# Generated by Django 5.2.9 on 2026-08-19 09:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0040_organisation_zweifaktor_pflicht'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schluessel', models.SlugField(max_length=40, verbose_name='Schlüssel')),
                ('bezeichnung', models.CharField(max_length=120, verbose_name='Bezeichnung')),
                ('entitlement', models.CharField(default='faelle', help_text='Schlüssel aus core.funktionen — steuert die Sichtbarkeit.', max_length=40, verbose_name='Funktionsschlüssel')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallarten', to='crm.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Fallart',
                'verbose_name_plural': 'Fallarten',
                'ordering': ('bezeichnung',),
            },
        ),
        migrations.CreateModel(
            name='Fall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(blank=True, max_length=20, verbose_name='Fallnummer')),
                ('akte_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('wartet_auf_dritte', 'Wartet auf Dritte'), ('ruht', 'Ruht'), ('abgeschlossen', 'Abgeschlossen'), ('abgebrochen', 'Abgebrochen')], default='offen', max_length=20, verbose_name='Status')),
                ('betreff', models.CharField(blank=True, max_length=200, verbose_name='Betreff')),
                ('notiz', models.TextField(blank=True, verbose_name='Notiz')),
                ('eroeffnet_am', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eröffnet')),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen')),
                ('letzte_bewegung', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Letzte Bewegung')),
                ('akte_typ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='faelle', to='crm.organisation', verbose_name='Organisation')),
                ('zustaendig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faelle', to=settings.AUTH_USER_MODEL)),
                ('fallart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faelle', to='faelle.fallart')),
            ],
            options={
                'verbose_name': 'Fall',
                'verbose_name_plural': 'Fälle',
                'ordering': ('-letzte_bewegung',),
            },
        ),
        migrations.CreateModel(
            name='SchrittVorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveSmallIntegerField(verbose_name='Reihenfolge')),
                ('etappe_nr', models.PositiveSmallIntegerField(verbose_name='Etappe')),
                ('etappe', models.CharField(max_length=80, verbose_name='Etappenbezeichnung')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Schritt')),
                ('hinweis', models.TextField(blank=True, verbose_name='Hinweis')),
                ('pflicht', models.BooleanField(default=True, verbose_name='Pflichtschritt')),
                ('frist_regel', models.CharField(blank=True, max_length=60, verbose_name='Fristregel')),
                ('fallart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schrittvorlagen', to='faelle.fallart')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='crm.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Schrittvorlage',
                'verbose_name_plural': 'Schrittvorlagen',
                'ordering': ('fallart', 'nr'),
            },
        ),
        migrations.CreateModel(
            name='Fallschritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveSmallIntegerField(verbose_name='Reihenfolge')),
                ('etappe_nr', models.PositiveSmallIntegerField(default=1, verbose_name='Etappe')),
                ('etappe', models.CharField(blank=True, max_length=80, verbose_name='Etappenbezeichnung')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Schritt')),
                ('pflicht', models.BooleanField(default=True, verbose_name='Pflichtschritt')),
                ('frist', models.DateField(blank=True, null=True, verbose_name='Frist')),
                ('erledigt_am', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt')),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('erledigt_durch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erledigte_fallschritte', to=settings.AUTH_USER_MODEL)),
                ('fall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schritte', to='faelle.fall')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='crm.organisation', verbose_name='Organisation')),
                ('vorlage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faelle.schrittvorlage')),
            ],
            options={
                'verbose_name': 'Fallschritt',
                'verbose_name_plural': 'Fallschritte',
                'ordering': ('fall', 'nr'),
            },
        ),
        migrations.CreateModel(
            name='Zeiteintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum')),
                ('minuten', models.PositiveIntegerField(verbose_name='Minuten')),
                ('taetigkeit', models.CharField(choices=[('bewirtschaftung', 'Bewirtschaftung'), ('buchhaltung', 'Buchhaltung'), ('korrespondenz', 'Korrespondenz'), ('sonder', 'Sonderaufwand')], default='bewirtschaftung', max_length=20, verbose_name='Tätigkeit')),
                ('notiz', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('verrechenbar', models.BooleanField(default=False, verbose_name='Separat verrechenbar')),
                ('benutzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zeiteintraege', to=settings.AUTH_USER_MODEL)),
                ('fall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeiteintraege', to='faelle.fall')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='crm.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Zeiteintrag',
                'verbose_name_plural': 'Zeiteinträge',
                'ordering': ('-datum', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='fallart',
            constraint=models.UniqueConstraint(fields=('organisation', 'schluessel'), name='fallart_je_organisation_eindeutig'),
        ),
        migrations.AddIndex(
            model_name='fall',
            index=models.Index(fields=['organisation', 'status'], name='faelle_fall_organis_a2fb04_idx'),
        ),
        migrations.AddIndex(
            model_name='fall',
            index=models.Index(fields=['akte_typ', 'akte_id'], name='faelle_fall_akte_ty_140379_idx'),
        ),
        migrations.AddConstraint(
            model_name='schrittvorlage',
            constraint=models.UniqueConstraint(fields=('fallart', 'nr'), name='schrittvorlage_nr_eindeutig'),
        ),
        migrations.AddConstraint(
            model_name='fallschritt',
            constraint=models.UniqueConstraint(fields=('fall', 'nr'), name='fallschritt_nr_eindeutig'),
        ),
        migrations.AddConstraint(
            model_name='zeiteintrag',
            constraint=models.CheckConstraint(condition=models.Q(('minuten__gt', 0)), name='zeiteintrag_minuten_positiv'),
        ),
    ]
