# Generated by Django 5.2.9 on 2026-08-19 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_organisation_zweifaktor_pflicht'),
        ('faelle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regelsatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=120, verbose_name='Bezeichnung')),
                ('kanton', models.CharField(blank=True, help_text='Leer bedeutet: gilt für alle Kantone dieser Verwaltung.', max_length=2, verbose_name='Kanton')),
                ('stand', models.DateField(default=django.utils.timezone.localdate, verbose_name='Stand')),
                ('geprueft', models.BooleanField(default=False, help_text='Ungeprüfte Regeln warnen, sie sperren nicht.', verbose_name='Juristisch geprüft')),
                ('hinweis', models.TextField(blank=True, verbose_name='Hinweis')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regelsaetze', to='crm.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Regelsatz',
                'verbose_name_plural': 'Regelsätze',
                'ordering': ('bezeichnung',),
            },
        ),
        migrations.CreateModel(
            name='Regel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('kuendigungstermin', 'Kündigungstermin und -frist'), ('zahlungsfrist', 'Zahlungsfrist bei Verzug'), ('mietzins_zustellung', 'Zustellfrist Mietzinsänderung'), ('kaution_hoechstbetrag', 'Höchstbetrag der Kaution')], max_length=40, verbose_name='Regelart')),
                ('verbindlichkeit', models.CharField(choices=[('warnung', 'Warnt, lässt aber weiterarbeiten'), ('sperre', 'Verhindert das Speichern')], default='warnung', max_length=10, verbose_name='Verbindlichkeit')),
                ('parameter', models.JSONField(blank=True, default=dict, verbose_name='Parameter')),
                ('begruendung', models.TextField(blank=True, help_text='Woher die Regel stammt. Steht im Hinweistext für die Bearbeitung.', verbose_name='Begründung')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='crm.organisation', verbose_name='Organisation')),
                ('regelsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regeln', to='faelle.regelsatz')),
            ],
            options={
                'verbose_name': 'Regel',
                'verbose_name_plural': 'Regeln',
                'ordering': ('regelsatz', 'art'),
            },
        ),
        migrations.CreateModel(
            name='Regelanwendung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=40, verbose_name='Regelart')),
                ('regel_stand', models.DateField(help_text='Fassung, unter der geprüft wurde — Schlüssel für Berichtigungen.', verbose_name='Stand der Regel')),
                ('geprueft_war', models.BooleanField(default=False, verbose_name='Regel war juristisch geprüft')),
                ('eingabe', models.JSONField(default=dict, verbose_name='Eingabe')),
                ('ergebnis', models.JSONField(default=dict, verbose_name='Ergebnis')),
                ('befund', models.CharField(choices=[('ok', 'Ohne Beanstandung'), ('beanstandet', 'Beanstandet')], max_length=15, verbose_name='Befund')),
                ('meldung', models.TextField(blank=True, verbose_name='Meldung')),
                ('uebersteuert', models.BooleanField(default=False, verbose_name='Übersteuert')),
                ('uebersteuert_begruendung', models.TextField(blank=True, verbose_name='Begründung')),
                ('zeitpunkt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zeitpunkt')),
                ('fall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regelanwendungen', to='faelle.fall')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='regelanwendungen', to='crm.organisation')),
                ('uebersteuert_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regeluebersteuerungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regelanwendung',
                'verbose_name_plural': 'Regelanwendungen',
                'ordering': ('-zeitpunkt',),
                'indexes': [models.Index(fields=['organisation', 'art', 'regel_stand'], name='faelle_rege_organis_065d23_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='regelsatz',
            constraint=models.UniqueConstraint(fields=('organisation', 'kanton'), name='regelsatz_je_organisation_und_kanton'),
        ),
        migrations.AddConstraint(
            model_name='regel',
            constraint=models.UniqueConstraint(fields=('regelsatz', 'art'), name='regel_je_satz_und_art'),
        ),
    ]
