# Generated by Django 5.2.9 on 2026-08-19 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0040_organisation_zweifaktor_pflicht'),
        ('faelle', '0002_regelsatz_regel_regelanwendung_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eingang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quelle', models.CharField(choices=[('mail', 'E-Mail'), ('post', 'Post'), ('scan', 'Scan'), ('portal', 'Portalmeldung'), ('bank', 'Bankeingang')], max_length=10, verbose_name='Quelle')),
                ('eingegangen_am', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eingegangen')),
                ('betreff', models.CharField(blank=True, max_length=300, verbose_name='Betreff')),
                ('absender', models.CharField(blank=True, max_length=200, verbose_name='Absender')),
                ('absender_norm', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Absender (normalisiert)')),
                ('absender_email', models.EmailField(blank=True, max_length=254, verbose_name='Absenderadresse')),
                ('referenz', models.CharField(blank=True, db_index=True, help_text='QR-Referenz, Sendungsnummer oder ähnliches.', max_length=60, verbose_name='Referenz')),
                ('text', models.TextField(blank=True, verbose_name='Inhalt')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('zugeordnet', 'Zugeordnet'), ('abgelegt', 'Abgelegt ohne Folge')], default='offen', max_length=12, verbose_name='Status')),
                ('akte_id', models.PositiveIntegerField(blank=True, null=True)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt')),
                ('ablage_grund', models.CharField(blank=True, max_length=200, verbose_name='Grund der Ablage')),
                ('akte_typ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('erledigt_durch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zulauf_erledigt', to=settings.AUTH_USER_MODEL)),
                ('fall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eingaenge', to='faelle.fall')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='zulauf', to='crm.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Eingang',
                'verbose_name_plural': 'Zulauf',
                'ordering': ('-eingegangen_am',),
                'indexes': [models.Index(fields=['organisation', 'status'], name='faelle_eing_organis_d07a14_idx')],
            },
        ),
        migrations.CreateModel(
            name='Zuordnungsregel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merkmal', models.CharField(choices=[('absender', 'Absendername'), ('email', 'Absenderadresse'), ('referenz', 'Referenz')], max_length=12, verbose_name='Merkmal')),
                ('wert', models.CharField(db_index=True, max_length=200, verbose_name='Wert (normalisiert)')),
                ('wert_anzeige', models.CharField(blank=True, max_length=200, verbose_name='Wert')),
                ('akte_id', models.PositiveIntegerField()),
                ('treffer', models.PositiveIntegerField(default=0, verbose_name='Automatisch getroffen')),
                ('zuletzt', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt getroffen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('akte_typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('fallart', models.ForeignKey(blank=True, help_text='Gesetzt: Ein Treffer eröffnet einen Fall dieser Art.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zuordnungsregeln', to='faelle.fallart')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='zuordnungsregeln', to='crm.organisation')),
            ],
            options={
                'verbose_name': 'Zuordnungsregel',
                'verbose_name_plural': 'Zuordnungsregeln',
                'ordering': ('-treffer',),
                'constraints': [models.UniqueConstraint(fields=('organisation', 'merkmal', 'wert'), name='zuordnungsregel_je_merkmal_eindeutig')],
            },
        ),
    ]
