# Generated by Django 5.2.9 on 2026-08-19 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_organisation_zweifaktor_pflicht'),
        ('faelle', '0003_eingang_zuordnungsregel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lauf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=10, verbose_name='Periode')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('laeuft', 'Läuft'), ('abgeschlossen', 'Abgeschlossen'), ('uebersprungen', 'Bewusst übersprungen')], default='offen', max_length=15, verbose_name='Status')),
                ('faellig_am', models.DateField(verbose_name='Fällig am')),
                ('gestartet_am', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet')),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen')),
                ('kennzahlen', models.JSONField(blank=True, default=dict, verbose_name='Kennzahlen')),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('abgeschlossen_durch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abgeschlossene_laeufe', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='crm.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Lauf',
                'verbose_name_plural': 'Läufe',
                'ordering': ('faellig_am', 'laufart__reihenfolge'),
            },
        ),
        migrations.CreateModel(
            name='Blockade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grund', models.CharField(max_length=200, verbose_name='Grund')),
                ('quelle', models.CharField(blank=True, help_text='Woher der Hinweis stammt — Akte, Lauf oder Prüfung.', max_length=120, verbose_name='Quelle')),
                ('seit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Seit')),
                ('behoben_am', models.DateTimeField(blank=True, null=True, verbose_name='Behoben')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='crm.organisation', verbose_name='Organisation')),
                ('lauf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockaden', to='faelle.lauf')),
            ],
            options={
                'verbose_name': 'Blockade',
                'verbose_name_plural': 'Blockaden',
                'ordering': ('-seit',),
            },
        ),
        migrations.CreateModel(
            name='Laufart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schluessel', models.SlugField(max_length=40, verbose_name='Schlüssel')),
                ('bezeichnung', models.CharField(max_length=120, verbose_name='Bezeichnung')),
                ('rhythmus', models.CharField(choices=[('monatlich', 'Monatlich'), ('quartalsweise', 'Quartalsweise'), ('jaehrlich', 'Jährlich')], default='monatlich', max_length=15, verbose_name='Rhythmus')),
                ('faellig_am_tag', models.PositiveSmallIntegerField(default=1, help_text='Vorgabe der Verwaltung, keine Frist aus dem Gesetz.', verbose_name='Fällig am Tag im Monat')),
                ('reihenfolge', models.PositiveSmallIntegerField(default=10, verbose_name='Reihenfolge')),
                ('entitlement', models.CharField(default='monatslauf', max_length=40, verbose_name='Funktionsschlüssel')),
                ('ziel_ansicht', models.CharField(blank=True, help_text='Name der bestehenden View, die den Lauf tatsächlich ausführt.', max_length=80, verbose_name='Ansicht')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laufarten', to='crm.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Laufart',
                'verbose_name_plural': 'Laufarten',
                'ordering': ('reihenfolge', 'bezeichnung'),
            },
        ),
        migrations.AddField(
            model_name='lauf',
            name='laufart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laeufe', to='faelle.laufart'),
        ),
        migrations.AddConstraint(
            model_name='laufart',
            constraint=models.UniqueConstraint(fields=('organisation', 'schluessel'), name='laufart_je_organisation_eindeutig'),
        ),
        migrations.AddIndex(
            model_name='lauf',
            index=models.Index(fields=['organisation', 'status', 'faellig_am'], name='faelle_lauf_organis_4659c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='lauf',
            constraint=models.UniqueConstraint(fields=('laufart', 'periode'), name='lauf_je_art_und_periode_eindeutig'),
        ),
    ]
