# Generated by Django 5.2.9 on 2026-08-20 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("crm", "0040_organisation_zweifaktor_pflicht"),
        ("faelle", "0004_lauf_blockade_laufart_lauf_laufart_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Abwesenheit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("von", models.DateField(verbose_name="Von")),
                ("bis", models.DateField(verbose_name="Bis (einschliesslich)")),
                (
                    "grund",
                    models.CharField(
                        choices=[
                            ("ferien", "Ferien"),
                            ("krank", "Krank"),
                            ("schulung", "Schulung"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        default="ferien",
                        max_length=12,
                        verbose_name="Grund",
                    ),
                ),
                (
                    "notiz",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Notiz"
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erfasst"),
                ),
                (
                    "benutzer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abwesenheiten",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Wer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abwesenheiten",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "vertreten_durch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vertretungen",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vertretung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abwesenheit",
                "verbose_name_plural": "Abwesenheiten",
                "ordering": ("von",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "von", "bis"],
                        name="faelle_abwe_organis_b0c0a8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Termin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("abnahme", "Wohnungsabnahme"),
                            ("besichtigung", "Besichtigung"),
                            ("gespraech", "Eigentümergespräch"),
                            ("begehung", "Begehung"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        default="sonstiges",
                        max_length=15,
                        verbose_name="Art",
                    ),
                ),
                ("titel", models.CharField(max_length=200, verbose_name="Titel")),
                ("beginn", models.DateTimeField(verbose_name="Beginn")),
                (
                    "dauer_minuten",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="Dauer (Minuten)"
                    ),
                ),
                (
                    "ort",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Ort"
                    ),
                ),
                ("akte_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("geplant", "Geplant"),
                            ("erledigt", "Erledigt"),
                            ("abgesagt", "Abgesagt"),
                        ],
                        default="geplant",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notiz",
                    models.TextField(blank=True, default="", verbose_name="Notiz"),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erfasst"),
                ),
                (
                    "akte_typ",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termine",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "zustaendig",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="termine",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Termin",
                "verbose_name_plural": "Termine",
                "ordering": ("beginn",),
                "indexes": [
                    models.Index(
                        fields=["organisation", "beginn"],
                        name="faelle_term_organis_87d14d_idx",
                    )
                ],
            },
        ),
    ]
