# Generated by Django 5.2.9 on 2026-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faelle', '0005_abwesenheit_termin'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeiteintrag',
            name='satz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stundensatz (CHF)'),
        ),
    ]
