# Generated by Django 5.2.9 on 2025-12-31 13:00

import ckeditor.fields
import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DokumentVorlage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=100)),
                ("inhalt", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name="Handwerker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firmenname", models.CharField(max_length=100)),
                ("branche", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Liegenschaft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "strasse",
                    models.CharField(max_length=100, verbose_name="Strasse & Nr."),
                ),
                ("plz", models.CharField(max_length=10, verbose_name="PLZ")),
                ("ort", models.CharField(max_length=100, verbose_name="Ort")),
                (
                    "kanton",
                    models.CharField(default="ZH", max_length=2, verbose_name="Kanton"),
                ),
                (
                    "egid",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="EGID"
                    ),
                ),
                ("konto_iban", models.CharField(max_length=34, verbose_name="IBAN")),
                (
                    "auto_import",
                    models.BooleanField(
                        default=False, verbose_name="Wohnungen vom Bund laden"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Liegenschaften",
            },
        ),
        migrations.CreateModel(
            name="Mieter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nachname", models.CharField(max_length=100)),
                ("vorname", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name_plural": "Mieter",
            },
        ),
        migrations.CreateModel(
            name="Einheit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bezeichnung", models.CharField(max_length=100)),
                (
                    "zimmer",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "flaeche_m2",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="m²"
                    ),
                ),
                ("etage", models.IntegerField(default=0)),
                ("typ", models.CharField(default="WOHNEN", max_length=20)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="einheiten",
                        to="core.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Einheiten",
            },
        ),
        migrations.CreateModel(
            name="Mietvertrag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("netto_mietzins", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "nk_akonto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("aktiv", models.BooleanField(default=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.einheit"
                    ),
                ),
                (
                    "mieter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.mieter"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mietverträge",
            },
        ),
        migrations.CreateModel(
            name="SchadenMeldung",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("betreff", models.CharField(max_length=100)),
                ("beschreibung", models.TextField(blank=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="schaden_fotos/"
                    ),
                ),
                (
                    "prioritaet",
                    models.CharField(
                        choices=[
                            ("HOCH", "Hoch"),
                            ("MITTEL", "Mittel"),
                            ("NIEDRIG", "Niedrig"),
                        ],
                        default="MITTEL",
                        max_length=10,
                    ),
                ),
                ("status", models.CharField(default="NEU", max_length=20)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "mietvertrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schadensmeldungen",
            },
        ),
        migrations.CreateModel(
            name="Schluessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schluessel_nummer", models.CharField(max_length=50)),
                ("funktion", models.CharField(max_length=100)),
                ("bestand_total", models.PositiveIntegerField(default=1)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schlüsselverwaltung",
            },
        ),
        migrations.CreateModel(
            name="SchluesselAusgabe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ausgabe_datum", models.DateField(default=datetime.date.today)),
                ("rueckgabe_datum", models.DateField(blank=True, null=True)),
                (
                    "mieter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.mieter",
                    ),
                ),
                (
                    "schluessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ausleihen",
                        to="core.schluessel",
                    ),
                ),
            ],
        ),
    ]
