# Generated by Django 5.2.9 on 2026-07-07 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AktivitaetsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zeitpunkt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zeitpunkt"),
                ),
                ("aktion", models.CharField(max_length=100, verbose_name="Aktion")),
                (
                    "objekt",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Objekt"
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, default="", verbose_name="Details"),
                ),
                (
                    "benutzer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktivitätslog",
                "verbose_name_plural": "Aktivitätslog",
                "ordering": ["-zeitpunkt"],
            },
        ),
    ]
