# Generated by Django 5.2.9 on 2025-12-31 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dokumentvorlage",
            options={
                "verbose_name": "Dokumentvorlage",
                "verbose_name_plural": "Dokumentvorlagen",
            },
        ),
        migrations.AlterModelOptions(
            name="einheit",
            options={"verbose_name": "Einheit", "verbose_name_plural": "Einheiten"},
        ),
        migrations.AlterModelOptions(
            name="handwerker",
            options={"verbose_name": "Handwerker", "verbose_name_plural": "Handwerker"},
        ),
        migrations.AlterModelOptions(
            name="liegenschaft",
            options={
                "ordering": ["ort", "strasse"],
                "verbose_name": "Liegenschaft",
                "verbose_name_plural": "Liegenschaften",
            },
        ),
        migrations.AlterModelOptions(
            name="mieter",
            options={"verbose_name": "Mieter", "verbose_name_plural": "Mieter"},
        ),
        migrations.AlterModelOptions(
            name="mietvertrag",
            options={
                "verbose_name": "Mietvertrag",
                "verbose_name_plural": "Mietverträge",
            },
        ),
        migrations.AlterModelOptions(
            name="schadenmeldung",
            options={
                "verbose_name": "Schadenmeldung",
                "verbose_name_plural": "Schadenmeldungen",
            },
        ),
        migrations.AlterModelOptions(
            name="schluessel",
            options={"verbose_name": "Schlüssel", "verbose_name_plural": "Schlüssel"},
        ),
        migrations.AlterModelOptions(
            name="schluesselausgabe",
            options={
                "verbose_name": "Schlüsselausgabe",
                "verbose_name_plural": "Schlüsselausgaben",
            },
        ),
        migrations.RenameField(
            model_name="handwerker",
            old_name="firmenname",
            new_name="firma",
        ),
        migrations.RenameField(
            model_name="schluesselausgabe",
            old_name="rueckgabe_datum",
            new_name="rueckgabe_am",
        ),
        migrations.RemoveField(
            model_name="dokumentvorlage",
            name="inhalt",
        ),
        migrations.RemoveField(
            model_name="handwerker",
            name="branche",
        ),
        migrations.RemoveField(
            model_name="liegenschaft",
            name="auto_import",
        ),
        migrations.RemoveField(
            model_name="liegenschaft",
            name="konto_iban",
        ),
        migrations.RemoveField(
            model_name="mietvertrag",
            name="nk_akonto",
        ),
        migrations.RemoveField(
            model_name="schadenmeldung",
            name="foto",
        ),
        migrations.RemoveField(
            model_name="schadenmeldung",
            name="mietvertrag",
        ),
        migrations.RemoveField(
            model_name="schluessel",
            name="bestand_total",
        ),
        migrations.RemoveField(
            model_name="schluesselausgabe",
            name="ausgabe_datum",
        ),
        migrations.AddField(
            model_name="dokumentvorlage",
            name="beschreibung",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dokumentvorlage",
            name="datei",
            field=models.FileField(default="platzhalter.pdf", upload_to="vorlagen/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="einheit",
            name="ewid",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="EWID (Wohnungs-ID)"
            ),
        ),
        migrations.AddField(
            model_name="handwerker",
            name="gewerk",
            field=models.CharField(
                default="Allgemein", max_length=50, verbose_name="Gewerk (z.B. Sanitär)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="handwerker",
            name="kontaktperson",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="handwerker",
            name="telefon",
            field=models.CharField(default="000000", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="aktualisiert_am",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="baujahr",
            field=models.IntegerField(blank=True, null=True, verbose_name="Baujahr"),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="bild",
            field=models.ImageField(
                blank=True, null=True, upload_to="liegenschaften/", verbose_name="Bild"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="erstellt_am",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="iban",
            field=models.CharField(
                blank=True, max_length=34, verbose_name="IBAN für Mieteingang"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="anrede",
            field=models.CharField(
                choices=[("Herr", "Herr"), ("Frau", "Frau"), ("Firma", "Firma")],
                default="Herr",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="geburtsdatum",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mieter",
            name="telefon",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="beginn",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Mietbeginn"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="ende",
            field=models.DateField(blank=True, null=True, verbose_name="Mietende"),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="nebenkosten",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Nebenkosten (Akonto)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="bild",
            field=models.ImageField(blank=True, null=True, upload_to="schaeden/"),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="einheit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.einheit",
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="gemeldet_von",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.mieter",
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="liegenschaft",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.liegenschaft",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schluessel",
            name="verfuegbar",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schluesselausgabe",
            name="ausgegeben_am",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="bezeichnung",
            field=models.CharField(
                max_length=50, verbose_name="Bezeichnung (z.B. 1. OG links)"
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="etage",
            field=models.CharField(blank=True, max_length=20, verbose_name="Etage"),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="flaeche_m2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Fläche (m²)",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="typ",
            field=models.CharField(
                choices=[
                    ("whg", "Wohnung"),
                    ("gew", "Gewerbe"),
                    ("pp", "Parkplatz"),
                    ("bas", "Bastelraum"),
                ],
                default="whg",
                max_length=3,
                verbose_name="Typ",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="zimmer",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Zimmer",
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="egid",
            field=models.CharField(
                blank=True, default=1, max_length=20, verbose_name="EGID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="kanton",
            field=models.CharField(blank=True, max_length=2, verbose_name="Kanton"),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="strasse",
            field=models.CharField(max_length=200, verbose_name="Strasse & Nr."),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="vorname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="aktiv",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="einheit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.einheit"
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="mieter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.mieter"
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="netto_mietzins",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Netto Mietzins"
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="beschreibung",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="betreff",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="prioritaet",
            field=models.CharField(
                choices=[
                    ("niedrig", "Niedrig"),
                    ("mittel", "Mittel"),
                    ("hoch", "Hoch"),
                ],
                default="mittel",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="status",
            field=models.CharField(
                choices=[
                    ("offen", "Offen"),
                    ("beauftragt", "In Bearbeitung"),
                    ("erledigt", "Erledigt"),
                ],
                default="offen",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="schluessel",
            name="funktion",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Funktion (z.B. Haustür)"
            ),
        ),
        migrations.AlterField(
            model_name="schluessel",
            name="schluessel_nummer",
            field=models.CharField(max_length=50, verbose_name="Schlüssel-Nr."),
        ),
        migrations.AlterField(
            model_name="schluesselausgabe",
            name="mieter",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.mieter"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schluesselausgabe",
            name="schluessel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.schluessel"
            ),
        ),
    ]
