# Generated by Django 5.2.9 on 2026-01-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_dokumentvorlage_options_alter_einheit_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="einheit",
            options={
                "ordering": ["bezeichnung"],
                "verbose_name": "Einheit",
                "verbose_name_plural": "Einheiten",
            },
        ),
        migrations.AddField(
            model_name="einheit",
            name="bemerkung",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="einheit",
            name="nebenkosten_ak",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                verbose_name="Nebenkosten (Akonto)",
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="nettomiete",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Aktuelle Marktmiete",
                max_digits=8,
                verbose_name="Nettomiete (Soll)",
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="referenzzinssatz",
            field=models.DecimalField(
                decimal_places=2,
                default=1.25,
                help_text="Aktueller Referenzzinssatz",
                max_digits=4,
                verbose_name="Ref. Zinssatz (%)",
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="wertquote",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Für Kostenverteilung (z.B. 100/1000)",
                max_digits=8,
                null=True,
                verbose_name="Wertquote / Punkte",
            ),
        ),
    ]
