# Generated by Django 5.2.9 on 2026-07-08 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rollen_gruppen"),
        ("portfolio", "0014_liegenschaft_hkvo_aktiv_and_more"),
        ("rentals", "0012_mietvertrag_mwst_satz"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pendenz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "beschreibung",
                    models.TextField(
                        blank=True, default="", verbose_name="Beschreibung"
                    ),
                ),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("frist", "Frist"),
                            ("aufgabe", "Aufgabe"),
                            ("vertrag", "Vertrag"),
                            ("finanzen", "Finanzen"),
                            ("unterhalt", "Unterhalt"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        default="aufgabe",
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "faellig_am",
                    models.DateField(blank=True, null=True, verbose_name="Fällig am"),
                ),
                (
                    "erledigt",
                    models.BooleanField(default=False, verbose_name="Erledigt"),
                ),
                (
                    "erledigt_am",
                    models.DateField(blank=True, null=True, verbose_name="Erledigt am"),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pendenzen",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "vertrag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pendenzen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pendenz",
                "verbose_name_plural": "Pendenzen",
                "ordering": ["erledigt", "faellig_am", "-erstellt_am"],
            },
        ),
    ]
