# Generated by Django 5.2.9 on 2026-07-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pendenz"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendenz",
            name="quelle",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=80,
                verbose_name="Quelle",
            ),
        ),
    ]
