# Generated by Django 5.2.9 on 2026-01-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_einheit_options_einheit_bemerkung_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="landesindex_datum",
            field=models.CharField(
                blank=True,
                help_text="z.B. 'Mai 2023' oder 'Basis Dez 2020'",
                max_length=50,
                verbose_name="Index-Stand (Datum)",
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="landesindex_punkte",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Stand des LIK (z.B. 107.4)",
                max_digits=6,
                null=True,
                verbose_name="Landesindex (Punkte)",
            ),
        ),
    ]
