# Generated by Django 5.2.9 on 2026-07-11 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_pendenz_quelle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aktivitaetslog",
            name="ziel_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Ziel-ID"
            ),
        ),
        migrations.AddField(
            model_name="aktivitaetslog",
            name="ziel_typ",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=20,
                verbose_name="Ziel-Typ",
            ),
        ),
        migrations.AddIndex(
            model_name="aktivitaetslog",
            index=models.Index(
                fields=["ziel_typ", "ziel_id"], name="core_aktivi_ziel_ty_ec3262_idx"
            ),
        ),
    ]
