# Generated by Django 5.2.9 on 2026-01-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_einheit_landesindex_datum_einheit_landesindex_punkte"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="einheit",
            name="wertquote",
        ),
        migrations.AlterField(
            model_name="einheit",
            name="bezeichnung",
            field=models.CharField(max_length=50, verbose_name="Bezeichnung"),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="ewid",
            field=models.CharField(blank=True, max_length=20, verbose_name="EWID"),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="landesindex_datum",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Index-Stand (Datum)"
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="landesindex_punkte",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Landesindex (Punkte)",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="nettomiete",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Nettomiete (Soll)",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="referenzzinssatz",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Ref. Zinssatz (%)",
            ),
        ),
    ]
