# Generated by Django 5.2.9 on 2026-07-11 17:19

from django.db import migrations, models


def _backfill_kategorie(apps, schema_editor):
    """Bestehende Logeinträge nachträglich kategorisieren (aus dem Aktionstext)."""
    from core.auth import kategorie_fuer
    Log = apps.get_model('core', 'AktivitaetsLog')
    for e in Log.objects.filter(kategorie=''):
        e.kategorie = kategorie_fuer(e.aktion)
        e.save(update_fields=['kategorie'])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_aktivitaetslog_ziel_id_aktivitaetslog_ziel_typ_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aktivitaetslog",
            name="ip_adresse",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP-Adresse"
            ),
        ),
        migrations.AddField(
            model_name="aktivitaetslog",
            name="kategorie",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=20,
                verbose_name="Kategorie",
            ),
        ),
        migrations.RunPython(_backfill_kategorie, migrations.RunPython.noop),
    ]
