# Generated by Django 5.2.9 on 2026-01-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_einheit_wertquote_alter_einheit_bezeichnung_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="referenzzinssatz_datum",
            field=models.CharField(
                blank=True,
                help_text="Gültigkeit des Zinssatzes",
                max_length=100,
                verbose_name="Ref. Zins (Datum)",
            ),
        ),
    ]
