# Generated by Django 5.2.9 on 2026-01-02 11:43

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_einheit_referenzzinssatz_datum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dokument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("Vertrag", "Vertragsunterlagen"),
                            ("Korrespondenz", "Korrespondenz"),
                            ("Rechtliches", "Rechtliches & Formulare"),
                            ("Protokolle", "Protokolle"),
                            ("Objekt", "Objekt-Schriftverkehr"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "datei",
                    models.FileField(upload_to=core.models.get_smart_upload_path),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MietzinsAnpassung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("erstellt_am", models.DateField(auto_now_add=True)),
                ("wirksam_ab", models.DateField(verbose_name="Wirksam ab")),
                ("alte_miete", models.DecimalField(decimal_places=2, max_digits=8)),
                ("neue_miete", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "erhoehung_prozent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("begruendung", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("sent", "Versendet"),
                            ("signed", "Akzeptiert"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DokumentVorlage",
        ),
        migrations.RenameField(
            model_name="einheit",
            old_name="nebenkosten_ak",
            new_name="nebenkosten_aktuell",
        ),
        migrations.RenameField(
            model_name="einheit",
            old_name="nettomiete",
            new_name="nettomiete_aktuell",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="landesindex_datum",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="landesindex_punkte",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="referenzzinssatz",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="referenzzinssatz_datum",
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="basis_lik_jahr",
            field=models.CharField(
                default="2020",
                help_text="z.B. 2020",
                max_length=4,
                verbose_name="Basis LIK Jahr",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="basis_lik_punkte",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=6,
                null=True,
                verbose_name="Basis LIK (Punkte)",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="basis_referenzzinssatz",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Basis Ref.Zins (%)",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="erstellt_am",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="einheit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertraege",
                to="core.einheit",
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="mieter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertraege",
                to="core.mieter",
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="nebenkosten",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Nebenkosten"
            ),
        ),
        migrations.AlterField(
            model_name="schluessel",
            name="funktion",
            field=models.CharField(blank=True, max_length=100, verbose_name="Funktion"),
        ),
        migrations.AddField(
            model_name="dokument",
            name="einheit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.einheit",
            ),
        ),
        migrations.AddField(
            model_name="dokument",
            name="mietvertrag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.mietvertrag",
            ),
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="mietvertrag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anpassungen",
                to="core.mietvertrag",
            ),
        ),
    ]
