# Generated by Django 5.2.9 on 2026-08-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_aktivitaetslog_ip_adresse_aktivitaetslog_kategorie"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendenz",
            name="frist_tage",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Fristdauer ab Zugang (Tage)"
            ),
        ),
        migrations.AddField(
            model_name="pendenz",
            name="sendungsnummer",
            field=models.CharField(
                blank=True,
                default="",
                max_length=40,
                verbose_name="Sendungsnummer (Einschreiben)",
            ),
        ),
        migrations.AddField(
            model_name="pendenz",
            name="versand_am",
            field=models.DateField(blank=True, null=True, verbose_name="Versendet am"),
        ),
        migrations.AddField(
            model_name="pendenz",
            name="zugang_am",
            field=models.DateField(
                blank=True, null=True, verbose_name="Zugang bestätigt am"
            ),
        ),
    ]
