# Generated by Django 5.2.9 on 2026-01-02 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_dokument_mietzinsanpassung_delete_dokumentvorlage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mieter",
            options={
                "ordering": ["nachname", "vorname"],
                "verbose_name": "Mieter",
                "verbose_name_plural": "Mieter",
            },
        ),
        migrations.AddField(
            model_name="mieter",
            name="adresszusatz",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Adresszusatz (c/o)"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="ahv_nummer",
            field=models.CharField(
                blank=True,
                help_text="Format: 756.xxxx.xxxx.xx",
                max_length=20,
                verbose_name="AHV-Nummer",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="aktiv",
            field=models.BooleanField(default=True, verbose_name="Ist aktiver Mieter"),
        ),
        migrations.AddField(
            model_name="mieter",
            name="aktualisiert_am",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="mieter",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Name der Bank"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="bemerkung",
            field=models.TextField(blank=True, verbose_name="Interne Notizen"),
        ),
        migrations.AddField(
            model_name="mieter",
            name="beruf",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Beruf / Arbeitgeber"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="betreibungs_status",
            field=models.CharField(
                choices=[
                    ("ungeprueft", "Ungeprüft"),
                    ("sauber", "Betreibungsregister sauber"),
                    ("eintraege", "Hat Einträge"),
                    ("unbekannt", "Unbekannt"),
                ],
                default="ungeprueft",
                max_length=20,
                verbose_name="Betreibungsauskunft",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="erstellt_am",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mieter",
            name="haftpflicht_vers",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Privathaftpflicht (Versicherung & Police)",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="heimatort",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Heimatort (CH)"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="iban",
            field=models.CharField(
                blank=True,
                help_text="Für Rückzahlungen (z.B. NK-Abrechnung)",
                max_length=34,
                verbose_name="Bankverbindung (IBAN)",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="nationalitaet",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Nationalität"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="ort",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ort"),
        ),
        migrations.AddField(
            model_name="mieter",
            name="plz",
            field=models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
        ),
        migrations.AddField(
            model_name="mieter",
            name="strasse",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Strasse & Nr."
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="telefon_geschaeft",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Telefon Geschäft"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="zivilstand",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ledig", "Ledig"),
                    ("verheiratet", "Verheiratet"),
                    ("geschieden", "Geschieden"),
                    ("verwitwet", "Verwitwet"),
                ],
                default="ledig",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="anrede",
            field=models.CharField(
                choices=[
                    ("Herr", "Herr"),
                    ("Frau", "Frau"),
                    ("Firma", "Firma"),
                    ("Familie", "Familie"),
                ],
                default="Herr",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-Mail Privat"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="geburtsdatum",
            field=models.DateField(blank=True, null=True, verbose_name="Geburtsdatum"),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="telefon",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Mobile / Telefon"
            ),
        ),
    ]
