# Generated by Django 5.2.9 on 2026-01-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_mieter_options_mieter_adresszusatz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="kaution_bank",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Kautionskonto bei Bank"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kaution_hoehe",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Kaution (CHF)",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kuendigungsfrist",
            field=models.IntegerField(
                default=3, verbose_name="Kündigungsfrist (Monate)"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kuendigungstermine",
            field=models.CharField(
                default="monatlich (ausser Dez.)",
                max_length=100,
                verbose_name="Kündigungstermine",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="mindestdauer",
            field=models.CharField(
                blank=True, help_text="z.B. 1 Jahr fest", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="nk_typ",
            field=models.CharField(
                choices=[
                    ("akonto", "Akonto"),
                    ("pauschal", "Pauschal"),
                    ("keine", "Keine"),
                ],
                default="akonto",
                max_length=10,
                verbose_name="NK Abrechnungstyp",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="vertrag_scan",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="vertraege_scans/",
                verbose_name="Scan des Vertrags (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="haftpflicht_vers",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Privathaftpflicht"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="iban",
            field=models.CharField(
                blank=True, max_length=34, verbose_name="Bankverbindung (IBAN)"
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="aktiv",
            field=models.BooleanField(default=True, verbose_name="Laufender Vertrag"),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="ende",
            field=models.DateField(
                blank=True, null=True, verbose_name="Mietende (falls befristet)"
            ),
        ),
    ]
