# Generated by Django 5.2.9 on 2026-01-02 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_mietvertrag_kaution_bank_mietvertrag_kaution_hoehe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Geraet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("ks", "Kühlschrank"),
                            ("gs", "Geschirrspüler"),
                            ("wm", "Waschmaschine"),
                            ("tu", "Tumbler/Trockner"),
                            ("bh", "Backofen/Herd"),
                            ("da", "Dunstabzug"),
                            ("sonst", "Sonstiges"),
                        ],
                        max_length=10,
                        verbose_name="Gerätetyp",
                    ),
                ),
                (
                    "marke",
                    models.CharField(max_length=50, verbose_name="Marke (z.B. V-Zug)"),
                ),
                (
                    "modell",
                    models.CharField(max_length=100, verbose_name="Modell / Typ"),
                ),
                (
                    "seriennummer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Serien-Nr. (Sn)"
                    ),
                ),
                (
                    "installiert_am",
                    models.DateField(
                        blank=True, null=True, verbose_name="Installationsdatum"
                    ),
                ),
                (
                    "garantie_bis",
                    models.DateField(
                        blank=True, null=True, verbose_name="Garantie bis"
                    ),
                ),
                (
                    "anschaffungspreis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Preis (CHF)",
                    ),
                ),
                (
                    "zustand",
                    models.CharField(
                        choices=[
                            ("neu", "Neuwertig"),
                            ("ok", "Funktionsfähig"),
                            ("alt", "Alt/Ersetzen"),
                            ("defekt", "Defekt"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("notiz", models.TextField(blank=True)),
                (
                    "dokument",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="geraete_anleitungen/",
                        verbose_name="Anleitung/Garantieschein",
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geraete",
                        to="core.einheit",
                    ),
                ),
                (
                    "lieferant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.handwerker",
                        verbose_name="Lieferant/Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gerät",
                "verbose_name_plural": "Geräte & Inventar",
            },
        ),
        migrations.CreateModel(
            name="Unterhalt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titel",
                    models.CharField(max_length=200, verbose_name="Titel der Arbeit"),
                ),
                (
                    "datum",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Ausführungsdatum",
                    ),
                ),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("maler", "Malerarbeiten"),
                            ("boden", "Bodenbeläge"),
                            ("sanitaer", "Sanitär"),
                            ("elektro", "Elektro"),
                            ("kueche", "Küche"),
                            ("fenster", "Fenster/Storen"),
                            ("heizung", "Heizung"),
                            ("sonst", "Sonstiges"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("erhalt", "Werterhaltend (Unterhalt)"),
                            ("vermehr", "Wertvermehrend (Sanierung/Inv.)"),
                            ("gemischt", "Gemischt"),
                        ],
                        default="erhalt",
                        max_length=20,
                        verbose_name="Art der Investition",
                    ),
                ),
                (
                    "kosten",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Kosten (CHF)"
                    ),
                ),
                ("beschreibung", models.TextField(blank=True)),
                (
                    "rechnung_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="unterhalt_rechnungen/",
                        verbose_name="Rechnung (PDF)",
                    ),
                ),
                (
                    "garantie_bis",
                    models.DateField(
                        blank=True, null=True, verbose_name="Garantie auf Arbeit bis"
                    ),
                ),
                (
                    "ausgefuehrt_durch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.handwerker",
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unterhalt_eintraege",
                        to="core.einheit",
                        verbose_name="Betroffene Einheit (optional)",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unterhalt_eintraege",
                        to="core.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unterhalt/Sanierung",
                "verbose_name_plural": "Unterhalt & Sanierungen",
                "ordering": ["-datum"],
            },
        ),
    ]
