# Generated by Django 5.2.9 on 2026-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_organisation_pflicht"),
    ]

    operations = [
        migrations.CreateModel(
            name="SicherheitsEreignis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zeitpunkt",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Zeitpunkt"
                    ),
                ),
                ("aktion", models.CharField(max_length=100, verbose_name="Aktion")),
                (
                    "objekt",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Betroffen"
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, default="", verbose_name="Details"),
                ),
                (
                    "ip_adresse",
                    models.GenericIPAddressField(
                        blank=True, db_index=True, null=True, verbose_name="IP-Adresse"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sicherheitsereignis",
                "verbose_name_plural": "Sicherheitsereignisse",
                "ordering": ["-zeitpunkt"],
            },
        ),
    ]
