# Generated by Django 5.2.9 on 2026-01-02 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_geraet_unterhalt"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="bodenbelag",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Bodenbeläge (z.B. Parkett)"
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="briefkasten_nr",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Briefkasten Nr."
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="estrich_abteil",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Estrichabteil Nr."
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="keller_abteil",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Kellerabteil Nr."
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="wandfarbe",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Farbcode Wände (z.B. RAL 9010)"
            ),
        ),
        migrations.CreateModel(
            name="Zaehler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zaehler_nummer",
                    models.CharField(max_length=100, verbose_name="Zählernummer"),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("strom", "Strom"),
                            ("wasser_k", "Kaltwasser"),
                            ("wasser_w", "Warmwasser"),
                            ("heizung", "Heizung / Wärmezähler"),
                            ("gas", "Gas"),
                            ("oel", "Öl"),
                        ],
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "standort",
                    models.CharField(
                        blank=True, help_text="z.B. Keller, Schacht Bad", max_length=100
                    ),
                ),
                ("baujahr", models.IntegerField(blank=True, null=True)),
                (
                    "letzte_eichung",
                    models.DateField(
                        blank=True, null=True, verbose_name="Letzte Eichung/Ersatz"
                    ),
                ),
                ("notiz", models.TextField(blank=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zaehler",
                        to="core.einheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zähler",
                "verbose_name_plural": "Zähler (Wasser/Strom/Heizung)",
            },
        ),
    ]
