# Generated by Django 5.2.9 on 2026-08-18 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_sicherheitsereignis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wiederherstellungscode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(max_length=255, verbose_name="Code (Hash)"),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "eingeloest_am",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eingelöst am"
                    ),
                ),
                (
                    "benutzer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiederherstellungscodes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiederherstellungscode",
                "verbose_name_plural": "Wiederherstellungscodes",
                "ordering": ["erstellt_am"],
            },
        ),
        migrations.CreateModel(
            name="ZweiterFaktor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geheimnis",
                    models.CharField(max_length=64, verbose_name="Geheimnis (Base32)"),
                ),
                (
                    "bestaetigt_am",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bestätigt am"
                    ),
                ),
                (
                    "letztes_fenster",
                    models.BigIntegerField(
                        default=0, verbose_name="Zuletzt verbrauchtes Fenster"
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "letzte_verwendung",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zuletzt verwendet"
                    ),
                ),
                (
                    "benutzer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zweiter_faktor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zweiter Faktor",
                "verbose_name_plural": "Zweite Faktoren",
            },
        ),
    ]
