# Generated by Django 5.2.9 on 2026-01-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_einheit_bodenbelag_einheit_briefkasten_nr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="inserat_text",
            field=models.TextField(
                blank=True, verbose_name="Inseratetext (Beschreibung)"
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="inserat_titel",
            field=models.CharField(
                blank=True,
                help_text="z.B. Helle Dachwohnung mit Weitsicht",
                max_length=200,
                verbose_name="Titel für Inserat",
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="verfuegbar_ab",
            field=models.DateField(blank=True, null=True, verbose_name="Verfügbar ab"),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="bemerkung",
            field=models.TextField(
                blank=True, null=True, verbose_name="Interne Bemerkung"
            ),
        ),
        migrations.CreateModel(
            name="EinheitBild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bild",
                    models.ImageField(
                        upload_to="inserate_bilder/", verbose_name="Foto"
                    ),
                ),
                (
                    "titel",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Titel (z.B. Küche)"
                    ),
                ),
                (
                    "reihenfolge",
                    models.IntegerField(default=0, verbose_name="Reihenfolge"),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bilder",
                        to="core.einheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inserat-Bild",
                "verbose_name_plural": "Inserat-Bilder",
                "ordering": ["reihenfolge"],
            },
        ),
    ]
