# Generated by Django 5.2.9 on 2026-01-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_einheit_inserat_text_einheit_inserat_titel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="export_flatfox",
            field=models.BooleanField(default=False, verbose_name="Export zu Flatfox"),
        ),
        migrations.AddField(
            model_name="einheit",
            name="export_homegate",
            field=models.BooleanField(default=False, verbose_name="Export zu Homegate"),
        ),
        migrations.AddField(
            model_name="einheit",
            name="export_immoscout",
            field=models.BooleanField(
                default=False, verbose_name="Export zu ImmoScout24"
            ),
        ),
    ]
