# Generated by Django 5.2.9 on 2026-08-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_wiederherstellungscode_zweiterfaktor"),
        ("crm", "0040_organisation_zweifaktor_pflicht"),
    ]

    operations = [
        migrations.CreateModel(
            name="Postfach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zweck",
                    models.CharField(
                        choices=[
                            ("antworten", "Antworten auf Ticket-Mails"),
                            ("rechnungen", "Eingehende Kreditorenrechnungen"),
                        ],
                        max_length=20,
                        verbose_name="Zweck",
                    ),
                ),
                (
                    "verfahren",
                    models.CharField(
                        choices=[
                            ("passwort", "Benutzername und Passwort"),
                            ("oauth2", "OAuth2 (Microsoft 365)"),
                        ],
                        default="passwort",
                        max_length=20,
                        verbose_name="Verfahren",
                    ),
                ),
                (
                    "aktiv",
                    models.BooleanField(default=True, verbose_name="Eingang aktiv"),
                ),
                (
                    "server",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="IMAP-Server",
                    ),
                ),
                ("port", models.PositiveIntegerField(default=993, verbose_name="Port")),
                (
                    "benutzer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Benutzername / Adresse",
                    ),
                ),
                (
                    "ordner",
                    models.CharField(
                        default="INBOX", max_length=100, verbose_name="Ordner"
                    ),
                ),
                (
                    "passwort_geheim",
                    models.TextField(
                        blank=True, default="", verbose_name="Passwort (verschlüsselt)"
                    ),
                ),
                (
                    "mandant_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Verzeichnis-ID (Tenant)",
                    ),
                ),
                (
                    "anwendung_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Anwendungs-ID (Client)",
                    ),
                ),
                (
                    "refresh_token_geheim",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Refresh-Token (verschlüsselt)",
                    ),
                ),
                (
                    "letzter_abruf",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Letzter erfolgreicher Abruf",
                    ),
                ),
                (
                    "letzter_test",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Letzter Verbindungstest"
                    ),
                ),
                (
                    "letzter_fehler_am",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Letzter Fehler"
                    ),
                ),
                (
                    "letzter_fehler",
                    models.TextField(blank=True, default="", verbose_name="Fehlertext"),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postfaecher",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postfach",
                "verbose_name_plural": "Postfächer",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "zweck"),
                        name="ein_postfach_je_zweck_und_organisation",
                    )
                ],
            },
        ),
    ]
