# Generated by Django 5.2.9 on 2026-01-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_einheit_export_flatfox_einheit_export_homegate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="geak_klasse",
            field=models.CharField(
                choices=[
                    ("A", "A (Exzellent)"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G (Schlecht)"),
                    ("X", "Kein Ausweis"),
                ],
                default="X",
                max_length=1,
                verbose_name="GEAK Energieklasse",
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="nk_abrechnungsart",
            field=models.CharField(
                choices=[
                    ("akonto", "Akonto (Abrechnung)"),
                    ("pauschal", "Pauschal (Keine Abr.)"),
                    ("keine", "Keine / Direktzahlung"),
                ],
                default="akonto",
                max_length=10,
                verbose_name="NK-Abrechnungsart (Standard)",
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="tour_url",
            field=models.URLField(
                blank=True, verbose_name="Link zu 360° Tour / Matterport"
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="nebenkosten_aktuell",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                verbose_name="Nebenkosten (Soll)",
            ),
        ),
    ]
