# Generated by Django 5.2.9 on 2026-01-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_einheit_geak_klasse_einheit_nk_abrechnungsart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liegenschaft",
            name="versicherungswert",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Basis für Rendite-Berechnung",
                max_digits=12,
                null=True,
                verbose_name="Versicherungswert / Marktwert",
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="nebenkosten",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Nebenkosten",
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="netto_mietzins",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Netto Mietzins",
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="nk_typ",
            field=models.CharField(
                blank=True,
                choices=[
                    ("akonto", "Akonto"),
                    ("pauschal", "Pauschal"),
                    ("keine", "Keine"),
                ],
                max_length=10,
                verbose_name="NK Abrechnungstyp",
            ),
        ),
    ]
