# Generated by Django 5.2.9 on 2026-01-03 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_liegenschaft_versicherungswert_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liegenschaft",
            name="amtlicher_wert",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Steuerwert",
                max_digits=12,
                null=True,
                verbose_name="Amtlicher Wert",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="grundstueck_m2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Grundstücksfläche (m²)",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="parzellen_nummer",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Parzelle / Kataster-Nr."
            ),
        ),
        migrations.CreateModel(
            name="Anlage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("heizung", "Heizung (ca. 20-25 Jahre)"),
                            ("lift", "Lift (ca. 25-30 Jahre)"),
                            ("dach", "Dach / Flachdach (ca. 30-40 Jahre)"),
                            ("fassade", "Fassade (ca. 25-40 Jahre)"),
                            ("fenster", "Fenster (ca. 25-30 Jahre)"),
                            ("elektro", "Elektro / Steigleitungen (ca. 40 Jahre)"),
                            ("sanitaer", "Sanitär / Leitungen (ca. 40 Jahre)"),
                            ("sonst", "Sonstiges"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(
                        help_text="z.B. Personenlift Schindler",
                        max_length=100,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "installations_jahr",
                    models.IntegerField(verbose_name="Installations-Jahr"),
                ),
                (
                    "nutzungsdauer",
                    models.IntegerField(
                        default=25,
                        help_text="Wie lange hält das Bauteil normalerweise?",
                        verbose_name="Lebensdauer (Jahre)",
                    ),
                ),
                (
                    "wiederbeschaffungswert",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Was kostet der Ersatz ca.?",
                        max_digits=10,
                        null=True,
                        verbose_name="Geschätzte Kosten (CHF)",
                    ),
                ),
                ("bemerkung", models.TextField(blank=True)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anlagen",
                        to="core.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bauteil / Anlage",
                "verbose_name_plural": "Lebenszyklus & Bauteile",
                "ordering": ["installations_jahr"],
            },
        ),
    ]
