# Generated by Django 5.2.9 on 2026-01-04 10:19

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_liegenschaft_amtlicher_wert_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anlage",
            options={
                "ordering": ["installations_jahr"],
                "verbose_name": "Anlage",
                "verbose_name_plural": "Anlagen",
            },
        ),
        migrations.AlterModelOptions(
            name="einheitbild",
            options={
                "ordering": ["reihenfolge"],
                "verbose_name": "Bild",
                "verbose_name_plural": "Bilder",
            },
        ),
        migrations.AlterModelOptions(
            name="liegenschaft",
            options={
                "ordering": ["ort", "strasse"],
                "verbose_name": "Übersicht / Liste",
                "verbose_name_plural": "Alle Liegenschaften",
            },
        ),
        migrations.AlterModelOptions(
            name="unterhalt",
            options={
                "ordering": ["-datum"],
                "verbose_name": "Unterhalt",
                "verbose_name_plural": "Unterhalt",
            },
        ),
        migrations.AlterModelOptions(
            name="zaehler",
            options={"verbose_name": "Zähler", "verbose_name_plural": "Zähler"},
        ),
        migrations.AddField(
            model_name="einheit",
            name="wertquote",
            field=models.IntegerField(
                default=0,
                help_text="Anteil in Tausendstel (z.B. 125)",
                verbose_name="Wertquote (‰)",
            ),
        ),
        migrations.AlterField(
            model_name="anlage",
            name="bezeichnung",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="anlage",
            name="installations_jahr",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="anlage",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("heizung", "Heizung"),
                    ("lift", "Lift"),
                    ("dach", "Dach"),
                    ("fassade", "Fassade"),
                    ("fenster", "Fenster"),
                    ("elektro", "Elektro"),
                    ("sanitaer", "Sanitär"),
                    ("sonst", "Sonstiges"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="anlage",
            name="nutzungsdauer",
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name="anlage",
            name="wiederbeschaffungswert",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dokument",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("Vertrag", "Vertragsunterlagen"),
                    ("Korrespondenz", "Korrespondenz"),
                    ("Rechtliches", "Rechtliches"),
                    ("Protokolle", "Protokolle"),
                    ("Objekt", "Objekt-Schriftverkehr"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="bemerkung",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="bodenbelag",
            field=models.CharField(blank=True, max_length=100, verbose_name="Boden"),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="briefkasten_nr",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Briefkasten"
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="estrich_abteil",
            field=models.CharField(blank=True, max_length=50, verbose_name="Estrich"),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="export_flatfox",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="export_homegate",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="export_immoscout",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="geak_klasse",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("X", "Kein Ausweis"),
                ],
                default="X",
                max_length=1,
                verbose_name="GEAK",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="inserat_text",
            field=models.TextField(blank=True, verbose_name="Inserat Text"),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="inserat_titel",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Inserat Titel"
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="keller_abteil",
            field=models.CharField(blank=True, max_length=50, verbose_name="Keller"),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="nk_abrechnungsart",
            field=models.CharField(
                choices=[
                    ("akonto", "Akonto"),
                    ("pauschal", "Pauschal"),
                    ("keine", "Keine"),
                ],
                default="akonto",
                max_length=10,
                verbose_name="NK-Art",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="tour_url",
            field=models.URLField(blank=True, verbose_name="360° Tour"),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="wandfarbe",
            field=models.CharField(blank=True, max_length=50, verbose_name="Wandfarbe"),
        ),
        migrations.AlterField(
            model_name="einheitbild",
            name="bild",
            field=models.ImageField(upload_to="inserate_bilder/"),
        ),
        migrations.AlterField(
            model_name="einheitbild",
            name="reihenfolge",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="einheitbild",
            name="titel",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="anschaffungspreis",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="dokument",
            field=models.FileField(
                blank=True, null=True, upload_to="geraete_anleitungen/"
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="garantie_bis",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="installiert_am",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="lieferant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.handwerker",
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="marke",
            field=models.CharField(max_length=50, verbose_name="Marke"),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="modell",
            field=models.CharField(max_length=100, verbose_name="Modell"),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="seriennummer",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Serien-Nr."
            ),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="gewerk",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="amtlicher_wert",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Amtlicher Wert",
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="grundstueck_m2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Grundstück m²",
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="iban",
            field=models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="parzellen_nummer",
            field=models.CharField(blank=True, max_length=50, verbose_name="Parzelle"),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="versicherungswert",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Versicherungswert",
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="adresszusatz",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="ahv_nummer",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="aktiv",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="anrede",
            field=models.CharField(
                choices=[("Herr", "Herr"), ("Frau", "Frau"), ("Firma", "Firma")],
                default="Herr",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="bemerkung",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="beruf",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="betreibungs_status",
            field=models.CharField(default="ungeprueft", max_length=20),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="geburtsdatum",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="haftpflicht_vers",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="heimatort",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="iban",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="nationalitaet",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="ort",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="plz",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="strasse",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="telefon",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="telefon_geschaeft",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="zivilstand",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="aktiv",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="basis_lik_jahr",
            field=models.CharField(default="2020", max_length=4),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="basis_lik_punkte",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="basis_referenzzinssatz",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="beginn",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="ende",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="kaution_bank",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="kaution_hoehe",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="kuendigungsfrist",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="kuendigungstermine",
            field=models.CharField(default="monatlich", max_length=100),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="mindestdauer",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="nebenkosten",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="netto_mietzins",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="nk_typ",
            field=models.CharField(
                blank=True,
                choices=[
                    ("akonto", "Akonto"),
                    ("pauschal", "Pauschal"),
                    ("keine", "Keine"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="vertrag_scan",
            field=models.FileField(blank=True, null=True, upload_to="vertraege_scans/"),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="art",
            field=models.CharField(
                choices=[
                    ("erhalt", "Werterhalt"),
                    ("vermehr", "Wertvermehrung"),
                    ("gemischt", "Gemischt"),
                ],
                default="erhalt",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="datum",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="einheit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.einheit",
            ),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="garantie_bis",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("maler", "Malerarbeiten"),
                    ("boden", "Boden"),
                    ("sanitaer", "Sanitär"),
                    ("elektro", "Elektro"),
                    ("kueche", "Küche"),
                    ("fenster", "Fenster"),
                    ("heizung", "Heizung"),
                    ("sonst", "Sonstiges"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="kosten",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="rechnung_scan",
            field=models.FileField(
                blank=True, null=True, upload_to="unterhalt_rechnungen/"
            ),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="titel",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="letzte_eichung",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="standort",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="typ",
            field=models.CharField(
                choices=[
                    ("strom", "Strom"),
                    ("wasser_k", "Kaltwasser"),
                    ("wasser_w", "Warmwasser"),
                    ("heizung", "Heizung"),
                    ("gas", "Gas"),
                    ("oel", "Öl"),
                ],
                max_length=20,
                verbose_name="Art",
            ),
        ),
        migrations.CreateModel(
            name="AbrechnungsPeriode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(
                        default="Abrechnung 2025", max_length=100, verbose_name="Titel"
                    ),
                ),
                ("start_datum", models.DateField(verbose_name="Beginn")),
                ("ende_datum", models.DateField(verbose_name="Ende")),
                ("abgeschlossen", models.BooleanField(default=False)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abrechnungen",
                        to="core.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "NK-Abrechnung",
                "verbose_name_plural": "NK-Abrechnungen",
                "ordering": ["-start_datum"],
            },
        ),
        migrations.CreateModel(
            name="NebenkostenBeleg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("heizung", "Heizung / Öl / Gas"),
                            ("wasser", "Wasser / Abwasser"),
                            ("hauswart", "Hauswartung / Garten"),
                            ("strom", "Allgemeinstrom"),
                            ("lift", "Lift Service"),
                            ("admin", "Verwaltung / Honorar"),
                            ("sonst", "Sonstiges"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Text")),
                ("datum", models.DateField()),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Betrag (CHF)"
                    ),
                ),
                (
                    "verteilschluessel",
                    models.CharField(
                        choices=[
                            ("m2", "Nach Fläche (m²)"),
                            ("wertquote", "Nach Wertquote (1000stel)"),
                            ("verbrauch", "Nach Zähler (Verbrauch)"),
                            ("einheiten", "Nach Einheiten"),
                            ("manuell", "Manuell"),
                        ],
                        default="m2",
                        max_length=20,
                    ),
                ),
                (
                    "beleg_scan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.models.get_smart_upload_path,
                    ),
                ),
                (
                    "periode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belege",
                        to="core.abrechnungsperiode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnung",
                "verbose_name_plural": "Rechnungen",
            },
        ),
        migrations.CreateModel(
            name="ZaehlerStand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(default=django.utils.timezone.now)),
                (
                    "wert",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Stand"
                    ),
                ),
                (
                    "ablese_art",
                    models.CharField(
                        default="Jährliche Ablesung", max_length=50, verbose_name="Art"
                    ),
                ),
                (
                    "zaehler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staende",
                        to="core.zaehler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ablesung",
                "verbose_name_plural": "Ablesungen",
                "ordering": ["-datum"],
            },
        ),
    ]
