# Generated by Django 5.2.9 on 2026-01-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_anlage_options_alter_einheitbild_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liegenschaft",
            name="iban",
            field=models.CharField(
                blank=True,
                help_text="IBAN für Einzahlungsscheine",
                max_length=34,
                verbose_name="IBAN (für QR)",
            ),
        ),
    ]
