# Generated by Django 5.2.9 on 2026-01-05 09:35

import core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_liegenschaft_iban"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abrechnungsperiode",
            options={},
        ),
        migrations.AlterModelOptions(
            name="anlage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="einheit",
            options={"verbose_name": "Einheit", "verbose_name_plural": "Einheiten"},
        ),
        migrations.AlterModelOptions(
            name="einheitbild",
            options={},
        ),
        migrations.AlterModelOptions(
            name="geraet",
            options={},
        ),
        migrations.AlterModelOptions(
            name="handwerker",
            options={},
        ),
        migrations.AlterModelOptions(
            name="liegenschaft",
            options={
                "verbose_name": "Liegenschaft",
                "verbose_name_plural": "Liegenschaften",
            },
        ),
        migrations.AlterModelOptions(
            name="mieter",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mietvertrag",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nebenkostenbeleg",
            options={},
        ),
        migrations.AlterModelOptions(
            name="schadenmeldung",
            options={},
        ),
        migrations.AlterModelOptions(
            name="unterhalt",
            options={},
        ),
        migrations.AlterModelOptions(
            name="zaehler",
            options={},
        ),
        migrations.AlterModelOptions(
            name="zaehlerstand",
            options={},
        ),
        migrations.RenameField(
            model_name="geraet",
            old_name="installiert_am",
            new_name="installations_datum",
        ),
        migrations.RenameField(
            model_name="mietvertrag",
            old_name="kaution_hoehe",
            new_name="kautions_betrag",
        ),
        migrations.RenameField(
            model_name="mietzinsanpassung",
            old_name="erstellt_am",
            new_name="datum_erstellt",
        ),
        migrations.RemoveField(
            model_name="abrechnungsperiode",
            name="erstellt_am",
        ),
        migrations.RemoveField(
            model_name="anlage",
            name="bemerkung",
        ),
        migrations.RemoveField(
            model_name="dokument",
            name="mietvertrag",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="bemerkung",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="bodenbelag",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="briefkasten_nr",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="estrich_abteil",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="export_flatfox",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="export_homegate",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="export_immoscout",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="geak_klasse",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="inserat_text",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="inserat_titel",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="keller_abteil",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="tour_url",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="verfuegbar_ab",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="wandfarbe",
        ),
        migrations.RemoveField(
            model_name="einheitbild",
            name="reihenfolge",
        ),
        migrations.RemoveField(
            model_name="geraet",
            name="anschaffungspreis",
        ),
        migrations.RemoveField(
            model_name="geraet",
            name="dokument",
        ),
        migrations.RemoveField(
            model_name="geraet",
            name="lieferant",
        ),
        migrations.RemoveField(
            model_name="geraet",
            name="notiz",
        ),
        migrations.RemoveField(
            model_name="geraet",
            name="seriennummer",
        ),
        migrations.RemoveField(
            model_name="geraet",
            name="zustand",
        ),
        migrations.RemoveField(
            model_name="liegenschaft",
            name="aktualisiert_am",
        ),
        migrations.RemoveField(
            model_name="liegenschaft",
            name="amtlicher_wert",
        ),
        migrations.RemoveField(
            model_name="liegenschaft",
            name="bild",
        ),
        migrations.RemoveField(
            model_name="liegenschaft",
            name="erstellt_am",
        ),
        migrations.RemoveField(
            model_name="liegenschaft",
            name="grundstueck_m2",
        ),
        migrations.RemoveField(
            model_name="liegenschaft",
            name="parzellen_nummer",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="adresszusatz",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="ahv_nummer",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="aktiv",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="aktualisiert_am",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="bemerkung",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="beruf",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="betreibungs_status",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="erstellt_am",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="geburtsdatum",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="haftpflicht_vers",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="heimatort",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="iban",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="nationalitaet",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="ort",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="plz",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="strasse",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="telefon_geschaeft",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="zivilstand",
        ),
        migrations.RemoveField(
            model_name="mietvertrag",
            name="basis_lik_jahr",
        ),
        migrations.RemoveField(
            model_name="mietvertrag",
            name="erstellt_am",
        ),
        migrations.RemoveField(
            model_name="mietvertrag",
            name="kaution_bank",
        ),
        migrations.RemoveField(
            model_name="mietvertrag",
            name="kuendigungsfrist",
        ),
        migrations.RemoveField(
            model_name="mietvertrag",
            name="kuendigungstermine",
        ),
        migrations.RemoveField(
            model_name="mietvertrag",
            name="mindestdauer",
        ),
        migrations.RemoveField(
            model_name="mietvertrag",
            name="nk_typ",
        ),
        migrations.RemoveField(
            model_name="mietvertrag",
            name="vertrag_scan",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="alte_miete",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="begruendung",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="erhoehung_prozent",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="mietvertrag",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="status",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="wirksam_ab",
        ),
        migrations.RemoveField(
            model_name="schadenmeldung",
            name="bild",
        ),
        migrations.RemoveField(
            model_name="schadenmeldung",
            name="prioritaet",
        ),
        migrations.RemoveField(
            model_name="schluessel",
            name="verfuegbar",
        ),
        migrations.RemoveField(
            model_name="unterhalt",
            name="ausgefuehrt_durch",
        ),
        migrations.RemoveField(
            model_name="unterhalt",
            name="garantie_bis",
        ),
        migrations.RemoveField(
            model_name="unterhalt",
            name="kategorie",
        ),
        migrations.RemoveField(
            model_name="unterhalt",
            name="rechnung_scan",
        ),
        migrations.RemoveField(
            model_name="zaehler",
            name="baujahr",
        ),
        migrations.RemoveField(
            model_name="zaehler",
            name="letzte_eichung",
        ),
        migrations.RemoveField(
            model_name="zaehler",
            name="notiz",
        ),
        migrations.RemoveField(
            model_name="zaehlerstand",
            name="ablese_art",
        ),
        migrations.AddField(
            model_name="dokument",
            name="liegenschaft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.liegenschaft",
            ),
        ),
        migrations.AddField(
            model_name="dokument",
            name="mieter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.mieter",
            ),
        ),
        migrations.AddField(
            model_name="handwerker",
            name="iban",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="kataster_nummer",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Kataster-Nr."
            ),
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="datum_wirksam",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 1, 5, 9, 35, 14, 15166, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="neuer_lik_index",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="neuer_referenzzinssatz",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="pdf_datei",
            field=models.FileField(
                blank=True, null=True, upload_to="mietzinsanpassungen/"
            ),
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="vertrag",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.mietvertrag",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.get_smart_upload_path
            ),
        ),
        migrations.AddField(
            model_name="schluesselausgabe",
            name="bemerkung",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="schluesselausgabe",
            name="handwerker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.handwerker",
                verbose_name="Empfänger (Handwerker)",
            ),
        ),
        migrations.AddField(
            model_name="unterhalt",
            name="beleg",
            field=models.FileField(
                blank=True, null=True, upload_to=core.models.get_smart_upload_path
            ),
        ),
        migrations.AddField(
            model_name="zaehlerstand",
            name="ableser",
            field=models.CharField(default="Verwaltung", max_length=100),
        ),
        migrations.AlterField(
            model_name="abrechnungsperiode",
            name="bezeichnung",
            field=models.CharField(max_length=100, verbose_name="Titel"),
        ),
        migrations.AlterField(
            model_name="anlage",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("heizung", "Heizung"),
                    ("dach", "Dach"),
                    ("fassade", "Fassade"),
                    ("lift", "Lift"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="anlage",
            name="nutzungsdauer",
            field=models.IntegerField(default=20, verbose_name="Nutzungsdauer (Jahre)"),
        ),
        migrations.AlterField(
            model_name="anlage",
            name="wiederbeschaffungswert",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dokument",
            name="einheit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.einheit",
            ),
        ),
        migrations.AlterField(
            model_name="dokument",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("vertrag", "Vertrag"),
                    ("protokoll", "Protokoll"),
                    ("korrespondenz", "Korrespondenz"),
                    ("sonstiges", "Sonstiges"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="ewid",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="EWID"
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="nebenkosten_aktuell",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=6, verbose_name="Nebenkosten"
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="nettomiete_aktuell",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, verbose_name="Nettomiete"
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="nk_abrechnungsart",
            field=models.CharField(
                choices=[("akonto", "Akonto"), ("pauschal", "Pauschal")],
                default="pauschal",
                max_length=20,
                verbose_name="NK-Art",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="typ",
            field=models.CharField(
                choices=[
                    ("whg", "Wohnung"),
                    ("gew", "Gewerbe"),
                    ("pp", "Parkplatz"),
                    ("bas", "Bastelraum"),
                ],
                default="whg",
                max_length=10,
                verbose_name="Typ",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="wertquote",
            field=models.IntegerField(default=0, verbose_name="Wertquote (‰)"),
        ),
        migrations.AlterField(
            model_name="einheitbild",
            name="bild",
            field=models.ImageField(upload_to=core.models.get_smart_upload_path),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="marke",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="modell",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="typ",
            field=models.CharField(
                help_text="z.B. Waschmaschine, Geschirrspüler",
                max_length=50,
                verbose_name="Gerätetyp",
            ),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="gewerk",
            field=models.CharField(
                help_text="z.B. Sanitär, Elektriker", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="telefon",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="egid",
            field=models.CharField(
                blank=True,
                help_text="Eidg. Gebäude-ID für Import",
                max_length=20,
                null=True,
                verbose_name="EGID (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="iban",
            field=models.CharField(
                blank=True, max_length=34, verbose_name="IBAN (Miete/NK)"
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="versicherungswert",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Versicherungswert (CHF)",
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="anrede",
            field=models.CharField(default="Herr", max_length=20),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="telefon",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="basis_lik_punkte",
            field=models.DecimalField(decimal_places=1, default=107.1, max_digits=6),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="basis_referenzzinssatz",
            field=models.DecimalField(decimal_places=2, default=1.75, max_digits=4),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="nebenkosten",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="netto_mietzins",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="betrag",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("heizung", "Heizung"),
                    ("wasser", "Wasser"),
                    ("hauswart", "Hauswart"),
                    ("strom", "Allgemeinstrom"),
                    ("admin", "Verwaltung"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="text",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="verteilschluessel",
            field=models.CharField(
                choices=[("m2", "Nach Fläche"), ("parteien", "Nach Parteien")],
                default="m2",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu"),
                    ("beauftragt", "Beauftragt"),
                    ("erledigt", "Erledigt"),
                ],
                default="neu",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="schluesselausgabe",
            name="mieter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.mieter",
                verbose_name="Empfänger (Mieter)",
            ),
        ),
        migrations.AlterField(
            model_name="schluesselausgabe",
            name="schluessel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ausgaben",
                to="core.schluessel",
            ),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="art",
            field=models.CharField(
                choices=[
                    ("reparatur", "Reparatur"),
                    ("renovation", "Renovation"),
                    ("investition", "Investition"),
                ],
                default="reparatur",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="kosten",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="liegenschaft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.liegenschaft"
            ),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="typ",
            field=models.CharField(
                choices=[
                    ("strom", "Strom"),
                    ("wasser", "Wasser"),
                    ("heizung", "Heizung"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="zaehler_nummer",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="zaehlerstand",
            name="wert",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
