# Generated by Django 5.2.9 on 2026-01-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_abrechnungsperiode_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mandant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firma_oder_name",
                    models.CharField(max_length=100, verbose_name="Name / Firma"),
                ),
                (
                    "ort",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
            ],
            options={
                "verbose_name": "Mandant",
                "verbose_name_plural": "Mandanten",
            },
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="mandant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liegenschaften",
                to="core.mandant",
            ),
        ),
    ]
