# Generated by Django 5.2.9 on 2026-01-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_mandant_liegenschaft_mandant"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="lik_punkte",
            field=models.DecimalField(
                decimal_places=1,
                default=107.1,
                help_text="Indexstand",
                max_digits=6,
                verbose_name="Basis LIK",
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="ref_zinssatz",
            field=models.DecimalField(
                decimal_places=2,
                default=1.75,
                help_text="Aktueller Referenzzinssatz für diese Einheit",
                max_digits=4,
                verbose_name="Basis Ref.Zins",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="nebenkosten_aktuell",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                verbose_name="Soll-Nebenkosten",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="nettomiete_aktuell",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Soll-Miete (Netto)",
            ),
        ),
    ]
