# Generated by Django 5.2.9 on 2026-01-06 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_einheit_lik_punkte_einheit_ref_zinssatz_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leerstand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beginn", models.DateField(verbose_name="Beginn (ab)")),
                (
                    "ende",
                    models.DateField(blank=True, null=True, verbose_name="Ende (bis)"),
                ),
                (
                    "grund",
                    models.CharField(
                        choices=[
                            ("mietersuche", "Mietersuche"),
                            ("sanierung", "Sanierung / Umbau"),
                            ("eigenbedarf", "Eigenbedarf / Reserviert"),
                            ("verkauf", "Verkaufsvorbereitung"),
                            ("kuendigung", "Gekündigt (Nachmietersuche)"),
                        ],
                        default="mietersuche",
                        max_length=50,
                        verbose_name="Grund",
                    ),
                ),
                ("bemerkung", models.TextField(blank=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leerstaende",
                        to="core.einheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leerstand",
                "verbose_name_plural": "Leerstände",
            },
        ),
    ]
