# Generated by Django 5.2.9 on 2026-01-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_leerstand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leerstand",
            options={
                "ordering": ["-beginn"],
                "verbose_name": "Leerstand",
                "verbose_name_plural": "Leerstände",
            },
        ),
        migrations.AlterModelOptions(
            name="mietvertrag",
            options={
                "ordering": ["-beginn"],
                "verbose_name": "Mietvertrag",
                "verbose_name_plural": "Mietverträge",
            },
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="pdf_datei",
            field=models.FileField(blank=True, null=True, upload_to="vertraege_pdfs/"),
        ),
    ]
