# Generated by Django 5.2.9 on 2026-01-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_leerstand_options_alter_mietvertrag_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("links", "links"),
                    ("rechts", "rechts"),
                    ("mitte", "mitte"),
                    ("hinten", "hinten"),
                    ("vorne", "vorne"),
                    ("oben", "oben"),
                    ("unten", "unten"),
                ],
                max_length=20,
                verbose_name="Position",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="bezeichnung",
            field=models.CharField(max_length=50, verbose_name="Objektbezeichnung"),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="zimmer",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="Anz. Zimmer",
            ),
        ),
    ]
