# Generated by Django 5.2.9 on 2026-01-08 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_einheit_position_alter_einheit_bezeichnung_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokument",
            name="bezeichnung",
            field=models.CharField(default="Dokument", max_length=200),
        ),
        migrations.AddField(
            model_name="dokument",
            name="mandant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.mandant",
            ),
        ),
        migrations.AddField(
            model_name="dokument",
            name="vertrag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dokumente",
                to="core.mietvertrag",
            ),
        ),
        migrations.AddField(
            model_name="mandant",
            name="unterschrift_bild",
            field=models.ImageField(blank=True, null=True, upload_to="unterschriften/"),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="jotform_submission_id",
            field=models.CharField(
                blank=True,
                help_text="DocuSeal Submission ID",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="sign_status",
            field=models.CharField(
                choices=[
                    ("offen", "Offen"),
                    ("gesendet", "Versendet (DocuSeal)"),
                    ("unterzeichnet", "Unterzeichnet"),
                ],
                default="offen",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dokument",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("vertrag", "Vertrag"),
                    ("Mietvertrag", "Mietvertrag (DocuSeal)"),
                    ("protokoll", "Protokoll"),
                    ("korrespondenz", "Korrespondenz"),
                    ("sonstiges", "Sonstiges"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="dokument",
            name="titel",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
