# Generated by Django 5.2.9 on 2026-01-08 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_dokument_bezeichnung_dokument_mandant_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mieter",
            options={"verbose_name": "Mieter", "verbose_name_plural": "Mieter"},
        ),
        migrations.AlterModelOptions(
            name="schluessel",
            options={},
        ),
        migrations.AlterModelOptions(
            name="schluesselausgabe",
            options={},
        ),
        migrations.RemoveField(
            model_name="zaehlerstand",
            name="ableser",
        ),
        migrations.AddField(
            model_name="mandant",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bankname"),
        ),
        migrations.AddField(
            model_name="mieter",
            name="geburtsdatum",
            field=models.DateField(blank=True, null=True, verbose_name="Geburtsdatum"),
        ),
        migrations.AddField(
            model_name="mieter",
            name="heimatort",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Heimatort / Nationalität"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="ort",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Ort (Aktuell)"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="partner_name",
            field=models.CharField(
                blank=True,
                help_text="Vorname & Nachname der zweiten Person",
                max_length=200,
                verbose_name="Ehepartner / Solidarhafter",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="plz",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="PLZ (Aktuell)"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="strasse",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Strasse (Aktuell)"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="zivilstand",
            field=models.CharField(
                choices=[
                    ("ledig", "ledig"),
                    ("verheiratet", "verheiratet"),
                    ("geschieden", "geschieden"),
                    ("verwitwet", "verwitwet"),
                    ("partnerschaft", "eingetragene Partnerschaft"),
                ],
                default="ledig",
                max_length=20,
                verbose_name="Zivilstand",
            ),
        ),
        migrations.AlterField(
            model_name="abrechnungsperiode",
            name="ende_datum",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="abrechnungsperiode",
            name="start_datum",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="anlage",
            name="nutzungsdauer",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="dokument",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("vertrag", "Vertrag"),
                    ("Mietvertrag", "Mietvertrag"),
                    ("protokoll", "Protokoll"),
                    ("korrespondenz", "Korrespondenz"),
                    ("sonstiges", "Sonstiges"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="lik_punkte",
            field=models.DecimalField(
                decimal_places=1, default=107.1, max_digits=6, verbose_name="Basis LIK"
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="ref_zinssatz",
            field=models.DecimalField(
                decimal_places=2,
                default=1.75,
                max_digits=4,
                verbose_name="Basis Ref.Zins",
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="typ",
            field=models.CharField(max_length=50, verbose_name="Gerätetyp"),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="gewerk",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="leerstand",
            name="beginn",
            field=models.DateField(verbose_name="Beginn"),
        ),
        migrations.AlterField(
            model_name="leerstand",
            name="ende",
            field=models.DateField(blank=True, null=True, verbose_name="Ende"),
        ),
        migrations.AlterField(
            model_name="leerstand",
            name="grund",
            field=models.CharField(
                choices=[
                    ("mietersuche", "Mietersuche"),
                    ("sanierung", "Sanierung"),
                    ("eigenbedarf", "Eigenbedarf"),
                    ("verkauf", "Verkauf"),
                    ("kuendigung", "Gekündigt"),
                ],
                default="mietersuche",
                max_length=50,
                verbose_name="Grund",
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="egid",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="EGID"
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="versicherungswert",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Versicherungswert",
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="anrede",
            field=models.CharField(
                choices=[("Herr", "Herr"), ("Frau", "Frau"), ("Familie", "Familie")],
                default="Herr",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="jotform_submission_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="verteilschluessel",
            field=models.CharField(default="m2", max_length=50),
        ),
        migrations.AlterField(
            model_name="schluessel",
            name="funktion",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="schluessel",
            name="schluessel_nummer",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="schluesselausgabe",
            name="handwerker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.handwerker",
            ),
        ),
        migrations.AlterField(
            model_name="schluesselausgabe",
            name="mieter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.mieter",
            ),
        ),
    ]
