# Generated by Django 5.2.9 on 2026-01-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_mieter_options_alter_schluessel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liegenschaft",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="z.B. Zürcher Kantonalbank",
                max_length=100,
                verbose_name="Bankname",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="verteilschluessel_text",
            field=models.CharField(
                default="nach Wohnfläche (m2)",
                help_text="Erscheint im Mietvertrag bei den Nebenkosten",
                max_length=200,
                verbose_name="Verteilschlüssel (Text)",
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="iban",
            field=models.CharField(
                blank=True,
                help_text="CH...",
                max_length=34,
                verbose_name="IBAN (Miete/NK)",
            ),
        ),
        migrations.AlterField(
            model_name="mandant",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Bankname (Mandant)"
            ),
        ),
        migrations.AlterField(
            model_name="mandant",
            name="unterschrift_bild",
            field=models.ImageField(
                blank=True,
                help_text="Scan der Unterschrift (transparentes PNG empfohlen) für Verträge",
                null=True,
                upload_to="unterschriften/",
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="jotform_submission_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="DocuSeal Submission ID",
            ),
        ),
    ]
