# Generated by Django 5.2.9 on 2026-01-12 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_liegenschaft_bank_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verwaltung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firma", models.CharField(max_length=100, verbose_name="Firmenname")),
                (
                    "strasse",
                    models.CharField(max_length=100, verbose_name="Strasse & Nr."),
                ),
                ("plz", models.CharField(max_length=10, verbose_name="PLZ")),
                ("ort", models.CharField(max_length=100, verbose_name="Ort")),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=30, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-Mail"
                    ),
                ),
                ("webseite", models.URLField(blank=True, verbose_name="Webseite")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
            ],
            options={
                "verbose_name": "Meine Verwaltung",
                "verbose_name_plural": "Meine Verwaltung",
            },
        ),
        migrations.RemoveField(
            model_name="einheitbild",
            name="einheit",
        ),
        migrations.AlterModelOptions(
            name="leerstand",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mandant",
            options={
                "verbose_name": "Mandant (Eigentümer)",
                "verbose_name_plural": "Mandanten (Eigentümer)",
            },
        ),
        migrations.AddField(
            model_name="mandant",
            name="plz",
            field=models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
        ),
        migrations.AddField(
            model_name="mandant",
            name="strasse",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Strasse (Eigentümer)"
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="z.B. ZKB",
                max_length=100,
                verbose_name="Bankname (Mietkonto)",
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="verteilschluessel_text",
            field=models.CharField(
                default="nach Wohnfläche (m2)",
                max_length=200,
                verbose_name="Verteilschlüssel (Text)",
            ),
        ),
        migrations.AlterField(
            model_name="mandant",
            name="firma_oder_name",
            field=models.CharField(
                max_length=100, verbose_name="Name / Firma (Eigentümer)"
            ),
        ),
        migrations.AlterField(
            model_name="mandant",
            name="unterschrift_bild",
            field=models.ImageField(
                blank=True,
                help_text="Scan der Unterschrift",
                null=True,
                upload_to="unterschriften/",
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="heimatort",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Heimatort"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="partner_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Partner / Solidarhafter"
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="jotform_submission_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="DocuSeal ID"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="verwaltung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liegenschaften",
                to="core.verwaltung",
                verbose_name="Zuständige Verwaltung",
            ),
        ),
        migrations.DeleteModel(
            name="Anlage",
        ),
        migrations.DeleteModel(
            name="EinheitBild",
        ),
    ]
