# Generated by Django 5.2.9 on 2026-01-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_verwaltung_remove_einheitbild_einheit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abrechnungsperiode",
            options={
                "verbose_name": "Abrechnungsperiode",
                "verbose_name_plural": "Abrechnungsperioden",
            },
        ),
        migrations.AlterModelOptions(
            name="dokument",
            options={"verbose_name": "Dokument", "verbose_name_plural": "Dokumente"},
        ),
        migrations.AlterModelOptions(
            name="geraet",
            options={"verbose_name": "Gerät", "verbose_name_plural": "Geräte"},
        ),
        migrations.AlterModelOptions(
            name="handwerker",
            options={"verbose_name": "Handwerker", "verbose_name_plural": "Handwerker"},
        ),
        migrations.AlterModelOptions(
            name="leerstand",
            options={"verbose_name": "Leerstand", "verbose_name_plural": "Leerstände"},
        ),
        migrations.AlterModelOptions(
            name="mietzinsanpassung",
            options={
                "verbose_name": "Mietzinsanpassung",
                "verbose_name_plural": "Mietzinsanpassungen",
            },
        ),
        migrations.AlterModelOptions(
            name="nebenkostenbeleg",
            options={
                "verbose_name": "Nebenkostenbeleg",
                "verbose_name_plural": "Nebenkostenbelege",
            },
        ),
        migrations.AlterModelOptions(
            name="schadenmeldung",
            options={
                "ordering": ["-erstellt_am"],
                "verbose_name": "Schadenmeldung",
                "verbose_name_plural": "Schadenmeldungen",
            },
        ),
        migrations.AlterModelOptions(
            name="schluessel",
            options={"verbose_name": "Schlüssel", "verbose_name_plural": "Schlüssel"},
        ),
        migrations.AlterModelOptions(
            name="schluesselausgabe",
            options={
                "verbose_name": "Schlüsselausgabe",
                "verbose_name_plural": "Schlüsselausgaben",
            },
        ),
        migrations.AlterModelOptions(
            name="unterhalt",
            options={"verbose_name": "Unterhalt", "verbose_name_plural": "Unterhalt"},
        ),
        migrations.AlterModelOptions(
            name="zaehler",
            options={"verbose_name": "Zähler", "verbose_name_plural": "Zähler"},
        ),
        migrations.AlterModelOptions(
            name="zaehlerstand",
            options={
                "verbose_name": "Zählerstand",
                "verbose_name_plural": "Zählerstände",
            },
        ),
        migrations.RemoveField(
            model_name="schadenmeldung",
            name="betreff",
        ),
        migrations.RemoveField(
            model_name="schadenmeldung",
            name="einheit",
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="betroffene_einheit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schaeden",
                to="core.einheit",
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="handwerker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auftraege",
                to="core.handwerker",
                verbose_name="Beauftragter Handwerker",
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="mieter_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Mieter E-Mail (Kontakt)"
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="mieter_telefon",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Mieter Telefon (Kontakt)"
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="prioritaet",
            field=models.CharField(
                choices=[
                    ("niedrig", "Niedrig"),
                    ("mittel", "Mittel"),
                    ("hoch", "Hoch"),
                ],
                default="mittel",
                max_length=20,
                verbose_name="Priorität",
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="titel",
            field=models.CharField(
                default="Schaden", max_length=200, verbose_name="Titel / Schaden"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="zutritt",
            field=models.CharField(
                choices=[
                    ("telefon", "Termin via Telefon"),
                    ("passpartout", "Passpartout (Schlüssel vorhanden)"),
                ],
                default="telefon",
                max_length=20,
                verbose_name="Zutritt / Termin",
            ),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="gewerk",
            field=models.CharField(
                help_text="z.B. Sanitär, Elektriker, Maler", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="beschreibung",
            field=models.TextField(verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="gemeldet_von",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gemeldete_schaeden",
                to="core.mieter",
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="liegenschaft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schaeden",
                to="core.liegenschaft",
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu"),
                    ("in_bearbeitung", "In Bearbeitung"),
                    ("beauftragt", "Beauftragt"),
                    ("erledigt", "Erledigt"),
                ],
                default="neu",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
