# Generated by Django 5.2.9 on 2026-01-15 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_abrechnungsperiode_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schadenmeldung",
            options={
                "ordering": ["-erstellt_am"],
                "verbose_name": "Ticket / Schaden",
                "verbose_name_plural": "Tickets / Schäden",
            },
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="aktualisiert_am",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu"),
                    ("in_bearbeitung", "In Bearbeitung"),
                    ("warte_auf_mieter", "Warte auf Mieter"),
                    ("beauftragt", "Handwerker beauftragt"),
                    ("erledigt", "Erledigt"),
                ],
                default="neu",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="TicketNachricht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("absender_name", models.CharField(max_length=100)),
                (
                    "is_intern",
                    models.BooleanField(
                        default=False,
                        help_text="Interne Notiz (Mieter sieht das nicht)",
                    ),
                ),
                (
                    "is_von_verwaltung",
                    models.BooleanField(
                        default=False,
                        help_text="True = Von Verwaltung, False = Von Mieter",
                    ),
                ),
                ("nachricht", models.TextField()),
                (
                    "datei",
                    models.FileField(blank=True, null=True, upload_to="ticket_anhang/"),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nachrichten",
                        to="core.schadenmeldung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Nachricht",
                "verbose_name_plural": "Ticket Nachrichten",
                "ordering": ["erstellt_am"],
            },
        ),
    ]
