# Generated by Django 5.2.9 on 2026-01-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_schadenmeldung_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schadenmeldung",
            name="uuid",
        ),
    ]
