# Generated by Django 5.2.9 on 2026-01-15 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_remove_schadenmeldung_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="schadenmeldung",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
