# Generated by Django 5.2.9 on 2026-01-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_schadenmeldung_uid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schadenmeldung",
            old_name="uid",
            new_name="uuid",
        ),
    ]
