# Generated by Django 5.2.9 on 2026-01-15 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_rename_uid_schadenmeldung_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schadenmeldung",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
