# Generated by Django 5.2.9 on 2026-01-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_alter_schadenmeldung_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="mieter",
            name="ahv_nummer",
            field=models.CharField(
                blank=True,
                help_text="756.xxxx.xxxx.xx",
                max_length=20,
                verbose_name="AHV-Nummer",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="nationalitaet",
            field=models.CharField(
                blank=True,
                default="Schweiz",
                max_length=50,
                verbose_name="Nationalität",
            ),
        ),
    ]
