# Generated by Django 5.2.9 on 2026-01-28 10:26

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_mieter_ahv_nummer_mieter_nationalitaet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mietzinsanpassung",
            old_name="datum_wirksam",
            new_name="wirksam_ab",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="datum_erstellt",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="neue_miete",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="pdf_datei",
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="alter_lik_index",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="alter_netto_mietzins",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="alter_referenzzinssatz",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="begruendung",
            field=models.TextField(
                default="Anpassung an Referenzzinssatz und Teuerung"
            ),
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="erhoehung_prozent_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="erstellt_am",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="neuer_netto_mietzins",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verwaltung",
            name="aktueller_lik_punkte",
            field=models.DecimalField(
                decimal_places=1,
                default=107.1,
                help_text="Landesindex der Konsumentenpreise (Punkte) (für NEUE Verträge)",
                max_digits=6,
                verbose_name="Aktueller LIK",
            ),
        ),
        migrations.AddField(
            model_name="verwaltung",
            name="aktueller_referenzzinssatz",
            field=models.DecimalField(
                decimal_places=2,
                default=1.75,
                help_text="Offizieller Satz vom BWO (für NEUE Verträge)",
                max_digits=4,
                verbose_name="Aktueller Ref.Zins",
            ),
        ),
        migrations.AddField(
            model_name="verwaltung",
            name="letztes_update_marktdaten",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="lik_punkte",
            field=models.DecimalField(
                decimal_places=1,
                default=core.models.get_current_lik,
                max_digits=6,
                verbose_name="Basis LIK",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="ref_zinssatz",
            field=models.DecimalField(
                decimal_places=2,
                default=core.models.get_current_ref_zins,
                max_digits=4,
                verbose_name="Basis Ref.Zins",
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="basis_lik_punkte",
            field=models.DecimalField(
                decimal_places=1,
                default=core.models.get_current_lik,
                help_text="LIK Punkte bei Vertragsabschluss (wird fixiert)",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="basis_referenzzinssatz",
            field=models.DecimalField(
                decimal_places=2,
                default=core.models.get_current_ref_zins,
                help_text="Zinssatz bei Vertragsabschluss (wird fixiert)",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="mietzinsanpassung",
            name="neuer_lik_index",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="mietzinsanpassung",
            name="vertrag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anpassungen",
                to="core.mietvertrag",
            ),
        ),
    ]
