# Generated by Django 5.2.9 on 2026-02-04 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_rename_datum_wirksam_mietzinsanpassung_wirksam_ab_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schadenmeldung",
            name="handwerker",
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="beauftragter_handwerker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auftraege",
                to="core.handwerker",
                verbose_name="Handwerker beauftragen",
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="email_melder",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-Mail Melder"
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="tel_melder",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telefon Melder"
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="mieter_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Mieter E-Mail (Legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="mieter_telefon",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Mieter Telefon (Legacy)"
            ),
        ),
    ]
