# Generated by Django 5.2.9 on 2026-02-04 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_remove_schadenmeldung_handwerker_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketnachricht",
            options={
                "ordering": ["-erstellt_am"],
                "verbose_name": "Historie / Nachricht",
                "verbose_name_plural": "Historie / Nachrichten",
            },
        ),
        migrations.RemoveField(
            model_name="schadenmeldung",
            name="beauftragter_handwerker",
        ),
        migrations.AddField(
            model_name="ticketnachricht",
            name="typ",
            field=models.CharField(
                choices=[
                    ("mail_antwort", "📩 Antwort per Mail"),
                    ("notiz_intern", "🔒 Interne Notiz"),
                    ("system", "⚙️ System-Log"),
                    ("chat", "💬 Nachricht"),
                ],
                default="chat",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu"),
                    ("in_bearbeitung", "In Bearbeitung"),
                    ("warte_auf_mieter", "Warte auf Mieter"),
                    ("erledigt", "Erledigt"),
                ],
                default="neu",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="is_intern",
            field=models.BooleanField(
                default=False, help_text="Interne Notiz (Legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="is_von_verwaltung",
            field=models.BooleanField(default=False, help_text="Legacy"),
        ),
        migrations.CreateModel(
            name="HandwerkerAuftrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen / Beauftragt"),
                            ("terminiert", "Termin vereinbart"),
                            ("erledigt", "Arbeiten erledigt"),
                            ("storniert", "Storniert"),
                        ],
                        default="offen",
                        max_length=20,
                    ),
                ),
                ("beauftragt_am", models.DateTimeField(auto_now_add=True)),
                ("abgeschlossen_am", models.DateTimeField(blank=True, null=True)),
                (
                    "bemerkung",
                    models.TextField(
                        blank=True, help_text="Interner Kommentar zum Auftrag"
                    ),
                ),
                (
                    "handwerker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auftraege",
                        to="core.handwerker",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handwerker_auftraege",
                        to="core.schadenmeldung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handwerker-Auftrag",
                "verbose_name_plural": "Handwerker-Aufträge",
            },
        ),
    ]
