# Generated by Django 5.2.9 on 2026-02-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_ticketnachricht_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schadenmeldung",
            name="gelesen",
            field=models.BooleanField(
                default=False, help_text="False = Neu/Ungelesen für Admin"
            ),
        ),
        migrations.AddField(
            model_name="ticketnachricht",
            name="gelesen",
            field=models.BooleanField(default=False),
        ),
    ]
