# Generated by Django 5.2.9 on 2026-02-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_schadenmeldung_gelesen_ticketnachricht_gelesen"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketnachricht",
            name="cc_email",
            field=models.CharField(
                blank=True,
                help_text="E-Mail für Kopie (z.B. Handwerker)",
                max_length=200,
                verbose_name="CC (Optional)",
            ),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="typ",
            field=models.CharField(
                choices=[
                    ("mail_antwort", "📩 Antwort per Mail (Eingang)"),
                    ("antwort_senden", "📤 Antwort an Melder (per E-Mail)"),
                    ("handwerker_mail", "🔨 E-Mail an Handwerker"),
                    ("notiz_intern", "🔒 Interne Notiz"),
                    ("system", "⚙️ System-Log"),
                    ("chat", "💬 Nachricht"),
                ],
                default="chat",
                max_length=20,
            ),
        ),
    ]
