# Generated by Django 5.2.9 on 2026-02-06 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_ticketnachricht_cc_email_alter_ticketnachricht_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketnachricht",
            name="empfaenger_handwerker",
            field=models.ForeignKey(
                blank=True,
                help_text="Nur nötig bei 'E-Mail an Handwerker'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.handwerker",
                verbose_name="Empfänger (Handwerker)",
            ),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="cc_email",
            field=models.CharField(
                blank=True,
                help_text="E-Mail für Kopie",
                max_length=200,
                verbose_name="CC (Optional)",
            ),
        ),
    ]
