# Generated by Django 5.2.9 on 2026-02-17 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_ticketnachricht_empfaenger_handwerker_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nebenkostenbeleg",
            options={
                "ordering": ["datum"],
                "verbose_name": "Nebenkostenbeleg",
                "verbose_name_plural": "Nebenkostenbelege",
            },
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="beleg_scan",
            field=models.FileField(
                blank=True, null=True, upload_to="nebenkosten_belege/"
            ),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="datum",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("heizung", "Heizung & Warmwasser"),
                    ("wasser", "Wasser / Abwasser"),
                    ("hauswart", "Hauswartung & Reinigung"),
                    ("garten", "Gartenpflege"),
                    ("strom", "Allgemeinstrom"),
                    ("lift", "Serviceabo Lift"),
                    ("verwaltung", "Verwaltungshonorar"),
                    ("tv", "TV / Kabelgebühren"),
                    ("kehricht", "Kehricht / Entsorgung"),
                    ("diverse", "Diverse Betriebskosten"),
                ],
                default="diverse",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="text",
            field=models.CharField(
                help_text="z.B. Heizöl Lieferung Müller AG",
                max_length=255,
                verbose_name="Beschreibung / Lieferant",
            ),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="verteilschluessel",
            field=models.CharField(
                choices=[
                    ("m2", "Nach Fläche (m²)"),
                    ("einheit", "Pro Wohnung (Pauschal/Einheit)"),
                    ("m3", "Nach Kubatur (m³)"),
                ],
                default="m2",
                max_length=20,
            ),
        ),
    ]
