# Generated by Django 5.2.9 on 2026-02-17 11:35

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_nebenkostenbeleg_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schadenmeldung",
            options={
                "verbose_name": "Ticket / Schaden",
                "verbose_name_plural": "Tickets / Schäden",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketnachricht",
            options={
                "ordering": ["-erstellt_am"],
                "verbose_name": "Historie / Nachricht",
            },
        ),
        migrations.RemoveField(
            model_name="schadenmeldung",
            name="aktualisiert_am",
        ),
        migrations.AlterField(
            model_name="einheit",
            name="nettomiete_aktuell",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, verbose_name="Soll-Miete"
            ),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="gewerk",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="handwerkerauftrag",
            name="bemerkung",
            field=models.TextField(blank=True, help_text="Interner Kommentar"),
        ),
        migrations.AlterField(
            model_name="handwerkerauftrag",
            name="status",
            field=models.CharField(default="offen", max_length=20),
        ),
        migrations.AlterField(
            model_name="leerstand",
            name="grund",
            field=models.CharField(
                default="mietersuche", max_length=50, verbose_name="Grund"
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bankname"),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="iban",
            field=models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="verteilschluessel_text",
            field=models.CharField(
                default="nach Wohnfläche (m2)",
                max_length=200,
                verbose_name="Verteilschlüssel",
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="verwaltung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liegenschaften",
                to="core.verwaltung",
            ),
        ),
        migrations.AlterField(
            model_name="mandant",
            name="unterschrift_bild",
            field=models.ImageField(blank=True, null=True, upload_to="unterschriften/"),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="ahv_nummer",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="geburtsdatum",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="heimatort",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="nationalitaet",
            field=models.CharField(blank=True, default="Schweiz", max_length=50),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="ort",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="partner_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="plz",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="strasse",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="zivilstand",
            field=models.CharField(default="ledig", max_length=20),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="basis_lik_punkte",
            field=models.DecimalField(
                decimal_places=1, default=core.models.get_current_lik, max_digits=6
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="basis_referenzzinssatz",
            field=models.DecimalField(
                decimal_places=2, default=core.models.get_current_ref_zins, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="sign_status",
            field=models.CharField(
                choices=[
                    ("offen", "Offen"),
                    ("gesendet", "Versendet"),
                    ("unterzeichnet", "Unterzeichnet"),
                ],
                default="offen",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="betrag",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="datum",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="text",
            field=models.CharField(
                blank=True,
                help_text="Wird automatisch aus PDF erkannt wenn leer",
                max_length=255,
                verbose_name="Beschreibung / Lieferant",
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="beschreibung",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="email_melder",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="gelesen",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="mieter_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="mieter_telefon",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="prioritaet",
            field=models.CharField(default="mittel", max_length=20),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="status",
            field=models.CharField(default="neu", max_length=20),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="tel_melder",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="titel",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="zutritt",
            field=models.CharField(default="telefon", max_length=20),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="cc_email",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="empfaenger_handwerker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.handwerker",
            ),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="is_intern",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="is_von_verwaltung",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="typ",
            field=models.CharField(default="chat", max_length=20),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="art",
            field=models.CharField(default="reparatur", max_length=50),
        ),
        migrations.AlterField(
            model_name="verwaltung",
            name="aktueller_lik_punkte",
            field=models.DecimalField(
                decimal_places=1,
                default=107.1,
                max_digits=6,
                verbose_name="Aktueller LIK",
            ),
        ),
        migrations.AlterField(
            model_name="verwaltung",
            name="aktueller_referenzzinssatz",
            field=models.DecimalField(
                decimal_places=2,
                default=1.75,
                max_digits=4,
                verbose_name="Aktueller Ref.Zins",
            ),
        ),
    ]
