# Generated by Django 5.2.9 on 2026-02-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_schadenmeldung_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NebenkostenLernRegel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suchwort",
                    models.CharField(
                        help_text="z.B. 'müller sanitär'",
                        max_length=100,
                        unique=True,
                        verbose_name="Schlüsselwort",
                    ),
                ),
                (
                    "kategorie_zuweisung",
                    models.CharField(max_length=50, verbose_name="Wird zugewiesen zu"),
                ),
                (
                    "text_vorschlag",
                    models.CharField(
                        max_length=200, verbose_name="Standard-Beschreibung"
                    ),
                ),
                (
                    "treffer_quote",
                    models.IntegerField(
                        default=0, verbose_name="Erfolgreich angewendet"
                    ),
                ),
            ],
            options={
                "verbose_name": "KI Lern-Regel",
                "verbose_name_plural": "KI Lern-Regeln",
            },
        ),
        migrations.AlterModelOptions(
            name="handwerkerauftrag",
            options={"verbose_name": "Handwerker-Auftrag"},
        ),
        migrations.AlterModelOptions(
            name="leerstand",
            options={"verbose_name": "Leerstand"},
        ),
        migrations.AlterModelOptions(
            name="mietvertrag",
            options={
                "verbose_name": "Mietvertrag",
                "verbose_name_plural": "Mietverträge",
            },
        ),
        migrations.AlterModelOptions(
            name="mietzinsanpassung",
            options={"verbose_name": "Mietzinsanpassung"},
        ),
        migrations.AlterModelOptions(
            name="nebenkostenbeleg",
            options={"ordering": ["datum"], "verbose_name": "Nebenkostenbeleg"},
        ),
        migrations.AlterModelOptions(
            name="schadenmeldung",
            options={
                "ordering": ["-erstellt_am"],
                "verbose_name": "Ticket / Schaden",
                "verbose_name_plural": "Tickets / Schäden",
            },
        ),
        migrations.AlterModelOptions(
            name="schluessel",
            options={"verbose_name": "Schlüssel"},
        ),
        migrations.AlterModelOptions(
            name="schluesselausgabe",
            options={"verbose_name": "Schlüsselausgabe"},
        ),
        migrations.AlterModelOptions(
            name="unterhalt",
            options={"verbose_name": "Unterhalt"},
        ),
        migrations.AlterModelOptions(
            name="zaehlerstand",
            options={"verbose_name": "Zählerstand"},
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="etage",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="ewid",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="position",
        ),
        migrations.RemoveField(
            model_name="einheit",
            name="wertquote",
        ),
        migrations.RemoveField(
            model_name="handwerker",
            name="kontaktperson",
        ),
        migrations.RemoveField(
            model_name="handwerkerauftrag",
            name="abgeschlossen_am",
        ),
        migrations.RemoveField(
            model_name="liegenschaft",
            name="baujahr",
        ),
        migrations.RemoveField(
            model_name="liegenschaft",
            name="kataster_nummer",
        ),
        migrations.RemoveField(
            model_name="liegenschaft",
            name="versicherungswert",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="ahv_nummer",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="heimatort",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="nationalitaet",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="partner_name",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="zivilstand",
        ),
        migrations.RemoveField(
            model_name="mietvertrag",
            name="jotform_submission_id",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="alter_lik_index",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="alter_netto_mietzins",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="alter_referenzzinssatz",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="begruendung",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="erhoehung_prozent_total",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="erstellt_am",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="neuer_lik_index",
        ),
        migrations.RemoveField(
            model_name="mietzinsanpassung",
            name="neuer_referenzzinssatz",
        ),
        migrations.RemoveField(
            model_name="schluessel",
            name="funktion",
        ),
        migrations.RemoveField(
            model_name="schluesselausgabe",
            name="bemerkung",
        ),
        migrations.RemoveField(
            model_name="unterhalt",
            name="art",
        ),
        migrations.RemoveField(
            model_name="unterhalt",
            name="beschreibung",
        ),
        migrations.RemoveField(
            model_name="verwaltung",
            name="webseite",
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="aktualisiert_am",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dokument",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("vertrag", "Vertrag"),
                    ("protokoll", "Protokoll"),
                    ("korrespondenz", "Korrespondenz"),
                    ("sonstiges", "Sonstiges"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="typ",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="handwerkerauftrag",
            name="bemerkung",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="leerstand",
            name="beginn",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="leerstand",
            name="ende",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leerstand",
            name="grund",
            field=models.CharField(default="mietersuche", max_length=50),
        ),
        migrations.AlterField(
            model_name="mandant",
            name="strasse",
            field=models.CharField(blank=True, max_length=100, verbose_name="Strasse"),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="anrede",
            field=models.CharField(default="Herr", max_length=20),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("heizung", "Heizung & Warmwasser"),
                    ("wasser", "Wasser / Abwasser"),
                    ("hauswart", "Hauswartung & Reinigung"),
                    ("strom", "Allgemeinstrom"),
                    ("lift", "Serviceabo Lift"),
                    ("verwaltung", "Verwaltungshonorar"),
                    ("tv", "TV / Kabelgebühren"),
                    ("kehricht", "Kehricht / Entsorgung"),
                    ("diverse", "Diverse Betriebskosten"),
                ],
                default="diverse",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Beschreibung / Lieferant"
            ),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="verteilschluessel",
            field=models.CharField(
                choices=[("m2", "Nach Fläche (m²)"), ("einheit", "Pro Wohnung")],
                default="m2",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="beschreibung",
            field=models.TextField(verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="email_melder",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-Mail Melder"
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="mieter_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Mieter E-Mail (Legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="mieter_telefon",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Mieter Telefon (Legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="prioritaet",
            field=models.CharField(
                default="mittel", max_length=20, verbose_name="Priorität"
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu"),
                    ("in_bearbeitung", "In Bearbeitung"),
                    ("warte_auf_mieter", "Warte auf Mieter"),
                    ("erledigt", "Erledigt"),
                ],
                default="neu",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="tel_melder",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telefon Melder"
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="titel",
            field=models.CharField(max_length=200, verbose_name="Titel / Schaden"),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="zutritt",
            field=models.CharField(
                choices=[
                    ("telefon", "Termin via Telefon"),
                    ("passpartout", "Passpartout (Schlüssel vorhanden)"),
                ],
                default="telefon",
                max_length=20,
                verbose_name="Zutritt / Termin",
            ),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="cc_email",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="CC (Optional)"
            ),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="typ",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("system", "System"),
                    ("mail_antwort", "Mail Antwort"),
                    ("antwort_senden", "Antwort Senden"),
                    ("handwerker_mail", "Handwerker Mail"),
                ],
                default="chat",
                max_length=20,
            ),
        ),
    ]
