# Generated by Django 5.2.9 on 2026-03-05 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_nebenkostenlernregel_alter_handwerkerauftrag_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buchungskonto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nummer",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Kontonummer"
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(max_length=100, verbose_name="Bezeichnung"),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("aufwand", "Aufwand"),
                            ("ertrag", "Ertrag"),
                            ("bilanz", "Bilanz"),
                        ],
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buchungskonto",
                "verbose_name_plural": "Kontenplan (Buchhaltung)",
                "ordering": ["nummer"],
            },
        ),
        migrations.AlterField(
            model_name="nebenkostenlernregel",
            name="suchwort",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Schlüsselwort"
            ),
        ),
        migrations.CreateModel(
            name="KreditorenRechnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lieferant",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Kreditor / Lieferant"
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Rechnungsdatum",
                    ),
                ),
                (
                    "faellig_am",
                    models.DateField(blank=True, null=True, verbose_name="Fällig am"),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Rechnungsbetrag",
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
                ),
                (
                    "referenz",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Referenznummer / QR-Ref",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen (Unbezahlt)"),
                            ("freigegeben", "Freigegeben zur Zahlung"),
                            ("bezahlt", "Bezahlt"),
                        ],
                        default="offen",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "beleg_scan",
                    models.FileField(
                        blank=True, null=True, upload_to="kreditoren_belege/"
                    ),
                ),
                (
                    "fehlermeldung",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="System-Info"
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "konto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aufwandskonto",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.buchungskonto",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        help_text="Welchem Objekt wird die Rechnung belastet?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kreditoren-Rechnung",
                "verbose_name_plural": "Kreditoren-Rechnungen",
                "ordering": ["-datum"],
            },
        ),
    ]
