# Generated by Django 5.2.9 on 2026-03-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_buchungskonto_alter_nebenkostenlernregel_suchwort_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kreditorenrechnung",
            name="einheit",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Betroffene Einheit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.einheit",
            ),
        ),
    ]
