# Generated by Django 5.2.9 on 2026-03-06 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_kreditorenrechnung_einheit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zahlungseingang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buchungs_monat",
                    models.DateField(
                        help_text="Bitte immer den 1. des Monats wählen (z.B. 01.03.2026)",
                        verbose_name="Für Monat/Jahr",
                    ),
                ),
                (
                    "datum_eingang",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Bezahlt am"
                    ),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Eingezahlter Betrag",
                    ),
                ),
                (
                    "bemerkung",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Bemerkung / Verwendungszweck",
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "konto",
                    models.ForeignKey(
                        help_text="Ertragskonto",
                        limit_choices_to={"typ": "ertrag"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.buchungskonto",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zahlungen",
                        to="core.liegenschaft",
                    ),
                ),
                (
                    "vertrag",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zahlungen",
                        to="core.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zahlungseingang (Miete)",
                "verbose_name_plural": "Zahlungseingänge (Mieten)",
                "ordering": ["-datum_eingang"],
            },
        ),
    ]
