# Generated by Django 5.2.9 on 2026-03-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_zahlungseingang"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jahresabschluss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jahr",
                    models.IntegerField(default=2026, verbose_name="Abrechnungsjahr"),
                ),
                (
                    "notizen",
                    models.TextField(blank=True, verbose_name="Interne Notizen"),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Erfolgsrechnung (GuV)",
                "verbose_name_plural": "Erfolgsrechnungen (GuV)",
                "unique_together": {("liegenschaft", "jahr")},
            },
        ),
    ]
