# Generated by Django 5.2.9 on 2026-03-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_jahresabschluss"),
    ]

    operations = [
        migrations.CreateModel(
            name="MietzinsKontrolle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monat",
                    models.DateField(
                        help_text="Immer den 1. des Monats wählen (z.B. 01.03.2026)",
                        verbose_name="Für Monat/Jahr",
                    ),
                ),
                (
                    "notizen",
                    models.TextField(blank=True, verbose_name="Interne Notizen"),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mietzins-Kontrolle (Scanner)",
                "verbose_name_plural": "Mietzins-Kontrollen (Scanner)",
                "unique_together": {("liegenschaft", "monat")},
            },
        ),
    ]
