# Generated by Django 5.2.9 on 2026-03-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_mietzinskontrolle"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="etage",
            field=models.CharField(blank=True, max_length=50, verbose_name="Etage"),
        ),
        migrations.AddField(
            model_name="einheit",
            name="ewid",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="EWID"
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="wertquote",
            field=models.DecimalField(
                decimal_places=2, default=10.0, max_digits=6, verbose_name="Wertquote"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="baujahr",
            field=models.IntegerField(blank=True, null=True, verbose_name="Baujahr"),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="kataster_nummer",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Kataster-Nr."
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="versicherungswert",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Versicherungswert",
            ),
        ),
    ]
