# Generated by Django 5.2.9 on 2026-09-22
#
# Neues Modell abo.Abonnement — die neue Quelle fuer Stufe und Status
# einer Organisation (PLAN-V7.md D7, Arbeitspaket M8, Etappe E3).
#
# `stufe_von()` in core/funktionen.py liest nun hierher, nicht mehr eine
# Settings-Konstante. Rueckfall: SWISSIMMO_VORGABE_STUFE (derzeit
# 'verwaltung'), damit Systeme ohne Abo weiterlaufen.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0043_remove_organisation_abo_bis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stufe",
                    models.CharField(
                        choices=[
                            ("basis", "Start (Basis)"),
                            ("aufbau", "Team (Aufbau)"),
                            ("verwaltung", "Professional (Verwaltung)"),
                            ("portfolio", "Enterprise (Portfolio)"),
                        ],
                        default="basis",
                        max_length=20,
                        verbose_name="Stufe",
                    ),
                ),
                (
                    "intervall",
                    models.CharField(
                        choices=[
                            ("monatlich", "Monatlich"),
                            ("jaehrlich", "Jährlich"),
                        ],
                        default="monatlich",
                        max_length=10,
                        verbose_name="Abrechnungsintervall",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktiv", "Aktiv"),
                            ("test", "Testphase"),
                            ("ausgelaufen", "Ausgelaufen"),
                        ],
                        default="test",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "testphase_bis",
                    models.DateField(
                        blank=True,
                        help_text="Bis zu diesem Datum laeuft die Testphase. "
                        "Danach wird entweder aktiviert oder ausgelaufen.",
                        null=True,
                        verbose_name="Testphase bis",
                    ),
                ),
                (
                    "anbieter_referenz",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identifikation beim Zahlungsanbieter "
                        "(z.B. Stripe Subscription-ID). Leer = kein "
                        "Anbieter hinterlegt.",
                        max_length=200,
                        verbose_name="Anbieter-Referenz",
                    ),
                ),
                (
                    "gekuendigt_auf",
                    models.DateField(
                        blank=True,
                        help_text="Datum der Kuendigung. Das Abo bleibt bis "
                        "zum Ablauf der bezahlten Periode aktiv, wechselt "
                        "dann auf ausgelaufen.",
                        null=True,
                        verbose_name="Gekuendigt auf",
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "aktualisiert_am",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Aktualisiert am"
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnements",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "ordering": ["-erstellt_am"],
            },
        ),
    ]
