# Generated by Django 5.2.9 on 2026-04-07 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolio", "0001_initial"),
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buchungskonto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nummer",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Kontonummer"
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(max_length=100, verbose_name="Bezeichnung"),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("aufwand", "Aufwand"),
                            ("ertrag", "Ertrag"),
                            ("bilanz", "Bilanz"),
                        ],
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buchungskonto",
                "verbose_name_plural": "Kontenplan (Buchhaltung)",
                "db_table": "core_buchungskonto",
                "ordering": ["nummer"],
            },
        ),
        migrations.CreateModel(
            name="NebenkostenLernRegel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suchwort",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Schlüsselwort"
                    ),
                ),
                (
                    "kategorie_zuweisung",
                    models.CharField(max_length=50, verbose_name="Wird zugewiesen zu"),
                ),
                (
                    "text_vorschlag",
                    models.CharField(
                        max_length=200, verbose_name="Standard-Beschreibung"
                    ),
                ),
                (
                    "treffer_quote",
                    models.IntegerField(
                        default=0, verbose_name="Erfolgreich angewendet"
                    ),
                ),
            ],
            options={
                "verbose_name": "KI Lern-Regel",
                "verbose_name_plural": "KI Lern-Regeln",
                "db_table": "core_nebenkostenlernregel",
            },
        ),
        migrations.CreateModel(
            name="AbrechnungsPeriode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bezeichnung", models.CharField(max_length=100, verbose_name="Titel")),
                ("start_datum", models.DateField()),
                ("ende_datum", models.DateField()),
                ("abgeschlossen", models.BooleanField(default=False)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abrechnungen",
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abrechnungsperiode",
                "verbose_name_plural": "Abrechnungsperioden",
                "db_table": "core_abrechnungsperiode",
            },
        ),
        migrations.CreateModel(
            name="KreditorenRechnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lieferant",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Kreditor / Lieferant"
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Rechnungsdatum",
                    ),
                ),
                (
                    "faellig_am",
                    models.DateField(blank=True, null=True, verbose_name="Fällig am"),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Rechnungsbetrag",
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
                ),
                (
                    "referenz",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Referenznummer / QR-Ref",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen (Unbezahlt)"),
                            ("freigegeben", "Freigegeben zur Zahlung"),
                            ("bezahlt", "Bezahlt"),
                        ],
                        default="offen",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "beleg_scan",
                    models.FileField(
                        blank=True, null=True, upload_to="kreditoren_belege/"
                    ),
                ),
                (
                    "fehlermeldung",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="System-Info"
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.buchungskonto",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kreditoren-Rechnung",
                "verbose_name_plural": "Kreditoren-Rechnungen",
                "db_table": "core_kreditorenrechnung",
                "ordering": ["-datum"],
            },
        ),
        migrations.CreateModel(
            name="NebenkostenBeleg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Beschreibung / Lieferant",
                    ),
                ),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("heizung", "Heizung & Warmwasser"),
                            ("wasser", "Wasser / Abwasser"),
                            ("hauswart", "Hauswartung & Reinigung"),
                            ("strom", "Allgemeinstrom"),
                            ("lift", "Serviceabo Lift"),
                            ("verwaltung", "Verwaltungshonorar"),
                            ("tv", "TV / Kabelgebühren"),
                            ("kehricht", "Kehricht / Entsorgung"),
                            ("diverse", "Diverse Betriebskosten"),
                        ],
                        default="diverse",
                        max_length=50,
                    ),
                ),
                (
                    "verteilschluessel",
                    models.CharField(
                        choices=[
                            ("m2", "Nach Fläche (m²)"),
                            ("einheit", "Pro Wohnung"),
                        ],
                        default="m2",
                        max_length=20,
                    ),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "beleg_scan",
                    models.FileField(
                        blank=True, null=True, upload_to="nebenkosten_belege/"
                    ),
                ),
                (
                    "periode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belege",
                        to="finance.abrechnungsperiode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nebenkostenbeleg",
                "db_table": "core_nebenkostenbeleg",
                "ordering": ["datum"],
            },
        ),
        migrations.CreateModel(
            name="Zahlungseingang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buchungs_monat",
                    models.DateField(
                        help_text="Bitte immer den 1. des Monats wählen",
                        verbose_name="Für Monat/Jahr",
                    ),
                ),
                (
                    "datum_eingang",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Bezahlt am"
                    ),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Eingezahlter Betrag",
                    ),
                ),
                (
                    "bemerkung",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Bemerkung / Verwendungszweck",
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "konto",
                    models.ForeignKey(
                        limit_choices_to={"typ": "ertrag"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.buchungskonto",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zahlungen",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "vertrag",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zahlungen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zahlungseingang (Miete)",
                "verbose_name_plural": "Zahlungseingänge (Mieten)",
                "db_table": "core_zahlungseingang",
                "ordering": ["-datum_eingang"],
            },
        ),
        migrations.CreateModel(
            name="Jahresabschluss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jahr",
                    models.IntegerField(default=2026, verbose_name="Abrechnungsjahr"),
                ),
                (
                    "notizen",
                    models.TextField(blank=True, verbose_name="Interne Notizen"),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Erfolgsrechnung (GuV)",
                "verbose_name_plural": "Erfolgsrechnungen (GuV)",
                "db_table": "core_jahresabschluss",
                "unique_together": {("liegenschaft", "jahr")},
            },
        ),
        migrations.CreateModel(
            name="MietzinsKontrolle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monat",
                    models.DateField(
                        help_text="Immer den 1. des Monats wählen",
                        verbose_name="Für Monat/Jahr",
                    ),
                ),
                (
                    "notizen",
                    models.TextField(blank=True, verbose_name="Interne Notizen"),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mietzins-Kontrolle (Scanner)",
                "verbose_name_plural": "Mietzins-Kontrollen (Scanner)",
                "db_table": "core_mietzinskontrolle",
                "unique_together": {("liegenschaft", "monat")},
            },
        ),
    ]
