# Generated by Django 5.2.9 on 2026-04-22 07:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buchungskonto",
            options={
                "ordering": ["nummer"],
                "verbose_name": "Buchungskonto",
                "verbose_name_plural": "Kontenplan",
            },
        ),
        migrations.AlterModelOptions(
            name="jahresabschluss",
            options={},
        ),
        migrations.AlterModelOptions(
            name="kreditorenrechnung",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mietzinskontrolle",
            options={},
        ),
        migrations.AlterModelOptions(
            name="nebenkostenbeleg",
            options={"verbose_name": "Nebenkostenbeleg"},
        ),
        migrations.AlterModelOptions(
            name="zahlungseingang",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="jahresabschluss",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="mietzinskontrolle",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="kreditorenrechnung",
            name="erstellt_am",
        ),
        migrations.RemoveField(
            model_name="nebenkostenlernregel",
            name="text_vorschlag",
        ),
        migrations.AlterField(
            model_name="jahresabschluss",
            name="jahr",
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name="jahresabschluss",
            name="notizen",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="kreditorenrechnung",
            name="betrag",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kreditorenrechnung",
            name="datum",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kreditorenrechnung",
            name="faellig_am",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kreditorenrechnung",
            name="fehlermeldung",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="kreditorenrechnung",
            name="iban",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="kreditorenrechnung",
            name="lieferant",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="kreditorenrechnung",
            name="referenz",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="kreditorenrechnung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu / Scan"),
                    ("freigegeben", "Freigegeben"),
                    ("bezahlt", "Bezahlt"),
                ],
                default="neu",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mietzinskontrolle",
            name="monat",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="mietzinskontrolle",
            name="notizen",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="verteilschluessel",
            field=models.CharField(
                choices=[("m2", "Nach Fläche (m²)"), ("einheit", "Pro Wohnung")],
                default="m2",
                max_length=20,
                verbose_name="Verteilschlüssel",
            ),
        ),
        migrations.AlterField(
            model_name="nebenkostenlernregel",
            name="suchwort",
            field=models.CharField(
                max_length=100,
                unique=True,
                verbose_name="Schlüsselwort (z.B. Firmenname)",
            ),
        ),
        migrations.AlterField(
            model_name="zahlungseingang",
            name="bemerkung",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="zahlungseingang",
            name="betrag",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="zahlungseingang",
            name="buchungs_monat",
            field=models.DateField(null=True, verbose_name="Für Monat/Jahr"),
        ),
        migrations.AlterField(
            model_name="zahlungseingang",
            name="datum_eingang",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="zahlungseingang",
            name="erstellt_am",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="zahlungseingang",
            name="konto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.buchungskonto",
            ),
        ),
        migrations.AlterField(
            model_name="zahlungseingang",
            name="liegenschaft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.liegenschaft",
            ),
        ),
    ]
