# Generated by Django 5.2.9 on 2026-04-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_buchungskonto_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kreditorenrechnung",
            options={"verbose_name": "Kreditorenrechnung"},
        ),
        migrations.AddField(
            model_name="abrechnungsperiode",
            name="anfangsbestand_chf",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Anfangsbestand (CHF)",
            ),
        ),
        migrations.AddField(
            model_name="abrechnungsperiode",
            name="anfangsbestand_liter",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Anfangsbestand (L)",
            ),
        ),
        migrations.AddField(
            model_name="abrechnungsperiode",
            name="endbestand_liter",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Endbestand (L) am Stichtag",
            ),
        ),
        migrations.AddField(
            model_name="buchungskonto",
            name="is_hnk_relevant",
            field=models.BooleanField(
                default=False,
                help_text="Kennzeichnet, ob Buchungen auf diesem Konto in die Nebenkostenabrechnung fliessen (z.B. 4000er Konten).",
                verbose_name="HNK-relevant",
            ),
        ),
        migrations.AddField(
            model_name="buchungskonto",
            name="standard_verteilschluessel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m2", "Fläche (m²)"),
                    ("m3", "Volumen (m³)"),
                    ("einheit", "Pro Einheit"),
                ],
                default="m2",
                max_length=20,
                verbose_name="Standard-Verteilschlüssel",
            ),
        ),
        migrations.AddField(
            model_name="kreditorenrechnung",
            name="is_hnk_relevant",
            field=models.BooleanField(default=False, verbose_name="In HNK einbeziehen"),
        ),
        migrations.AddField(
            model_name="kreditorenrechnung",
            name="leistungs_bis",
            field=models.DateField(
                blank=True, null=True, verbose_name="Leistungsperiode Bis"
            ),
        ),
        migrations.AddField(
            model_name="kreditorenrechnung",
            name="leistungs_von",
            field=models.DateField(
                blank=True, null=True, verbose_name="Leistungsperiode Von"
            ),
        ),
        migrations.AddField(
            model_name="kreditorenrechnung",
            name="menge_liter",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Menge (Liter)",
            ),
        ),
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="verteilschluessel",
            field=models.CharField(
                choices=[
                    ("m2", "Nach Fläche (m²)"),
                    ("m3", "Nach Volumen (m³)"),
                    ("einheit", "Pro Wohnung"),
                ],
                default="m2",
                max_length=20,
                verbose_name="Verteilschlüssel",
            ),
        ),
    ]
