# Generated by Django 5.2.9 on 2026-05-04 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_kreditorenrechnung_options_and_more"),
        ("portfolio", "0013_einheit_standard_kautionsmonate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buchung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(default=django.utils.timezone.now)),
                ("beleg_text", models.CharField(max_length=255)),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "haben_konto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="haben_buchungen",
                        to="finance.buchungskonto",
                    ),
                ),
                (
                    "kreditoren_rechnung",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.kreditorenrechnung",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buchungen",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "soll_konto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="soll_buchungen",
                        to="finance.buchungskonto",
                    ),
                ),
                (
                    "zahlungseingang",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.zahlungseingang",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buchung",
                "verbose_name_plural": "Buchungen",
                "db_table": "core_buchung",
                "ordering": ["-datum", "-id"],
            },
        ),
    ]
