# Generated by Django 5.2.9 on 2026-05-11 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_buchung"),
        ("portfolio", "0013_einheit_standard_kautionsmonate_and_more"),
        ("rentals", "0007_mietvertrag_mitmieter_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buchung",
            name="kreditoren_rechnung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buchungen",
                to="finance.kreditorenrechnung",
            ),
        ),
        migrations.AlterField(
            model_name="buchung",
            name="zahlungseingang",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buchungen",
                to="finance.zahlungseingang",
            ),
        ),
        migrations.CreateModel(
            name="DebitorenRechnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titel",
                    models.CharField(max_length=200, verbose_name="Titel / Grund"),
                ),
                ("beschreibung", models.TextField(blank=True, default="")),
                ("datum", models.DateField(default=django.utils.timezone.now)),
                ("faellig_am", models.DateField(blank=True, null=True)),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("bezahlt", "Bezahlt"),
                            ("storniert", "Storniert"),
                        ],
                        default="offen",
                        max_length=20,
                    ),
                ),
                (
                    "pdf_dokument",
                    models.FileField(
                        blank=True, null=True, upload_to="debitoren_rechnungen/"
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "konto_haben",
                    models.ForeignKey(
                        blank=True,
                        help_text="Gegenkonto (z.B. 1190 Durchlaufkonto oder 3000 Ertrag)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.buchungskonto",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "vertrag",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debitoren_rechnungen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Debitorenrechnung (Weiterverrechnung)",
                "verbose_name_plural": "Debitorenrechnungen",
                "db_table": "core_debitorenrechnung",
            },
        ),
        migrations.AddField(
            model_name="buchung",
            name="debitoren_rechnung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buchungen",
                to="finance.debitorenrechnung",
            ),
        ),
    ]
