# Generated by Django 5.2.9 on 2026-05-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_buchung_kreditoren_rechnung_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buchung",
            name="ist_storno",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="buchung",
            name="storniert_am",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="zahlungseingang",
            name="debitoren_rechnung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zahlungseingaenge",
                to="finance.debitorenrechnung",
            ),
        ),
        migrations.AddField(
            model_name="zahlungseingang",
            name="status",
            field=models.CharField(
                choices=[("verbucht", "Verbucht"), ("storniert", "Storniert")],
                default="verbucht",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="debitorenrechnung",
            name="status",
            field=models.CharField(
                choices=[
                    ("offen", "Offen"),
                    ("teilbezahlt", "Teilbezahlt"),
                    ("bezahlt", "Bezahlt"),
                    ("storniert", "Storniert"),
                ],
                default="offen",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="kreditorenrechnung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu / Scan"),
                    ("freigegeben", "Freigegeben"),
                    ("bezahlt", "Bezahlt"),
                    ("storniert", "Storniert"),
                ],
                default="neu",
                max_length=20,
            ),
        ),
    ]
