# Generated by Django 5.2.9 on 2026-07-08 10:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_buchung_erstellt_von_zahlungseingang_erstellt_von"),
    ]

    operations = [
        migrations.AddField(
            model_name="kreditorenrechnung",
            name="mwst_betrag",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Vorsteuer (CHF)",
            ),
        ),
        migrations.AddField(
            model_name="kreditorenrechnung",
            name="mwst_satz",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                max_digits=4,
                verbose_name="MWST-Satz (%)",
            ),
        ),
    ]
