# Generated by Django 5.2.9 on 2026-07-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_kreditorenrechnung_mwst_betrag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="debitorenrechnung",
            name="qr_referenz",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=27,
                verbose_name="QRR-Referenz (27-stellig)",
            ),
        ),
    ]
