# Generated by Django 5.2.9 on 2026-07-08 11:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_debitorenrechnung_qr_referenz"),
        ("rentals", "0012_mietvertrag_mwst_satz"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mahnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stufe",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Mahnstufe"
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Mahndatum"
                    ),
                ),
                (
                    "betrag_offen",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Offener Betrag",
                    ),
                ),
                (
                    "gebuehr",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Mahngebühr",
                    ),
                ),
                (
                    "versandart",
                    models.CharField(
                        choices=[
                            ("email", "E-Mail"),
                            ("brief", "Brief"),
                            ("manuell", "Manuell erfasst"),
                        ],
                        default="manuell",
                        max_length=20,
                        verbose_name="Versand",
                    ),
                ),
                ("bemerkung", models.CharField(blank=True, default="", max_length=255)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "debitoren_rechnung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mahnungen",
                        to="finance.debitorenrechnung",
                    ),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vertrag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mahnungen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahnung",
                "verbose_name_plural": "Mahn-Historie",
                "db_table": "core_mahnung",
                "ordering": ["-datum", "-id"],
            },
        ),
    ]
