# Generated by Django 5.2.9 on 2026-07-08 15:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_mahnung"),
        ("portfolio", "0014_liegenschaft_hkvo_aktiv_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(max_length=200, verbose_name="Bezeichnung"),
                ),
                (
                    "anschaffungswert",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Anschaffungswert (CHF)",
                    ),
                ),
                (
                    "anschaffungsdatum",
                    models.DateField(verbose_name="Anschaffungsdatum"),
                ),
                (
                    "nutzungsdauer_jahre",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Nutzungsdauer (Jahre)"
                    ),
                ),
                (
                    "restwert",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Restwert (CHF)",
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("notizen", models.TextField(blank=True, default="")),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anlagen",
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anlage",
                "verbose_name_plural": "Anlagen",
                "db_table": "core_anlage",
                "ordering": ["liegenschaft", "bezeichnung"],
            },
        ),
        migrations.CreateModel(
            name="Erneuerungsfonds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bestand",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Bestand (CHF)",
                    ),
                ),
                (
                    "jaehrliche_einlage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Jährliche Einlage (CHF)",
                    ),
                ),
                (
                    "letzte_einlage_jahr",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "liegenschaft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="erneuerungsfonds",
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Erneuerungsfonds",
                "verbose_name_plural": "Erneuerungsfonds",
                "db_table": "core_erneuerungsfonds",
            },
        ),
        migrations.CreateModel(
            name="Abschreibung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jahr", models.PositiveIntegerField(verbose_name="Jahr")),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="AfA-Betrag",
                    ),
                ),
                ("datum", models.DateField(verbose_name="Buchungsdatum")),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "buchung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="finance.buchung",
                    ),
                ),
                (
                    "anlage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abschreibungen",
                        to="finance.anlage",
                    ),
                ),
            ],
            options={
                "db_table": "core_abschreibung",
                "ordering": ["-jahr"],
                "unique_together": {("anlage", "jahr")},
            },
        ),
    ]
