# Generated by Django 5.2.9 on 2026-07-08 18:18

from django.db import migrations, models


def backfill_beleg_nr(apps, schema_editor):
    Buchung = apps.get_model("finance", "Buchung")
    nr = 0
    for b in Buchung.objects.order_by("datum", "id").iterator():
        nr += 1
        Buchung.objects.filter(pk=b.pk).update(beleg_nr=nr)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_anlage_erneuerungsfonds_abschreibung"),
    ]

    operations = [
        migrations.AddField(
            model_name="buchung",
            name="beleg_nr",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Beleg-Nr"
            ),
        ),
        migrations.RunPython(backfill_beleg_nr, noop),
    ]
