# Generated by Django 5.2.9 on 2026-07-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_buchung_beleg_nr"),
    ]

    operations = [
        migrations.AddField(
            model_name="zahlungseingang",
            name="bank_referenz",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=140,
                verbose_name="Bank-Referenz",
            ),
        ),
    ]
