# Generated by Django 5.2.9 on 2026-07-12 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_zahlungseingang_bank_referenz"),
    ]

    operations = [
        migrations.AddField(
            model_name="debitorenrechnung",
            name="quell_kreditor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weiterverrechnungen",
                to="finance.kreditorenrechnung",
                verbose_name="Weiterverrechnung aus Kreditorenrechnung",
            ),
        ),
    ]
