# Generated by Django 5.2.9 on 2026-07-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_debitorenrechnung_quell_kreditor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kreditorenrechnung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu / Scan"),
                    ("freigegeben", "Freigegeben"),
                    ("in_zahlung", "In Zahlung"),
                    ("bezahlt", "Bezahlt"),
                    ("storniert", "Storniert"),
                ],
                default="neu",
                max_length=20,
            ),
        ),
    ]
