# Generated by Django 5.2.9 on 2026-07-12 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_alter_kreditorenrechnung_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="kreditorenrechnung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu / Scan"),
                    ("freigegeben", "Freigegeben"),
                    ("in_zahlung", "In Zahlung"),
                    ("teilbezahlt", "Teilbezahlt"),
                    ("bezahlt", "Bezahlt"),
                    ("storniert", "Storniert"),
                ],
                default="neu",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="KreditorenZahlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=10)),
                ("datum", models.DateField(default=django.utils.timezone.now)),
                (
                    "bank_referenz",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=140,
                        verbose_name="Bank-Referenz",
                    ),
                ),
                ("bemerkung", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("verbucht", "Verbucht"), ("storniert", "Storniert")],
                        default="verbucht",
                        max_length=20,
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.buchungskonto",
                    ),
                ),
                (
                    "kreditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zahlungen",
                        to="finance.kreditorenrechnung",
                    ),
                ),
            ],
            options={
                "db_table": "core_kreditorenzahlung",
                "ordering": ["-datum", "-id"],
            },
        ),
    ]
