# Generated by Django 5.2.9 on 2026-07-12 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0015_alter_kreditorenrechnung_status_kreditorenzahlung"),
    ]

    operations = [
        migrations.AddField(
            model_name="buchung",
            name="storno_von",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stornierungen",
                to="finance.buchung",
            ),
        ),
    ]
