# Generated by Django 5.2.9 on 2026-07-12 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_verwaltung_abo_jaehrlich_verwaltung_abo_plan"),
        ("finance", "0016_buchung_storno_von"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="buchungskonto",
            name="typ",
            field=models.CharField(
                choices=[
                    ("aufwand", "Aufwand"),
                    ("ertrag", "Ertrag"),
                    ("bilanz", "Bilanz"),
                    ("aktiv", "Aktivum"),
                    ("passiv", "Passivum / Eigenkapital"),
                ],
                max_length=20,
                verbose_name="Typ",
            ),
        ),
        migrations.CreateModel(
            name="EigentuemerAuszahlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=12)),
                ("datum", models.DateField(default=django.utils.timezone.now)),
                ("bemerkung", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("verbucht", "Verbucht"), ("storniert", "Storniert")],
                        default="verbucht",
                        max_length=20,
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bankkonto der Auszahlung (Haben)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.buchungskonto",
                    ),
                ),
                (
                    "mandant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auszahlungen",
                        to="crm.mandant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eigentümer-Auszahlung",
                "verbose_name_plural": "Eigentümer-Auszahlungen",
                "db_table": "core_eigentuemerauszahlung",
                "ordering": ["-datum", "-id"],
            },
        ),
    ]
