# Generated by Django 5.2.9 on 2026-07-13 09:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0017_alter_buchungskonto_typ_eigentuemerauszahlung"),
        ("portfolio", "0019_seed_lebensdauer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hypothek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Bank / Gläubiger",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Bezeichnung / Tranche",
                    ),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Betrag (CHF)",
                    ),
                ),
                (
                    "zinssatz",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        max_digits=5,
                        verbose_name="Zinssatz (%)",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("fest", "Festhypothek"),
                            ("saron", "SARON"),
                            ("variabel", "Variabel"),
                        ],
                        default="fest",
                        max_length=10,
                    ),
                ),
                (
                    "beginn",
                    models.DateField(
                        blank=True, null=True, verbose_name="Abschluss / Beginn"
                    ),
                ),
                (
                    "ablauf",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ablauf / Fälligkeit"
                    ),
                ),
                ("notiz", models.TextField(blank=True, default="")),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hypotheken",
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hypothek",
                "verbose_name_plural": "Hypotheken",
                "db_table": "core_hypothek",
                "ordering": ["ablauf", "id"],
            },
        ),
    ]
