# Generated by Django 5.2.9 on 2026-07-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0018_hypothek"),
    ]

    operations = [
        migrations.CreateModel(
            name="LieferantProfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_key",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Namensschlüssel"
                    ),
                ),
                (
                    "name_anzeige",
                    models.CharField(max_length=200, verbose_name="Lieferant"),
                ),
                ("iban", models.CharField(blank=True, max_length=50)),
                (
                    "treffer",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Gelernte Belege"
                    ),
                ),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "standard_konto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lieferanten",
                        to="finance.buchungskonto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lieferantenprofil",
                "db_table": "finance_lieferantprofil",
                "ordering": ["name_anzeige"],
            },
        ),
    ]
