# Generated by Django 5.2.9 on 2026-07-15 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0019_lieferantprofil"),
        ("portfolio", "0026_sollmietzins_quelle_anpassung"),
    ]

    operations = [
        migrations.CreateModel(
            name="KreditorPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Betrag (brutto)"
                    ),
                ),
                (
                    "is_hnk_relevant",
                    models.BooleanField(default=False, verbose_name="HNK-relevant"),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kreditor_positionen",
                        to="finance.buchungskonto",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "rechnung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="finance.kreditorenrechnung",
                    ),
                ),
            ],
            options={
                "db_table": "finance_kreditorposition",
                "ordering": ["id"],
            },
        ),
    ]
