# Generated by Django 5.2.9 on 2026-07-16 16:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0020_kreditorposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="debitorenrechnung",
            name="weiterverrechnung_zuschlag",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Weiterverrechnungs-Zuschlag (CHF)",
            ),
        ),
    ]
