# Generated by Django 5.2.9 on 2026-07-17 21:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0021_debitorenrechnung_weiterverrechnung_zuschlag"),
    ]

    operations = [
        migrations.AddField(
            model_name="mahnung",
            name="zins",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="Verzugszins (fakturiert)",
            ),
        ),
    ]
