# Generated by Django 5.2.9 on 2026-07-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0022_mahnung_zins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debitorenrechnung",
            name="status",
            field=models.CharField(
                choices=[
                    ("offen", "Offen"),
                    ("teilbezahlt", "Teilbezahlt"),
                    ("bezahlt", "Bezahlt"),
                    ("storniert", "Storniert"),
                    ("abgeschrieben", "Abgeschrieben"),
                ],
                default="offen",
                max_length=20,
            ),
        ),
    ]
