# Generated by Django 5.2.9 on 2026-07-30 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0023_alter_debitorenrechnung_status"),
        ("rentals", "0028_mietvertrag_solidarhaftung_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="buchung",
            name="beleg_nr",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Beleg-Nr"
            ),
        ),
        migrations.AddConstraint(
            model_name="mahnung",
            constraint=models.UniqueConstraint(
                condition=models.Q(("debitoren_rechnung__isnull", False)),
                fields=("debitoren_rechnung", "stufe"),
                name="uniq_mahnung_rechnung_stufe",
            ),
        ),
    ]
