# Generated by Django 5.2.9 on 2026-07-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0024_alter_buchung_beleg_nr_and_more"),
        ("portfolio", "0030_liegenschaft_anlagekosten_and_more"),
        ("rentals", "0028_mietvertrag_solidarhaftung_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="debitorenrechnung",
            index=models.Index(
                fields=["status", "faellig_am"], name="idx_debrech_status_faellig"
            ),
        ),
        migrations.AddIndex(
            model_name="debitorenrechnung",
            index=models.Index(
                fields=["vertrag", "status"], name="idx_debrech_vertrag_status"
            ),
        ),
    ]
