# Generated by Django 5.2.9 on 2026-08-01 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0025_debitorenrechnung_idx_debrech_status_faellig_and_more"),
        ("portfolio", "0030_liegenschaft_anlagekosten_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kontoauszug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=34,
                        verbose_name="IBAN",
                    ),
                ),
                (
                    "von",
                    models.DateField(blank=True, null=True, verbose_name="Periode von"),
                ),
                (
                    "bis",
                    models.DateField(blank=True, null=True, verbose_name="Periode bis"),
                ),
                (
                    "eroeffnungssaldo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Eröffnungssaldo",
                    ),
                ),
                (
                    "schlusssaldo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Schlusssaldo laut Auszug",
                    ),
                ),
                ("dateiname", models.CharField(blank=True, default="", max_length=255)),
                ("quelle", models.CharField(blank=True, default="", max_length=30)),
                ("importiert_am", models.DateTimeField(auto_now_add=True)),
                (
                    "importiert_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        help_text="Buchhaltungskonto, das dieses Bankkonto abbildet",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kontoauszuege",
                        to="finance.buchungskonto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontoauszug",
                "verbose_name_plural": "Kontoauszüge",
                "ordering": ["-bis", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Bankbewegung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datum",
                    models.DateField(db_index=True, verbose_name="Buchungsdatum"),
                ),
                (
                    "valuta",
                    models.DateField(blank=True, null=True, verbose_name="Valutadatum"),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="positiv = Gutschrift, negativ = Belastung",
                        max_digits=12,
                        verbose_name="Betrag",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Text / Mitteilung",
                    ),
                ),
                (
                    "gegenpartei",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=160,
                        verbose_name="Auftraggeber / Empfänger",
                    ),
                ),
                (
                    "referenz",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="QR-Referenz",
                    ),
                ),
                (
                    "bank_referenz",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=140
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("verbucht", "Verbucht"),
                            ("ignoriert", "Ignoriert"),
                        ],
                        db_index=True,
                        default="offen",
                        max_length=12,
                    ),
                ),
                ("bemerkung", models.CharField(blank=True, default="", max_length=255)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "buchung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bankbewegungen",
                        to="finance.buchung",
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        help_text="Bankkonto (Buchhaltungskonto) dieser Bewegung",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bankbewegungen",
                        to="finance.buchungskonto",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bankbewegungen",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "zahlung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bankbewegungen",
                        to="finance.zahlungseingang",
                    ),
                ),
                (
                    "auszug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bewegungen",
                        to="finance.kontoauszug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bankbewegung",
                "verbose_name_plural": "Bankbewegungen",
                "ordering": ["-datum", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "datum"], name="idx_bankbew_status_datum"
                    )
                ],
            },
        ),
    ]
