# Generated by Django 5.2.9 on 2026-08-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0026_kontoauszug_bankbewegung"),
    ]

    operations = [
        migrations.AddField(
            model_name="kreditorenrechnung",
            name="zahlung_ausfuehrung",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ausführung Zahllauf"
            ),
        ),
    ]
