# Generated by Django 5.2.9 on 2026-08-01 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0027_kreditor_zahlung_ausfuehrung"),
        ("rentals", "0029_mietvertrag_idx_mietvertrag_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZahlerZuordnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_norm",
                    models.CharField(
                        db_index=True,
                        max_length=160,
                        unique=True,
                        verbose_name="Absender (normalisiert)",
                    ),
                ),
                (
                    "name_anzeige",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="Absender"
                    ),
                ),
                (
                    "treffer",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Automatisch getroffen"
                    ),
                ),
                (
                    "zuletzt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zuletzt getroffen"
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "vertrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zahler_zuordnungen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zahler-Zuordnung",
                "verbose_name_plural": "Zahler-Zuordnungen",
                "ordering": ["name_anzeige"],
            },
        ),
    ]
