# Generated by Django 5.2.9 on 2026-08-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0028_zahlerzuordnung"),
    ]

    operations = [
        migrations.AddField(
            model_name="debitorenrechnung",
            name="stammrechnung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="folgeforderungen",
                to="finance.debitorenrechnung",
                verbose_name="Stammrechnung (Mahngebühr/Zins gehört zu)",
            ),
        ),
    ]
