# Generated by Django 5.2.9 on 2026-08-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0029_debitorenrechnung_stammrechnung"),
    ]

    operations = [
        migrations.AddField(
            model_name="abrechnungsperiode",
            name="snapshot_json",
            field=models.TextField(
                blank=True, default="", verbose_name="Eingefrorene Abrechnung (JSON)"
            ),
        ),
    ]
