# Generated by Django 5.2.9 on 2026-08-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0030_abrechnungsperiode_snapshot_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nebenkostenbeleg",
            name="verteilschluessel",
            field=models.CharField(
                choices=[
                    ("m2", "Nach Fläche (m²)"),
                    ("m3", "Nach Volumen (m³)"),
                    ("einheit", "Pro Wohnung"),
                    ("personen", "Nach Personenzahl"),
                ],
                default="m2",
                max_length=20,
                verbose_name="Verteilschlüssel",
            ),
        ),
    ]
