# Generated by Django 5.2.9 on 2026-08-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0030_alter_eigentuemer_bank_name"),
        ("finance", "0033_auszahlung_eigentuemer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eigentuemerauszahlung",
            name="eigentuemer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auszahlungen",
                to="crm.eigentuemer",
            ),
        ),
    ]
