# Generated by Django 5.2.9 on 2026-09-30 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0045_abostufen_marktnamen"),
        ("finance", "0040_organisation_rest_pflicht"),
        ("rentals", "0037_dokument_organisation_pflicht"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Zahlungsvereinbarung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "betrag_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Rückstand bei Abschluss (CHF)",
                    ),
                ),
                (
                    "gedeckt_bis",
                    models.DateField(verbose_name="Gedeckte Forderungen: fällig bis"),
                ),
                (
                    "anzahl_raten",
                    models.PositiveSmallIntegerField(verbose_name="Anzahl Raten"),
                ),
                ("erste_rate", models.DateField(verbose_name="Erste Rate am")),
                (
                    "intervall_monate",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Abstand der Raten (Monate)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktiv", "Aktiv"),
                            ("erfuellt", "Erfüllt"),
                            ("gebrochen", "Gebrochen"),
                            ("abgebrochen", "Abgebrochen"),
                        ],
                        default="aktiv",
                        max_length=12,
                    ),
                ),
                ("notiz", models.CharField(blank=True, default="", max_length=255)),
                ("erfasst_am", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "vertrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zahlungsvereinbarungen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zahlungsvereinbarung",
                "verbose_name_plural": "Zahlungsvereinbarungen",
                "ordering": ["-erfasst_am", "-id"],
            },
        ),
    ]
