# Generated by Django 5.2.9 on 2026-09-30 13:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0041_zahlungsvereinbarung"),
    ]

    operations = [
        migrations.AddField(
            model_name="kreditorenrechnung",
            name="weiterverrechnung_eigentuemer",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Bei Verteilung beim Eigentümer verbleibend (Leerstand)",
            ),
        ),
    ]
