# Generated by Django 5.2.9 on 2026-10-02 11:46

from decimal import Decimal
from django.db import migrations, models


def mwst_aus_buchungen(apps, schema_editor):
    """Bestandsrechnungen: MWST-Betrag aus den 1100/2200-Buchungen, Satz aus dem Vertrag.

    Nur Rechnungen, bei denen die Sollstellung MWST auf 2200 gebucht hat — alles
    andere (Wohnraum) bleibt bei 0 und das PDF weist weiterhin nichts aus."""
    Buchung = apps.get_model('finance', 'Buchung')
    Rechnung = apps.get_model('finance', 'DebitorenRechnung')
    from django.db.models import Sum
    summen = (Buchung.objects.filter(soll_konto__nummer='1100', haben_konto__nummer='2200',
                                     ist_storno=False, debitoren_rechnung__isnull=False)
              .values('debitoren_rechnung').annotate(s=Sum('betrag')))
    for z in summen:
        if not z['s'] or z['s'] <= 0:
            continue
        r = Rechnung.objects.filter(pk=z['debitoren_rechnung']).select_related('vertrag').first()
        if r is None:
            continue
        satz = getattr(r.vertrag, 'mwst_satz', None) or Decimal('0.0')
        Rechnung.objects.filter(pk=r.pk).update(mwst_betrag=z['s'], mwst_satz=satz)


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0042_kreditor_weiterverrechnung_eigentuemer"),
    ]

    operations = [
        migrations.AddField(
            model_name="debitorenrechnung",
            name="mwst_betrag",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="MWST (CHF)",
            ),
        ),
        migrations.AddField(
            model_name="debitorenrechnung",
            name="mwst_satz",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                max_digits=4,
                verbose_name="MWST-Satz (%)",
            ),
        ),
        migrations.RunPython(mwst_aus_buchungen, migrations.RunPython.noop),
    ]
