# Generated by Django 5.2.9 on 2026-10-04 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("finance", "0043_debitor_mwst_ausweis"),
        ("portfolio", "0042_versicherung_selbstbehalt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErneuerungsfondsBewegung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[("einlage", "Einlage"), ("entnahme", "Entnahme")],
                        max_length=10,
                    ),
                ),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=12)),
                ("jahr", models.PositiveIntegerField()),
                ("datum", models.DateField(default=django.utils.timezone.localdate)),
                ("text", models.CharField(blank=True, default="", max_length=255)),
                (
                    "buchung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="finance.buchung",
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fonds_bewegungen",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "fonds",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bewegungen",
                        to="finance.erneuerungsfonds",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "finance_erneuerungsfondsbewegung",
                "ordering": ["datum", "id"],
            },
        ),
    ]
