# Generated by Django 5.2.9 on 2026-10-05 13:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("finance", "0044_stweg_grundlagen"),
        ("rentals", "0044_mietzinsanpassung_anteile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="abrechnungsperiode",
            name="versand_kanal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "E-Mail"),
                    ("brief", "Brief"),
                    ("portal", "Mieterportal"),
                ],
                default="",
                max_length=20,
                verbose_name="Zustellung",
            ),
        ),
        migrations.AddField(
            model_name="abrechnungsperiode",
            name="versendet_am",
            field=models.DateField(
                blank=True, null=True, verbose_name="Abrechnung zugestellt am"
            ),
        ),
        migrations.CreateModel(
            name="Betreibung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("begehren", "Begehren eingereicht"),
                            ("zahlungsbefehl", "Zahlungsbefehl zugestellt"),
                            ("rechtsvorschlag", "Rechtsvorschlag erhoben"),
                            ("rechtsoeffnung", "Rechtsöffnung beantragt/erteilt"),
                            ("fortsetzung", "Fortsetzungsbegehren"),
                            ("bezahlt", "Bezahlt"),
                            ("verlustschein", "Verlustschein"),
                            ("zurueckgezogen", "Zurückgezogen"),
                        ],
                        default="begehren",
                        max_length=20,
                        verbose_name="Stand",
                    ),
                ),
                (
                    "betreibungsamt",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Betreibungsamt",
                    ),
                ),
                (
                    "betreibungsnummer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Betreibungsnummer",
                    ),
                ),
                (
                    "forderung",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Forderung (CHF)",
                    ),
                ),
                (
                    "kosten",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Betreibungskosten (CHF)",
                    ),
                ),
                (
                    "begehren_am",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Betreibungsbegehren am",
                    ),
                ),
                (
                    "zahlungsbefehl_am",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Zahlungsbefehl zugestellt am",
                    ),
                ),
                (
                    "rechtsvorschlag_am",
                    models.DateField(
                        blank=True, null=True, verbose_name="Rechtsvorschlag am"
                    ),
                ),
                (
                    "rechtsoeffnung_am",
                    models.DateField(
                        blank=True, null=True, verbose_name="Rechtsöffnung am"
                    ),
                ),
                (
                    "fortsetzung_am",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fortsetzungsbegehren am"
                    ),
                ),
                (
                    "verlustschein_am",
                    models.DateField(
                        blank=True, null=True, verbose_name="Verlustschein am"
                    ),
                ),
                ("bemerkung", models.TextField(blank=True, default="")),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "debitoren_rechnung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="betreibungen",
                        to="finance.debitorenrechnung",
                    ),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "vertrag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="betreibungen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Betreibung",
                "verbose_name_plural": "Betreibungen",
                "ordering": ["-begehren_am", "-id"],
            },
        ),
    ]
