# Generated by Django 5.2.9 on 2026-03-31 08:06

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leerstand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beginn", models.DateField()),
                ("ende", models.DateField(blank=True, null=True)),
                ("grund", models.CharField(default="mietersuche", max_length=50)),
                ("bemerkung", models.TextField(blank=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leerstaende",
                        to="portfolio.einheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leerstand",
                "db_table": "core_leerstand",
            },
        ),
        migrations.CreateModel(
            name="Mietvertrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beginn", models.DateField()),
                ("ende", models.DateField(blank=True, null=True)),
                ("netto_mietzins", models.DecimalField(decimal_places=2, max_digits=8)),
                ("nebenkosten", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "basis_referenzzinssatz",
                    models.DecimalField(
                        decimal_places=2,
                        default=core.utils.get_current_ref_zins,
                        max_digits=4,
                    ),
                ),
                (
                    "basis_lik_punkte",
                    models.DecimalField(
                        decimal_places=1,
                        default=core.utils.get_current_lik,
                        max_digits=6,
                    ),
                ),
                ("aktiv", models.BooleanField(default=True)),
                (
                    "sign_status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("gesendet", "Versendet"),
                            ("unterzeichnet", "Unterzeichnet"),
                        ],
                        default="offen",
                        max_length=20,
                    ),
                ),
                (
                    "pdf_datei",
                    models.FileField(
                        blank=True, null=True, upload_to="vertraege_pdfs/"
                    ),
                ),
                (
                    "kautions_betrag",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vertraege",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "mieter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vertraege",
                        to="crm.mieter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mietvertrag",
                "verbose_name_plural": "Mietverträge",
                "db_table": "core_mietvertrag",
            },
        ),
        migrations.CreateModel(
            name="Dokument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bezeichnung", models.CharField(default="Dokument", max_length=200)),
                ("titel", models.CharField(blank=True, max_length=200)),
                ("datei", models.FileField(upload_to=core.utils.get_smart_upload_path)),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("vertrag", "Vertrag"),
                            ("protokoll", "Protokoll"),
                            ("korrespondenz", "Korrespondenz"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        max_length=50,
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "mandant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.mandant",
                    ),
                ),
                (
                    "mieter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.mieter",
                    ),
                ),
                (
                    "vertrag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dokumente",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumente",
                "db_table": "core_dokument",
            },
        ),
        migrations.CreateModel(
            name="MietzinsAnpassung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wirksam_ab", models.DateField()),
                (
                    "neuer_netto_mietzins",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "alter_netto_mietzins",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "alter_referenzzinssatz",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "alter_lik_index",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "neuer_referenzzinssatz",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "neuer_lik_index",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "erhoehung_prozent_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("begruendung", models.TextField(blank=True, null=True)),
                (
                    "vertrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anpassungen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mietzinsanpassung",
                "db_table": "core_mietzinsanpassung",
            },
        ),
    ]
