# Generated by Django 5.2.9 on 2026-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="nebenobjekte",
            field=models.ManyToManyField(
                blank=True,
                related_name="als_nebenobjekt_in_vertraegen",
                to="portfolio.einheit",
            ),
        ),
    ]
