# Generated by Django 5.2.9 on 2026-04-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_mietvertrag_nebenobjekte"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="ausgeschlossene_kosten",
            field=models.TextField(
                blank=True,
                help_text="Welche Kosten zahlt dieser Mieter NICHT? (z.B. Lift im EG, Gartenpflege bei Attika etc.)",
                verbose_name="Ausgeschlossene Kosten",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="nk_abrechnungsart",
            field=models.CharField(
                choices=[
                    ("akonto", "Akonto (Vorschuss mit Abrechnung)"),
                    ("pauschal", "Pauschal (fixer Betrag ohne Abrechnung)"),
                    ("inbegriffen", "Inbegriffen (im Nettomietzins enthalten)"),
                    ("direkt", "Direkt (Mieter zahlt direkt an Werke)"),
                ],
                default="akonto",
                max_length=20,
                verbose_name="NK-Abrechnungsart",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="verteilschluessel",
            field=models.CharField(
                choices=[
                    ("m2", "Fläche (m²)"),
                    ("m3", "Volumen (m³)"),
                    ("quote", "Wertquote"),
                    ("einheit", "Pro Einheit / Pauschal"),
                    ("individuell", "Individuelle Zähler (VHKA)"),
                ],
                default="m2",
                max_length=20,
                verbose_name="Verteilschlüssel",
            ),
        ),
    ]
