# Generated by Django 5.2.9 on 2026-04-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_mietvertrag_ausgeschlossene_kosten_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dokument",
            options={},
        ),
        migrations.AlterModelOptions(
            name="leerstand",
            options={},
        ),
        migrations.AlterModelOptions(
            name="mietzinsanpassung",
            options={},
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kautions_einbezahlt_am",
            field=models.DateField(
                blank=True, null=True, verbose_name="Kaution einbezahlt am"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kautions_konto",
            field=models.CharField(
                blank=True,
                default="",
                max_length=34,
                verbose_name="Kautionskonto (IBAN)",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kuendigungsfrist_monate",
            field=models.IntegerField(
                default=3, verbose_name="Kündigungsfrist (Monate)"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kuendigungstermine",
            field=models.CharField(
                blank=True,
                default="Ende jedes Monats ausser Dezember",
                max_length=100,
                verbose_name="Kündigungstermine",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="status",
            field=models.CharField(
                choices=[
                    ("entwurf", "Entwurf"),
                    ("aktiv", "Aktiv"),
                    ("gekuendigt", "Gekündigt"),
                    ("archiviert", "Archiviert"),
                ],
                default="entwurf",
                max_length=20,
                verbose_name="Vertragsstatus",
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="ausgeschlossene_kosten",
            field=models.TextField(
                blank=True,
                help_text="Welche Kosten zahlt dieser Mieter NICHT?",
                verbose_name="Ausgeschlossene Kosten",
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="kautions_betrag",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Kautionsbetrag",
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="sign_status",
            field=models.CharField(
                choices=[
                    ("offen", "Offen"),
                    ("gesendet", "Versendet"),
                    ("unterzeichnet", "Unterzeichnet"),
                ],
                default="offen",
                max_length=20,
                verbose_name="Signatur-Status",
            ),
        ),
    ]
