# Generated by Django 5.2.9 on 2026-04-29 11:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0004_alter_dokument_options_alter_leerstand_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dokument",
            name="erstellt_am",
        ),
        migrations.AddField(
            model_name="dokument",
            name="datum",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 4, 29, 11, 0, 39, 836793, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dokument",
            name="vertrag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dokument_ablage",
                to="rentals.mietvertrag",
            ),
        ),
        migrations.AlterField(
            model_name="mietvertrag",
            name="pdf_datei",
            field=models.FileField(blank=True, null=True, upload_to="roh_vertraege/"),
        ),
    ]
