# Generated by Django 5.2.9 on 2026-05-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0005_remove_dokument_erstellt_am_dokument_datum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="anzahl_personen",
            field=models.IntegerField(default=1, verbose_name="Anzahl Personen"),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="besondere_vereinbarungen",
            field=models.TextField(
                blank=True, default="", verbose_name="Besondere Vereinbarungen"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="erstmals_kuendbar_auf",
            field=models.DateField(
                blank=True, null=True, verbose_name="Erstmals kündbar auf"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="familienwohnung",
            field=models.BooleanField(default=False, verbose_name="Familienwohnung"),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kostensteigerung_datum",
            field=models.DateField(
                blank=True, null=True, verbose_name="Kostensteigerung ausgeglichen bis"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="mietzinsreserve_betrag",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Reserve Betrag (CHF)",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="mietzinsreserve_prozent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Reserve Prozent (%)",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="weitere_vorbehalte",
            field=models.TextField(
                blank=True, default="", verbose_name="Weitere Vorbehalte"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="zahlungsrhythmus",
            field=models.CharField(
                choices=[
                    ("monatlich", "monatlich"),
                    ("vierteljahr", "vierteljährlich"),
                    ("halbjahr", "halbjährlich"),
                    ("jahr", "jährlich"),
                ],
                default="monatlich",
                max_length=20,
                verbose_name="Zahlungsrhythmus",
            ),
        ),
    ]
