# Generated by Django 5.2.9 on 2026-05-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0006_mietvertrag_anzahl_personen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="mitmieter_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Ehegatte / Mitmieter",
            ),
        ),
    ]
