# Generated by Django 5.2.9 on 2026-07-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0007_mietvertrag_mitmieter_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="mitbenutzung",
            field=models.TextField(
                blank=True, default="", verbose_name="Zur Mitbenützung"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="mwst_pflichtig",
            field=models.BooleanField(default=False, verbose_name="MWST-pflichtig"),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="nebenraeume",
            field=models.TextField(blank=True, default="", verbose_name="Nebenräume"),
        ),
    ]
