# Generated by Django 5.2.9 on 2026-07-08 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_mandant_benutzer"),
        (
            "rentals",
            "0008_mietvertrag_mitbenutzung_mietvertrag_mwst_pflichtig_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="mitmieter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vertraege_als_mitmieter",
                to="crm.mieter",
                verbose_name="Zweiter Mieter",
            ),
        ),
    ]
