# Generated by Django 5.2.9 on 2026-07-08 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0009_mietvertrag_mitmieter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kuendigung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "absender",
                    models.CharField(
                        choices=[("mieter", "Mieter"), ("vermieter", "Vermieter")],
                        default="mieter",
                        max_length=20,
                        verbose_name="Gekündigt durch",
                    ),
                ),
                (
                    "eingang_datum",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Eingang / Poststempel",
                    ),
                ),
                (
                    "zustellung",
                    models.CharField(
                        choices=[
                            ("einschreiben", "Einschreiben (Mieter)"),
                            ("amtliches_formular", "Amtliches Formular (Vermieter)"),
                            ("normal", "Normal / persönlich"),
                        ],
                        default="einschreiben",
                        max_length=30,
                        verbose_name="Zustellung",
                    ),
                ),
                (
                    "gewuenschtes_ende",
                    models.DateField(
                        blank=True, null=True, verbose_name="Gewünschtes Vertragsende"
                    ),
                ),
                (
                    "berechneter_termin",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Nächster ordentlicher Termin",
                    ),
                ),
                (
                    "per_datum",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vertragsende (wirksam)"
                    ),
                ),
                (
                    "ausserordentlich",
                    models.BooleanField(
                        default=False, verbose_name="Ausserordentliche Kündigung"
                    ),
                ),
                (
                    "ausserordentlich_grund",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Grund (ausserordentlich)",
                    ),
                ),
                (
                    "erstreckung_bis",
                    models.DateField(
                        blank=True, null=True, verbose_name="Erstreckung bis"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("erfasst", "Erfasst"),
                            ("bestaetigt", "Bestätigt"),
                            ("vollzogen", "Vollzogen"),
                            ("zurueckgezogen", "Zurückgezogen"),
                        ],
                        default="erfasst",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "bemerkung",
                    models.TextField(blank=True, default="", verbose_name="Bemerkung"),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "vertrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kuendigungen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kündigung",
                "verbose_name_plural": "Kündigungen",
                "db_table": "core_kuendigung",
                "ordering": ["-eingang_datum"],
            },
        ),
    ]
