# Generated by Django 5.2.9 on 2026-07-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0010_kuendigung"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="kautions_abzug_betrag",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Einbehalt / Abzug",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kautions_abzug_grund",
            field=models.TextField(
                blank=True, default="", verbose_name="Grund des Einbehalts"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kautions_rueckzahlung_betrag",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Rückzahlung an Mieter",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kautions_zurueckbezahlt_am",
            field=models.DateField(
                blank=True, null=True, verbose_name="Kaution zurückbezahlt am"
            ),
        ),
    ]
