# Generated by Django 5.2.9 on 2026-07-08 10:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0011_mietvertrag_kautions_abzug_betrag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="mwst_satz",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("8.1"),
                max_digits=4,
                verbose_name="MWST-Satz (%)",
            ),
        ),
    ]
