# Generated by Django 5.2.9 on 2026-07-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0012_mietvertrag_mwst_satz"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="kautions_art",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sperrkonto", "Sperrkonto (Bankdepot)"),
                    ("versicherung", "Kautionsversicherung"),
                ],
                default="sperrkonto",
                max_length=20,
                verbose_name="Kautionsart",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kautions_policennummer",
            field=models.CharField(
                blank=True, default="", max_length=60, verbose_name="Policennummer"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kautions_versicherer",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="Versicherer / Anbieter",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="kautions_zertifikat",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="kautions_zertifikate/",
                verbose_name="Zertifikat / Police",
            ),
        ),
    ]
