# Generated by Django 5.2.9 on 2026-07-08 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0013_mietvertrag_kautions_art_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abnahmeprotokoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("einzug", "Einzug / Übergabe"),
                            ("auszug", "Auszug / Rücknahme"),
                        ],
                        default="auszug",
                        max_length=10,
                        verbose_name="Art",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Datum"
                    ),
                ),
                (
                    "mieter_anwesend",
                    models.BooleanField(default=True, verbose_name="Mieter anwesend"),
                ),
                (
                    "verwalter_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Abnahme durch",
                    ),
                ),
                (
                    "allgemein_zustand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("neuwertig", "Neuwertig"),
                            ("gut", "Gut"),
                            ("gebraucht", "Gebraucht"),
                            ("renovationsbeduerftig", "Renovationsbedürftig"),
                        ],
                        default="gut",
                        max_length=25,
                        verbose_name="Allgemeinzustand",
                    ),
                ),
                (
                    "schluessel_anzahl",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Schlüssel zurück"
                    ),
                ),
                (
                    "zaehler_strom",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Zählerstand Strom",
                    ),
                ),
                (
                    "zaehler_wasser",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Zählerstand Wasser",
                    ),
                ),
                (
                    "zaehler_gas",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Zählerstand Gas/Wärme",
                    ),
                ),
                (
                    "neue_adresse",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Neue Adresse des Mieters",
                    ),
                ),
                (
                    "bemerkungen",
                    models.TextField(
                        blank=True, default="", verbose_name="Bemerkungen"
                    ),
                ),
                (
                    "unterschrift_mieter",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Unterschrift Mieter",
                    ),
                ),
                (
                    "unterschrift_verwalter",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Unterschrift Verwalter",
                    ),
                ),
                (
                    "abgeschlossen",
                    models.BooleanField(default=False, verbose_name="Abgeschlossen"),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "vertrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abnahmen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abnahmeprotokoll",
                "verbose_name_plural": "Abnahmeprotokolle",
                "db_table": "core_abnahmeprotokoll",
                "ordering": ["-datum", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AbnahmeMangel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raum",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="Raum"
                    ),
                ),
                (
                    "beschreibung",
                    models.CharField(max_length=255, verbose_name="Mangel"),
                ),
                (
                    "verursacher",
                    models.CharField(
                        choices=[
                            ("abnutzung", "Normale Abnutzung"),
                            ("mieter", "Mieter (Schaden)"),
                            ("vermieter", "Vermieter/Unterhalt"),
                        ],
                        default="abnutzung",
                        max_length=12,
                        verbose_name="Verursacher",
                    ),
                ),
                (
                    "kostenschaetzung",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="Kostenschätzung CHF",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="abnahme_fotos/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "protokoll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maengel",
                        to="rentals.abnahmeprotokoll",
                    ),
                ),
            ],
            options={
                "db_table": "core_abnahmemangel",
                "ordering": ["id"],
            },
        ),
    ]
