# Generated by Django 5.2.9 on 2026-07-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0014_abnahmeprotokoll_abnahmemangel"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="basis_lik_stand",
            field=models.DateField(
                blank=True, null=True, verbose_name="LIK Basis Stand-Monat"
            ),
        ),
    ]
