# Generated by Django 5.2.9 on 2026-07-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0015_mietvertrag_basis_lik_stand"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokument",
            name="im_portal_sichtbar",
            field=models.BooleanField(
                default=True, verbose_name="Im Mieterportal sichtbar"
            ),
        ),
    ]
