# Generated by Django 5.2.9 on 2026-07-10 16:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0016_dokument_im_portal_sichtbar"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="index_intervall_monate",
            field=models.IntegerField(
                default=12, verbose_name="Index-Mindestintervall (Monate)"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="index_letzte_anpassung",
            field=models.DateField(
                blank=True, null=True, verbose_name="Letzte Indexanpassung"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="index_weitergabe_prozent",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("100.0"),
                max_digits=5,
                verbose_name="Index-Weitergabe (%)",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="mietzins_modell",
            field=models.CharField(
                choices=[
                    ("fest", "Fester Mietzins"),
                    ("index", "Indexmiete (LIK, Art. 269b)"),
                    ("staffel", "Staffelmiete (Art. 269c)"),
                ],
                default="fest",
                max_length=10,
                verbose_name="Mietzinsmodell",
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="zweckbestimmung",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Nutzungszweck (Geschäftsraum)",
            ),
        ),
        migrations.CreateModel(
            name="Staffelstufe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ab_datum", models.DateField(verbose_name="Gültig ab")),
                (
                    "netto_mietzins",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Netto-Mietzins ab Stichtag",
                    ),
                ),
                (
                    "vertrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffelstufen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staffelstufe",
                "verbose_name_plural": "Staffelstufen",
                "db_table": "core_staffelstufe",
                "ordering": ["ab_datum"],
            },
        ),
    ]
