# Generated by Django 5.2.9 on 2026-07-13 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_seed_lebensdauer"),
        ("rentals", "0017_mietvertrag_index_intervall_monate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abnahmemangel",
            name="ausstattung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maengel",
                to="portfolio.ausstattung",
            ),
        ),
        migrations.AddField(
            model_name="abnahmemangel",
            name="mieteranteil",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                verbose_name="Mieteranteil CHF (nach Lebensdauer)",
            ),
        ),
        migrations.AddField(
            model_name="abnahmemangel",
            name="neuwert",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                verbose_name="Neuwert CHF",
            ),
        ),
    ]
