# Generated by Django 5.2.9 on 2026-07-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rentals",
            "0018_abnahmemangel_ausstattung_abnahmemangel_mieteranteil_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dokument",
            name="erstellt_am",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Abgelegt am"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="unterzeichnet_am",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Unterzeichnet am (Rücklauf)"
            ),
        ),
    ]
