# Generated by Django 5.2.9 on 2026-07-15 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0022_sync_aktiv_mit_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="VertragMietzins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gueltig_ab", models.DateField(verbose_name="Gültig ab")),
                (
                    "netto_mietzins",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Netto-Mietzins",
                    ),
                ),
                (
                    "nebenkosten",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Nebenkosten",
                    ),
                ),
                ("notiz", models.CharField(blank=True, default="", max_length=200)),
                (
                    "vertrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mietzins_komponenten",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mietzins-Komponente",
                "db_table": "rentals_vertragmietzins",
                "ordering": ["gueltig_ab", "id"],
            },
        ),
    ]
