# Generated by Django 5.2.9 on 2026-07-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0023_vertragmietzins"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertragmietzins",
            name="rabatt_netto",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Rabatt Netto"
            ),
        ),
        migrations.AddField(
            model_name="vertragmietzins",
            name="rabatt_nk",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Rabatt NK"
            ),
        ),
        migrations.AlterField(
            model_name="vertragmietzins",
            name="nebenkosten",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Nebenkosten (Referenz)",
            ),
        ),
        migrations.AlterField(
            model_name="vertragmietzins",
            name="netto_mietzins",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Netto-Mietzins (Referenz)",
            ),
        ),
    ]
