# Generated by Django 5.2.9 on 2026-07-17 13:49

from django.db import migrations, models


def backfill_befristet(apps, schema_editor):
    """Alt-Verträge: ein AKTIVER Vertrag mit gesetztem Enddatum war bisher
    implizit befristet (die Auslauf-Pipeline las `ende IS NOT NULL`). Diese
    Semantik verlustfrei ins neue Flag überführen. Gekündigte/archivierte
    Verträge NICHT anfassen — deren `ende` ist der Kündigungstermin."""
    Mietvertrag = apps.get_model("rentals", "Mietvertrag")
    Mietvertrag.objects.filter(status="aktiv", ende__isnull=False).update(ist_befristet=True)


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0026_backfill_anpassung_sollmietzins"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="ist_befristet",
            field=models.BooleanField(
                default=False, verbose_name="Befristetes Mietverhältnis"
            ),
        ),
        migrations.RunPython(backfill_befristet, migrations.RunPython.noop),
    ]
