# Generated by Django 5.2.9 on 2026-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0024_mieter_betreibung_ergebnis_mieter_ebill_email_and_more"),
        ("rentals", "0027_mietvertrag_ist_befristet"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietvertrag",
            name="solidarhaftung",
            field=models.BooleanField(
                default=True, verbose_name="Solidarische Haftung aller Mieter"
            ),
        ),
        migrations.AddField(
            model_name="mietvertrag",
            name="weitere_mieter",
            field=models.ManyToManyField(
                blank=True,
                related_name="vertraege_als_weiterer_mieter",
                to="crm.mieter",
                verbose_name="Weitere Mieter (WG)",
            ),
        ),
    ]
