# Generated by Django 5.2.9 on 2026-07-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0026_verwaltung_nk_honorar_prozent"),
        ("portfolio", "0030_liegenschaft_anlagekosten_and_more"),
        ("rentals", "0028_mietvertrag_solidarhaftung_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mietvertrag",
            index=models.Index(fields=["status"], name="idx_mietvertrag_status"),
        ),
        migrations.AddIndex(
            model_name="mietvertrag",
            index=models.Index(fields=["aktiv"], name="idx_mietvertrag_aktiv"),
        ),
    ]
