# Generated by Django 5.2.9 on 2026-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0029_mietvertrag_idx_mietvertrag_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kuendigung",
            name="ende_vorher",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vertragsende vor Kündigung"
            ),
        ),
    ]
