# Generated by Django 5.2.9 on 2026-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0037_dokument_organisation_pflicht"),
    ]

    operations = [
        migrations.AddField(
            model_name="dokument",
            name="frist_pendenz_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dokument",
            name="zugang_pflichtig",
            field=models.BooleanField(
                default=False, verbose_name="Zugang nachzuweisen (Art. 257d)"
            ),
        ),
    ]
