# Generated by Django 5.2.9 on 2026-10-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0038_dokument_zugang"),
    ]

    operations = [
        migrations.AddField(
            model_name="abnahmemangel",
            name="vorsaetzlich",
            field=models.BooleanField(
                default=False,
                verbose_name="Absichtlich beschädigt (kein Zeitwertabzug)",
            ),
        ),
    ]
