# Generated by Django 5.2.9 on 2026-10-02 15:07

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0042_versicherung_selbstbehalt"),
        ("rentals", "0039_abnahmemangel_vorsaetzlich"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbnahmePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raum", models.CharField(max_length=60, verbose_name="Raum")),
                (
                    "bezeichnung",
                    models.CharField(max_length=120, verbose_name="Bauteil"),
                ),
                (
                    "zustand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Offen"),
                            ("io", "Neu i.O."),
                            ("normal", "Normale Abnutzung"),
                            ("uebermaessig", "Übermässige Abnutzung"),
                        ],
                        default="",
                        max_length=12,
                        verbose_name="Zustand",
                    ),
                ),
                (
                    "kommentar",
                    models.TextField(blank=True, default="", verbose_name="Kommentar"),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.get_smart_upload_path,
                        verbose_name="Foto",
                    ),
                ),
                (
                    "kostenschaetzung",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="Kostenschätzung CHF",
                    ),
                ),
                (
                    "vorsaetzlich",
                    models.BooleanField(
                        default=False, verbose_name="Absichtlich beschädigt"
                    ),
                ),
                ("sortierung", models.PositiveIntegerField(default=0)),
                (
                    "ausstattung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abnahme_positionen",
                        to="portfolio.ausstattung",
                    ),
                ),
                (
                    "mangel",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="position",
                        to="rentals.abnahmemangel",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "protokoll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="rentals.abnahmeprotokoll",
                    ),
                ),
            ],
            options={
                "db_table": "core_abnahmeposition",
                "ordering": ["sortierung", "id"],
            },
        ),
    ]
