# Generated by Django 5.2.9 on 2026-10-02 20:15

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("rentals", "0041_abnahme_einheit_vorgaenger"),
    ]

    operations = [
        migrations.AddField(
            model_name="abnahmeprotokoll",
            name="unterschrift_mieter_bild",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.utils.get_smart_upload_path,
                verbose_name="Unterschrift Mieter (Bild)",
            ),
        ),
        migrations.AddField(
            model_name="abnahmeprotokoll",
            name="unterschrift_verwalter_bild",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.utils.get_smart_upload_path,
                verbose_name="Unterschrift Verwaltung (Bild)",
            ),
        ),
        migrations.CreateModel(
            name="AbnahmeSchluessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(max_length=80, verbose_name="Schlüssel"),
                ),
                (
                    "anlage",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="Schliessanlage / Schlüsselnummer",
                    ),
                ),
                (
                    "soll",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Soll"),
                ),
                (
                    "ist",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ist"
                    ),
                ),
                ("sortierung", models.PositiveIntegerField(default=0)),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "protokoll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schluessel",
                        to="rentals.abnahmeprotokoll",
                    ),
                ),
            ],
            options={
                "db_table": "core_abnahmeschluessel",
                "ordering": ["sortierung", "id"],
            },
        ),
    ]
