# Generated by Django 5.2.9 on 2026-10-03 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("rentals", "0042_abnahme_schluessel_unterschrift"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbnahmeText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schluessel", models.CharField(max_length=20)),
                ("text", models.TextField(max_length=3000)),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abnahme_texte",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "core_abnahmetext",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "schluessel"),
                        name="uniq_abnahmetext_je_organisation",
                    )
                ],
            },
        ),
    ]
