# Generated by Django 5.2.9 on 2026-10-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0043_abnahmetext"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="kosten_prozent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Anteil Kostensteigerung (%)",
            ),
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="lik_prozent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Anteil Teuerung/LIK (%)",
            ),
        ),
        migrations.AddField(
            model_name="mietzinsanpassung",
            name="zins_prozent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Anteil Referenzzins (%)",
            ),
        ),
    ]
