from django.urls import path

from stweg import views as v
from stweg import views_dokumente as vd
from stweg import views_finanzen as vf
from stweg import views_inkasso as vi

urlpatterns = [
    path('', v.stweg_uebersicht, name='stweg_uebersicht'),
    path('<int:stweg_id>/', v.stweg_gemeinschaft, name='stweg_gemeinschaft'),
    path('<int:stweg_id>/versammlung/neu/', v.stweg_versammlung_neu, name='stweg_versammlung_neu'),
    path('<int:stweg_id>/anfrage/neu/', v.stweg_anfrage_neu, name='stweg_anfrage_neu'),
    path('<int:stweg_id>/aufgabe/neu/', v.stweg_aufgabe_neu, name='stweg_aufgabe_neu'),
    path('<int:stweg_id>/einheiten/', v.stweg_einheiten, name='stweg_einheiten'),
    path('<int:stweg_id>/einheiten/speichern/', v.stweg_einheiten_speichern, name='stweg_einheiten_speichern'),
    path('<int:stweg_id>/einheiten/neu/', v.stweg_einheit_neu, name='stweg_einheit_neu'),
    path('<int:stweg_id>/eigentuemer/neu/', v.stweg_eigentuemer_neu, name='stweg_eigentuemer_neu'),
    path('<int:stweg_id>/aktivieren/', v.stweg_aktivieren, name='stweg_aktivieren'),
    path('<int:stweg_id>/abrechnung/', v.stweg_abrechnung, name='stweg_abrechnung'),
    path('<int:stweg_id>/abrechnung/berechnen/', v.stweg_abrechnung_berechnen, name='stweg_abrechnung_berechnen'),
    path('<int:stweg_id>/akonto/neu/', v.stweg_akonto_neu, name='stweg_akonto_neu'),
    path('<int:stweg_id>/fonds/einlage/', v.stweg_fonds_einlage, name='stweg_fonds_einlage'),
    path('<int:stweg_id>/fonds/entnahme/', v.stweg_fonds_entnahme, name='stweg_fonds_entnahme'),
    path('abrechnung/<int:pk>/abschliessen/', v.stweg_abrechnung_abschliessen, name='stweg_abrechnung_abschliessen'),
    path('abrechnung/<int:pk>/pdf/', v.stweg_abrechnung_pdf, name='stweg_abrechnung_pdf'),
    path('akonto/<int:pk>/loeschen/', v.stweg_akonto_loeschen, name='stweg_akonto_loeschen'),
    path('versammlung/<int:pk>/', v.stweg_versammlung, name='stweg_versammlung'),
    path('versammlung/<int:pk>/evoting/', v.stweg_versammlung_evoting, name='stweg_versammlung_evoting'),
    path('versammlung/<int:pk>/traktandum/neu/', v.stweg_traktandum_neu, name='stweg_traktandum_neu'),
    path('versammlung/<int:pk>/einladung/', v.stweg_einladung_versenden, name='stweg_einladung_versenden'),
    path('versammlung/<int:pk>/durchfuehren/', v.stweg_durchfuehren, name='stweg_durchfuehren'),
    path('versammlung/<int:pk>/anwesenheit/', v.stweg_anwesenheit_speichern, name='stweg_anwesenheit_speichern'),
    path('versammlung/<int:pk>/protokoll/', v.stweg_protokoll_speichern, name='stweg_protokoll_speichern'),
    path('versammlung/<int:pk>/protokoll/versenden/', v.stweg_protokoll_versenden, name='stweg_protokoll_versenden'),
    path('versammlung/<int:pk>/pdf/<str:art>/', v.stweg_pdf, name='stweg_pdf'),
    path('versammlung/<int:pk>/vollmacht/neu/', v.stweg_vollmacht_neu, name='stweg_vollmacht_neu'),
    path('<int:stweg_id>/zirkular/neu/', v.stweg_zirkular_neu, name='stweg_zirkular_neu'),
    path('zirkular/<int:pk>/', v.stweg_zirkular, name='stweg_zirkular'),
    path('zirkular/<int:pk>/versenden/', v.stweg_zirkular_versenden, name='stweg_zirkular_versenden'),
    path('zirkular/<int:pk>/stimmen/', v.stweg_zirkular_stimmen, name='stweg_zirkular_stimmen'),
    path('zirkular/<int:pk>/feststellen/', v.stweg_zirkular_feststellen, name='stweg_zirkular_feststellen'),
    path('zirkular/<int:pk>/ergebnis/', v.stweg_zirkular_ergebnis, name='stweg_zirkular_ergebnis'),
    path('zirkular/<int:pk>/pdf/', v.stweg_zirkular_pdf, name='stweg_zirkular_pdf'),
    path('vollmacht/<int:pk>/dokument/', v.stweg_vollmacht_dokument, name='stweg_vollmacht_dokument'),
    path('vollmacht/<int:pk>/datei/', v.stweg_vollmacht_datei, name='stweg_vollmacht_datei'),
    path('vollmacht/<int:pk>/widerrufen/', v.stweg_vollmacht_widerrufen, name='stweg_vollmacht_widerrufen'),
    path('traktandum/<int:pk>/loeschen/', v.stweg_traktandum_loeschen, name='stweg_traktandum_loeschen'),
    path('traktandum/<int:pk>/stimmen/', v.stweg_stimmen_speichern, name='stweg_stimmen_speichern'),
    path('traktandum/<int:pk>/feststellen/', v.stweg_beschluss_feststellen, name='stweg_beschluss_feststellen'),
    path('anfrage/<int:pk>/beantworten/', v.stweg_anfrage_beantworten, name='stweg_anfrage_beantworten'),
    path('anfrage/<int:pk>/erledigt/', v.stweg_anfrage_erledigt, name='stweg_anfrage_erledigt'),
    path('aufgabe/<int:pk>/erledigt/', v.stweg_aufgabe_erledigt, name='stweg_aufgabe_erledigt'),
    path('<int:stweg_id>/vorgaben/', v.stweg_vorgaben, name='stweg_vorgaben'),
    path('<int:stweg_id>/vorgaben/speichern/', v.stweg_vorgaben_speichern, name='stweg_vorgaben_speichern'),
    # Verteilschlüssel und Budget
    path('<int:stweg_id>/schluessel/', vf.stweg_schluessel, name='stweg_schluessel'),
    path('<int:stweg_id>/schluessel/neu/', vf.stweg_schluessel_neu, name='stweg_schluessel_neu'),
    path('<int:stweg_id>/kostenart/', vf.stweg_kostenart_zuordnen, name='stweg_kostenart_zuordnen'),
    path('schluessel/<int:pk>/anteile/', vf.stweg_schluessel_anteile, name='stweg_schluessel_anteile'),
    path('schluessel/<int:pk>/loeschen/', vf.stweg_schluessel_loeschen, name='stweg_schluessel_loeschen'),
    path('<int:stweg_id>/budget/', vf.stweg_budget, name='stweg_budget'),
    path('<int:stweg_id>/budget/neu/', vf.stweg_budget_neu, name='stweg_budget_neu'),
    path('budget/<int:pk>/', vf.stweg_budget_detail, name='stweg_budget_detail'),
    path('budget/<int:pk>/position/neu/', vf.stweg_budget_position_neu, name='stweg_budget_position_neu'),
    path('budget/<int:pk>/position/loeschen/', vf.stweg_budget_position_loeschen, name='stweg_budget_position_loeschen'),
    path('budget/<int:pk>/vorlegen/', vf.stweg_budget_vorlegen, name='stweg_budget_vorlegen'),
    path('budget/<int:pk>/traktandum/', vf.stweg_budget_traktandum, name='stweg_budget_traktandum'),
    path('budget/<int:pk>/versenden/', vf.stweg_budget_versenden, name='stweg_budget_versenden'),
    path('budget/<int:pk>/pdf/', vf.stweg_budget_pdf, name='stweg_budget_pdf'),
    # Dokumenten-Repository
    path('<int:stweg_id>/dokumente/', vd.stweg_dokumente, name='stweg_dokumente'),
    path('<int:stweg_id>/dokumente/neu/', vd.stweg_dokument_neu, name='stweg_dokument_neu'),
    path('dokument/<int:pk>/', vd.stweg_dokument_download, name='stweg_dokument_download'),
    path('dokument/<int:pk>/loeschen/', vd.stweg_dokument_loeschen, name='stweg_dokument_loeschen'),
    path('dokument/<int:pk>/sichtbar/', vd.stweg_dokument_sichtbar, name='stweg_dokument_sichtbar'),
    # Inkasso (Retentionsrecht, Gemeinschaftspfandrecht)
    path('<int:stweg_id>/inkasso/', vi.stweg_inkasso, name='stweg_inkasso'),
    path('<int:stweg_id>/inkasso/mahnen/', vi.stweg_inkasso_mahnen, name='stweg_inkasso_mahnen'),
    path('<int:stweg_id>/inkasso/retention/', vi.stweg_inkasso_retention, name='stweg_inkasso_retention'),
    path('<int:stweg_id>/inkasso/pfandrecht/', vi.stweg_inkasso_pfandrecht, name='stweg_inkasso_pfandrecht'),
    path('mahnung/<int:pk>/pdf/', vi.stweg_mahnung_pdf, name='stweg_mahnung_pdf'),
    path('pfandrecht/<int:pk>/pdf/', vi.stweg_pfandrecht_pdf, name='stweg_pfandrecht_pdf'),
    path('pfandrecht/<int:pk>/eingetragen/', vi.stweg_pfandrecht_eingetragen, name='stweg_pfandrecht_eingetragen'),
    path('inkassofall/<int:pk>/pdf/', vi.stweg_inkassofall_pdf, name='stweg_inkassofall_pdf'),
]
