# Generated by Django 5.2.9 on 2026-05-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolio", "0013_einheit_standard_kautionsmonate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mietbewerbung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("neu", "Neu eingegangen"),
                            ("geprueft", "Bonität geprüft"),
                            ("zugesagt", "Zusage erteilt"),
                            ("abgelehnt", "Abgelehnt"),
                        ],
                        default="neu",
                        max_length=20,
                    ),
                ),
                ("vorname", models.CharField(max_length=100)),
                ("nachname", models.CharField(max_length=100)),
                ("geburtsdatum", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("telefon", models.CharField(max_length=50)),
                ("beruf", models.CharField(max_length=150)),
                ("arbeitgeber", models.CharField(max_length=150)),
                (
                    "einkommen_jahr",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bruttojahreseinkommen",
                        max_digits=12,
                    ),
                ),
                (
                    "aktueller_vermieter",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("grund_fuer_wechsel", models.TextField(blank=True, null=True)),
                ("anzahl_personen", models.IntegerField(default=1)),
                ("haustiere", models.BooleanField(default=False)),
                (
                    "haustiere_details",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("musikinstrumente", models.BooleanField(default=False)),
                (
                    "wunsch_kautions_typ",
                    models.CharField(
                        choices=[
                            ("bank", "Bankdepot (3 Monatsmieten)"),
                            ("swisskaution", "Swisskaution (Kautionsversicherung)"),
                        ],
                        default="bank",
                        max_length=20,
                    ),
                ),
                (
                    "schild_briefkasten",
                    models.CharField(
                        help_text="Gewünschter Name auf dem Briefkasten", max_length=150
                    ),
                ),
                (
                    "schild_sonnerie",
                    models.CharField(
                        help_text="Gewünschter Name auf der Klingel", max_length=150
                    ),
                ),
                (
                    "betreibungsauszug",
                    models.FileField(
                        blank=True, null=True, upload_to="bewerbungen/betreibung/"
                    ),
                ),
                (
                    "ausweiskopie",
                    models.FileField(
                        blank=True, null=True, upload_to="bewerbungen/ausweis/"
                    ),
                ),
                (
                    "lohnausweis",
                    models.FileField(
                        blank=True, null=True, upload_to="bewerbungen/lohn/"
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bewerbungen",
                        to="portfolio.einheit",
                    ),
                ),
            ],
        ),
    ]
