# Generated by Django 5.2.9 on 2026-05-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mietprozess", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mietbewerbung",
            name="digitaler_betreibungsauszug",
            field=models.BooleanField(
                default=False, help_text="Wird via API eingeholt"
            ),
        ),
    ]
