# Generated by Django 5.2.9 on 2026-05-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mietprozess", "0002_mietbewerbung_digitaler_betreibungsauszug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mietbewerbung",
            old_name="anzahl_personen",
            new_name="anzahl_erwachsene",
        ),
        migrations.RenameField(
            model_name="mietbewerbung",
            old_name="telefon",
            new_name="mobilnummer",
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="adresse",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="angestellt_seit",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="anzahl_kinder",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="bemerkungen",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="email_arbeitgeber",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="email_vermieter",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="erwerbsstatus",
            field=models.CharField(
                choices=[
                    ("angestellt", "Angestellt"),
                    ("selbstaendig", "Selbständig"),
                    ("student", "Student"),
                    ("keine_erwerbstaetigkeit", "Keine Erwerbstätigkeit"),
                    ("arbeitslos", "Arbeitslos"),
                    ("pensioniert", "Pensioniert"),
                    ("iv_bezueger", "IV Bezüger"),
                ],
                default="angestellt",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="geschlecht",
            field=models.CharField(
                choices=[("weiblich", "Weiblich"), ("maennlich", "Männlich")],
                default="weiblich",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="gewuenschter_bezugstermin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="hat_betreibungen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="heimatort",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="interesse_parkplatz",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="ist_unbefristet",
            field=models.BooleanField(
                default=True, help_text="Ist die Anstellung unbefristet?"
            ),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="kontaktperson_arbeitgeber",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="kontaktperson_vermieter",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="musikinstrumente_details",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="nationalitaet",
            field=models.CharField(default="Schweiz", max_length=100),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="ort",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="plz",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="telefon_arbeitgeber",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="telefon_vermieter",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="weitere_dokumente",
            field=models.FileField(
                blank=True, null=True, upload_to="bewerbungen/weitere/"
            ),
        ),
        migrations.AddField(
            model_name="mietbewerbung",
            name="zivilstand",
            field=models.CharField(
                choices=[
                    ("ledig", "Ledig"),
                    ("verheiratet", "Verheiratet"),
                    ("eingetragene_partnerschaft", "Eingetragene Partnerschaft"),
                    ("geschieden", "Geschieden"),
                    ("verwitwet", "Verwitwet"),
                    ("getrennt", "Getrennt"),
                ],
                default="ledig",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="mietbewerbung",
            name="arbeitgeber",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="mietbewerbung",
            name="einkommen_jahr",
            field=models.CharField(
                help_text="Einkommensspanne (Flatfox-Style)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="mietbewerbung",
            name="schild_briefkasten",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="mietbewerbung",
            name="schild_sonnerie",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
