# Generated by Django 5.2.9 on 2026-07-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mietprozess",
            "0003_rename_anzahl_personen_mietbewerbung_anzahl_erwachsene_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mietbewerbung",
            name="besichtigung_am",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Besichtigungstermin"
            ),
        ),
        migrations.AlterField(
            model_name="mietbewerbung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu eingegangen"),
                    ("geprueft", "Bonität geprüft"),
                    ("besichtigung", "Zur Besichtigung eingeladen"),
                    ("zugesagt", "Zusage erteilt"),
                    ("abgelehnt", "Abgelehnt"),
                ],
                default="neu",
                max_length=20,
            ),
        ),
    ]
