# Generated by Django 5.2.9 on 2026-08-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mietprozess", "0004_mietbewerbung_besichtigung_am_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mietbewerbung",
            name="zivilstand",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ledig", "Ledig"),
                    ("verheiratet", "Verheiratet"),
                    ("eingetragene_partnerschaft", "Eingetragene Partnerschaft"),
                    ("geschieden", "Geschieden"),
                    ("verwitwet", "Verwitwet"),
                    ("getrennt", "Getrennt"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
