# Generated by Django 5.2.9 on 2026-03-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Handwerker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firma", models.CharField(max_length=100)),
                ("gewerk", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefon", models.CharField(blank=True, max_length=30)),
                ("iban", models.CharField(blank=True, max_length=34)),
            ],
            options={
                "verbose_name": "Handwerker",
                "verbose_name_plural": "Handwerker",
                "db_table": "core_handwerker",
            },
        ),
        migrations.CreateModel(
            name="Mandant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firma_oder_name",
                    models.CharField(
                        max_length=100, verbose_name="Name / Firma (Eigentümer)"
                    ),
                ),
                (
                    "strasse",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Strasse"
                    ),
                ),
                (
                    "plz",
                    models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
                ),
                (
                    "ort",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
                (
                    "unterschrift_bild",
                    models.ImageField(
                        blank=True, null=True, upload_to="unterschriften/"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bankname (Mandant)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandant (Eigentümer)",
                "verbose_name_plural": "Mandanten (Eigentümer)",
                "db_table": "core_mandant",
            },
        ),
        migrations.CreateModel(
            name="Mieter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anrede", models.CharField(default="Herr", max_length=20)),
                ("vorname", models.CharField(max_length=100)),
                ("nachname", models.CharField(max_length=100)),
                ("telefon", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("strasse", models.CharField(blank=True, max_length=200)),
                ("plz", models.CharField(blank=True, max_length=10)),
                ("ort", models.CharField(blank=True, max_length=100)),
                ("geburtsdatum", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Mieter",
                "verbose_name_plural": "Mieter",
                "db_table": "core_mieter",
            },
        ),
        migrations.CreateModel(
            name="Verwaltung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firma", models.CharField(max_length=100, verbose_name="Firmenname")),
                (
                    "strasse",
                    models.CharField(max_length=100, verbose_name="Strasse & Nr."),
                ),
                ("plz", models.CharField(max_length=10, verbose_name="PLZ")),
                ("ort", models.CharField(max_length=100, verbose_name="Ort")),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=30, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-Mail"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "aktueller_referenzzinssatz",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.75,
                        max_digits=4,
                        verbose_name="Aktueller Ref.Zins",
                    ),
                ),
                (
                    "aktueller_lik_punkte",
                    models.DecimalField(
                        decimal_places=1,
                        default=107.1,
                        max_digits=6,
                        verbose_name="Aktueller LIK",
                    ),
                ),
                (
                    "letztes_update_marktdaten",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Meine Verwaltung",
                "verbose_name_plural": "Meine Verwaltung",
                "db_table": "core_verwaltung",
            },
        ),
    ]
