# Generated by Django 5.2.9 on 2026-04-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mieter",
            name="firma",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Firmenname"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="is_company",
            field=models.BooleanField(default=False, verbose_name="Ist eine Firma?"),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="anrede",
            field=models.CharField(
                blank=True, default="Herr", max_length=20, verbose_name="Anrede"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="nachname",
            field=models.CharField(blank=True, max_length=100, verbose_name="Nachname"),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="vorname",
            field=models.CharField(blank=True, max_length=100, verbose_name="Vorname"),
        ),
    ]
