# Generated by Django 5.2.9 on 2026-04-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="handwerker",
            name="kontaktperson",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Kontaktperson"
            ),
        ),
        migrations.AddField(
            model_name="handwerker",
            name="notizen",
            field=models.TextField(blank=True, verbose_name="Interne Notizen"),
        ),
        migrations.AddField(
            model_name="handwerker",
            name="ort",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ort"),
        ),
        migrations.AddField(
            model_name="handwerker",
            name="plz",
            field=models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
        ),
        migrations.AddField(
            model_name="handwerker",
            name="strasse",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Strasse & Nr."
            ),
        ),
        migrations.AddField(
            model_name="mandant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-Mail"),
        ),
        migrations.AddField(
            model_name="mandant",
            name="iban",
            field=models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
        ),
        migrations.AddField(
            model_name="mandant",
            name="kontaktperson",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Kontaktperson"
            ),
        ),
        migrations.AddField(
            model_name="mandant",
            name="telefon",
            field=models.CharField(blank=True, max_length=30, verbose_name="Telefon"),
        ),
        migrations.AddField(
            model_name="mieter",
            name="adresszusatz",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Adresszusatz (z.B. c/o)"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="ahv_nummer",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="AHV-Nummer"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="nationalitaet",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Nationalität"
            ),
        ),
        migrations.AddField(
            model_name="verwaltung",
            name="iban",
            field=models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-Mail"),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="firma",
            field=models.CharField(max_length=100, verbose_name="Firma"),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="gewerk",
            field=models.CharField(
                max_length=100, verbose_name="Gewerk (z.B. Sanitär, Elektro)"
            ),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="iban",
            field=models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="telefon",
            field=models.CharField(blank=True, max_length=30, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="mandant",
            name="strasse",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Strasse & Nr."
            ),
        ),
        migrations.AlterField(
            model_name="mandant",
            name="unterschrift_bild",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="unterschriften/",
                verbose_name="Digitale Unterschrift",
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="anrede",
            field=models.CharField(
                default="Herr", max_length=20, verbose_name="Anrede"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-Mail"),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="geburtsdatum",
            field=models.DateField(blank=True, null=True, verbose_name="Geburtsdatum"),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="nachname",
            field=models.CharField(max_length=100, verbose_name="Nachname"),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="ort",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ort"),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="plz",
            field=models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="strasse",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Strasse & Nr."
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="telefon",
            field=models.CharField(blank=True, max_length=30, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="vorname",
            field=models.CharField(max_length=100, verbose_name="Vorname"),
        ),
        migrations.AlterField(
            model_name="verwaltung",
            name="letztes_update_marktdaten",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Letztes Update Marktdaten"
            ),
        ),
        migrations.AlterField(
            model_name="verwaltung",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="Firmenlogo"
            ),
        ),
    ]
