# Generated by Django 5.2.9 on 2026-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_mieter_firma_mieter_is_company_alter_mieter_anrede_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verwaltung",
            name="unterschrift_bild",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="unterschriften/",
                verbose_name="Digitale Unterschrift",
            ),
        ),
    ]
