# Generated by Django 5.2.9 on 2026-04-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_verwaltung_unterschrift_bild"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mieter",
            name="firma",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="is_company",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="telefon",
        ),
        migrations.AddField(
            model_name="mieter",
            name="bank_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Bank"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="bonitaet_datum",
            field=models.DateField(
                blank=True, null=True, verbose_name="Betreibungsauszug vom"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="firmen_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Firmenname"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="iban",
            field=models.CharField(
                blank=True, default="", max_length=34, verbose_name="IBAN"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="kontaktperson",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Kontaktperson"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="land",
            field=models.CharField(
                default="Schweiz", max_length=50, verbose_name="Land"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="mobile",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Mobile"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="notizen",
            field=models.TextField(
                blank=True, default="", verbose_name="Interne Notizen"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="postfach",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Postfach"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="sprache",
            field=models.CharField(
                choices=[
                    ("de", "Deutsch"),
                    ("fr", "Französisch"),
                    ("it", "Italienisch"),
                    ("en", "Englisch"),
                ],
                default="de",
                max_length=2,
                verbose_name="Korrespondenzsprache",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="telefon_geschaeft",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Telefon Geschäft"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="telefon_privat",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Telefon Privat"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="typ",
            field=models.CharField(
                choices=[
                    ("person", "Privatperson"),
                    ("firma", "Firma / Unternehmen"),
                    ("verein", "Verein / Stiftung"),
                ],
                default="person",
                max_length=20,
                verbose_name="Kunden-Typ",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="uid_nummer",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="UID / CHE-Nummer"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="zivilstand",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Zivilstand"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="adresszusatz",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Adresszusatz"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="ahv_nummer",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="AHV-Nummer"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="E-Mail"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="nachname",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Nachname"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="nationalitaet",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Nationalität"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="ort",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Ort"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="plz",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="PLZ"
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="strasse",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Strasse & Nr."
            ),
        ),
        migrations.AlterField(
            model_name="mieter",
            name="vorname",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Vorname"
            ),
        ),
    ]
