# Generated by Django 5.2.9 on 2026-05-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_remove_mieter_firma_remove_mieter_is_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mieter",
            name="arbeitgeber",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Arbeitgeber"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="beruf",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Beruf"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="einkommen_jahr",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Jahreseinkommen"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="erwerbsstatus",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Erwerbsstatus"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="heimatort",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Heimatort"
            ),
        ),
    ]
