# Generated by Django 5.2.9 on 2026-05-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_mieter_arbeitgeber_mieter_beruf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mieter",
            name="zukuenftig_ab",
            field=models.DateField(
                blank=True, null=True, verbose_name="Gültig ab (Einzug)"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="zukuenftige_plz",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Zukünftige PLZ"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="zukuenftige_strasse",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Zukünftige Strasse",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="zukuenftiger_ort",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Zukünftiger Ort"
            ),
        ),
    ]
