# Generated by Django 5.2.9 on 2026-05-21 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_mieter_zukuenftig_ab_mieter_zukuenftige_plz_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="handwerker",
            options={
                "ordering": ["firma"],
                "verbose_name": "Handwerker",
                "verbose_name_plural": "Handwerkerstamm",
            },
        ),
        migrations.RemoveField(
            model_name="handwerker",
            name="gewerk",
        ),
        migrations.RemoveField(
            model_name="handwerker",
            name="iban",
        ),
        migrations.RemoveField(
            model_name="handwerker",
            name="notizen",
        ),
        migrations.RemoveField(
            model_name="handwerker",
            name="ort",
        ),
        migrations.RemoveField(
            model_name="handwerker",
            name="plz",
        ),
        migrations.RemoveField(
            model_name="handwerker",
            name="strasse",
        ),
        migrations.AddField(
            model_name="handwerker",
            name="branche",
            field=models.CharField(
                choices=[
                    ("sanitaer", "Sanitär / Heizung"),
                    ("elektro", "Elektroinstallation"),
                    ("maler", "Maler / Gipser"),
                    ("schreiner", "Schreiner / Zimmermann"),
                    ("schloss", "Schlosserei / Schlüsseldienst"),
                    ("allgemein", "Allround-Handwerker / Baugeschäft"),
                    ("garten", "Gartenbau / Umgebung"),
                    ("reinigung", "Reinigungsinstitut"),
                ],
                default="allgemein",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="handwerker",
            name="erstellt_am",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 5, 21, 12, 19, 38, 439186, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="E-Mail für Aufträge",
            ),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="firma",
            field=models.CharField(max_length=255, verbose_name="Firmenname"),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="kontaktperson",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Kontaktperson"
            ),
        ),
        migrations.AlterField(
            model_name="handwerker",
            name="telefon",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telefonnummer"
            ),
        ),
    ]
