# Generated by Django 5.2.9 on 2026-07-07 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_alter_handwerker_options_remove_handwerker_gewerk_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mandant",
            name="benutzer",
            field=models.OneToOneField(
                blank=True,
                help_text="Optionaler Benutzer-Account für das Eigentümer-Portal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mandant_profil",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Portal-Login",
            ),
        ),
    ]
