# Generated by Django 5.2.9 on 2026-07-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_mandant_benutzer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vorlage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Bezeichnung")),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("brief", "Brief / Anschreiben"),
                            ("kuendigung", "Kündigung"),
                            ("mahnung", "Mahnung"),
                            ("info", "Information / Rundschreiben"),
                            ("protokoll", "Protokoll"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        default="brief",
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "betreff",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Betreff"
                    ),
                ),
                (
                    "inhalt",
                    models.TextField(blank=True, default="", verbose_name="Inhalt"),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vorlage",
                "verbose_name_plural": "Vorlagen",
                "db_table": "core_vorlage",
                "ordering": ["kategorie", "name"],
            },
        ),
    ]
