# Generated by Django 5.2.9 on 2026-07-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_vorlage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vorlage",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("brief", "Brief / Anschreiben"),
                    ("kuendigung", "Kündigung"),
                    ("mahnung", "Mahnung"),
                    ("info", "Information / Rundschreiben"),
                    ("protokoll", "Protokoll"),
                    ("ticket_eingang", "Schaden – Eingangsbestätigung"),
                    ("ticket_handwerker", "Schaden – Auftrag an Handwerker"),
                    ("ticket_melder", "Schaden – Info an Melder"),
                    ("ticket_erledigt", "Schaden – Erledigt-Meldung"),
                    ("sonstiges", "Sonstiges"),
                ],
                default="brief",
                max_length=20,
                verbose_name="Kategorie",
            ),
        ),
    ]
