# Generated by Django 5.2.9 on 2026-07-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_alter_vorlage_kategorie"),
    ]

    operations = [
        migrations.AddField(
            model_name="verwaltung",
            name="buchung_gesperrt_bis",
            field=models.DateField(
                blank=True, null=True, verbose_name="Buchungen gesperrt bis"
            ),
        ),
    ]
