# Generated by Django 5.2.9 on 2026-07-08 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_verwaltung_buchung_gesperrt_bis"),
        ("portfolio", "0014_liegenschaft_hkvo_aktiv_and_more"),
        ("rentals", "0014_abnahmeprotokoll_abnahmemangel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kommunikation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("telefon", "Telefon"),
                            ("email", "E-Mail"),
                            ("brief", "Brief"),
                            ("notiz", "Notiz"),
                            ("persoenlich", "Persönlich"),
                        ],
                        default="telefon",
                        max_length=15,
                        verbose_name="Kanal",
                    ),
                ),
                (
                    "richtung",
                    models.CharField(
                        choices=[
                            ("eingehend", "Eingehend"),
                            ("ausgehend", "Ausgehend"),
                            ("intern", "Intern"),
                        ],
                        default="eingehend",
                        max_length=12,
                        verbose_name="Richtung",
                    ),
                ),
                (
                    "zeitpunkt",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Zeitpunkt"
                    ),
                ),
                (
                    "betreff",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Betreff"
                    ),
                ),
                ("inhalt", models.TextField(verbose_name="Inhalt / Notiz")),
                (
                    "erledigt",
                    models.BooleanField(default=True, verbose_name="Erledigt"),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "mieter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kommunikationen",
                        to="crm.mieter",
                    ),
                ),
                (
                    "vertrag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kommunikationen",
                        to="rentals.mietvertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kommunikation",
                "verbose_name_plural": "Kommunikationsjournal",
                "db_table": "core_kommunikation",
                "ordering": ["-zeitpunkt", "-id"],
            },
        ),
    ]
