# Generated by Django 5.2.9 on 2026-07-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_kommunikation"),
    ]

    operations = [
        migrations.AddField(
            model_name="verwaltung",
            name="mwst_methode",
            field=models.CharField(
                choices=[
                    ("effektiv", "Effektive Methode"),
                    ("saldo", "Saldosteuersatz"),
                ],
                default="effektiv",
                max_length=10,
                verbose_name="MWST-Methode",
            ),
        ),
        migrations.AddField(
            model_name="verwaltung",
            name="mwst_uid",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="MWST-Nummer (CHE)"
            ),
        ),
        migrations.AddField(
            model_name="verwaltung",
            name="saldosteuersatz",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=4,
                verbose_name="Saldosteuersatz (%)",
            ),
        ),
    ]
