# Generated by Django 5.2.9 on 2026-07-08 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_verwaltung_mwst_methode_verwaltung_mwst_uid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mieter",
            name="benutzer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mieter_profil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
