# Generated by Django 5.2.9 on 2026-07-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_mieter_benutzer"),
    ]

    operations = [
        migrations.AddField(
            model_name="verwaltung",
            name="aktueller_lik_stand",
            field=models.DateField(
                blank=True, null=True, verbose_name="LIK Stand-Monat"
            ),
        ),
        migrations.AddField(
            model_name="verwaltung",
            name="lik_basis",
            field=models.CharField(
                default="Dezember 2020", max_length=40, verbose_name="LIK-Basis"
            ),
        ),
    ]
