# Generated by Django 5.2.9 on 2026-07-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_verwaltung_aktueller_lik_stand_verwaltung_lik_basis"),
    ]

    operations = [
        migrations.AddField(
            model_name="verwaltung",
            name="abo_jaehrlich",
            field=models.BooleanField(
                default=False, verbose_name="Jährliche Abrechnung"
            ),
        ),
        migrations.AddField(
            model_name="verwaltung",
            name="abo_plan",
            field=models.CharField(
                choices=[("start", "Start"), ("pro", "Pro"), ("premium", "Premium")],
                default="pro",
                max_length=10,
                verbose_name="Abo-Plan",
            ),
        ),
    ]
