# Generated by Django 5.2.9 on 2026-07-12 11:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_verwaltung_abo_jaehrlich_verwaltung_abo_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandant",
            name="honorar_prozent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Verwaltungshonorar (%)",
            ),
        ),
    ]
