# Generated by Django 5.2.9 on 2026-07-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0018_alter_vorlage_kategorie"),
    ]

    operations = [
        migrations.AddField(
            model_name="verwaltung",
            name="portal_feed_token",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Portal-Feed-Token"
            ),
        ),
    ]
