# Generated by Django 5.2.9 on 2026-07-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0019_verwaltung_portal_feed_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="mieter",
            name="anonymisiert",
            field=models.BooleanField(default=False, verbose_name="DSG-anonymisiert"),
        ),
        migrations.AddField(
            model_name="mieter",
            name="anonymisiert_am",
            field=models.DateField(
                blank=True, null=True, verbose_name="Anonymisiert am"
            ),
        ),
    ]
