# Generated by Django 5.2.9 on 2026-07-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0020_mieter_anonymisiert_mieter_anonymisiert_am"),
    ]

    operations = [
        migrations.AddField(
            model_name="mieter",
            name="aufenthaltsbewilligung",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("schweizer", "Schweizer Bürger/in"),
                    ("C", "Niederlassung C"),
                    ("B", "Aufenthalt B"),
                    ("L", "Kurzaufenthalt L"),
                    ("G", "Grenzgänger G"),
                    ("Ci", "Ci (Aufenthalt mit Erwerb)"),
                    ("F", "Vorläufig aufgenommen F"),
                    ("N", "Asylsuchend N"),
                    ("andere", "Andere"),
                ],
                default="",
                max_length=20,
                verbose_name="Aufenthaltsbewilligung",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="bewilligung_gueltig_bis",
            field=models.DateField(
                blank=True, null=True, verbose_name="Bewilligung gültig bis"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="haftpflicht_gesellschaft",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="Haftpflicht-Versicherung",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="haftpflicht_police",
            field=models.CharField(
                blank=True, default="", max_length=60, verbose_name="Policen-Nr."
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="haushalt_erwachsene",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Erwachsene im Haushalt"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="haushalt_kinder",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Kinder im Haushalt"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="haustiere",
            field=models.BooleanField(default=False, verbose_name="Haustiere"),
        ),
        migrations.AddField(
            model_name="mieter",
            name="haustiere_details",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Haustiere (Details)",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="notfall_beziehung",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Beziehung"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="notfall_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Notfallkontakt / Bürge",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="notfall_telefon",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Notfall-Telefon"
            ),
        ),
    ]
