# Generated by Django 5.2.9 on 2026-07-17 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0021_mieter_aufenthaltsbewilligung_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MieterAdresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("wohn", "Wohnadresse"),
                            ("korrespondenz", "Korrespondenzadresse"),
                        ],
                        default="wohn",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                ("gueltig_ab", models.DateField(verbose_name="Gültig ab")),
                (
                    "strasse",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Strasse & Nr.",
                    ),
                ),
                (
                    "adresszusatz",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Adresszusatz",
                    ),
                ),
                (
                    "plz",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="PLZ"
                    ),
                ),
                (
                    "ort",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Ort"
                    ),
                ),
                (
                    "land",
                    models.CharField(
                        blank=True,
                        default="Schweiz",
                        max_length=50,
                        verbose_name="Land",
                    ),
                ),
                (
                    "quelle",
                    models.CharField(
                        blank=True,
                        default="manuell",
                        max_length=50,
                        verbose_name="Quelle",
                    ),
                ),
                (
                    "notiz",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Bemerkung"
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "mieter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adressen",
                        to="crm.mieter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mieter-Adresse",
                "verbose_name_plural": "Mieter-Adressen",
                "db_table": "core_mieteradresse",
                "ordering": ["-gueltig_ab", "-id"],
            },
        ),
    ]
