# Generated by Django 5.2.9 on 2026-07-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0023_backfill_mieteradresse"),
    ]

    operations = [
        migrations.AddField(
            model_name="mieter",
            name="betreibung_ergebnis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("keine", "Keine Betreibungen"),
                    ("offen", "Offene Betreibungen"),
                    ("verlustscheine", "Verlustscheine vorhanden"),
                ],
                default="",
                max_length=20,
                verbose_name="Betreibungsauszug-Ergebnis",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="ebill_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="eBill-/E-Rechnungs-Adresse",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="mahnsperre",
            field=models.BooleanField(
                default=False, verbose_name="Mahnsperre (Zahlungsvereinbarung)"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="ref_vermieter_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="Vorvermieter E-Mail",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="ref_vermieter_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Referenz Vorvermieter",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="ref_vermieter_telefon",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Vorvermieter Telefon",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="vertretung_art",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("bevollmaechtigt", "Bevollmächtigte Person"),
                    ("beistand", "Beistand (Erwachsenenschutz)"),
                    ("kesb", "KESB"),
                    ("erbengemeinschaft", "Erbengemeinschaft / Willensvollstrecker"),
                ],
                default="",
                max_length=30,
                verbose_name="Vertretung",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="vertretung_kontakt",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Vertretung Kontakt",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="vertretung_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Vertretung Name/Behörde",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="zahler_adresse",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Zahler-Adresse"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="zahler_iban",
            field=models.CharField(
                blank=True, default="", max_length=34, verbose_name="Zahler-IBAN"
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="zahler_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Abweichender Zahler",
            ),
        ),
        migrations.AddField(
            model_name="mieter",
            name="zahlungsart",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("dauerauftrag", "Dauerauftrag"),
                    ("qr", "QR-Einzahlung"),
                    ("lsv", "LSV / CH-DD-Lastschrift"),
                    ("ebill", "eBill"),
                ],
                default="",
                max_length=20,
                verbose_name="Zahlungsart",
            ),
        ),
    ]
