# Generated by Django 5.2.9 on 2026-07-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0024_mieter_betreibung_ergebnis_mieter_ebill_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mieter",
            name="zukuenftig_ab",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="zukuenftige_plz",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="zukuenftige_strasse",
        ),
        migrations.RemoveField(
            model_name="mieter",
            name="zukuenftiger_ort",
        ),
    ]
