# Generated by Django 5.2.9 on 2026-07-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0025_remove_mieter_zukuenftig_ab_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verwaltung",
            name="nk_honorar_prozent",
            field=models.DecimalField(
                decimal_places=2,
                default=3.0,
                max_digits=4,
                verbose_name="NK-Verwaltungshonorar (%)",
            ),
        ),
    ]
