# Generated by Django 5.2.9 on 2026-08-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0026_verwaltung_nk_honorar_prozent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verwaltung",
            name="aktueller_referenzzinssatz",
            field=models.DecimalField(
                decimal_places=2,
                default=1.25,
                max_digits=4,
                verbose_name="Aktueller Ref.Zins",
            ),
        ),
    ]
