# Generated by Django 5.2.9 on 2026-08-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0027_alter_verwaltung_aktueller_referenzzinssatz"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandant",
            name="mahn_konfig",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Mahnstufen-Konfiguration",
            ),
        ),
    ]
