# Generated by Django 5.2.9 on 2026-08-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0029_mandant_zu_eigentuemer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eigentuemer",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Bankname (Eigentümer)"
            ),
        ),
    ]
