# Generated by Django 5.2.9 on 2026-08-15 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0030_alter_eigentuemer_bank_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eigentuemer",
            name="benutzer",
            field=models.OneToOneField(
                blank=True,
                help_text="Optionaler Benutzer-Account für das Eigentümer-Portal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eigentuemer_profil",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Portal-Login",
            ),
        ),
    ]
