# Generated by Django 5.2.9 on 2026-08-15 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0032_verwaltung_zu_organisation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mitgliedschaft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rolle",
                    models.CharField(
                        choices=[
                            ("Verwaltung", "Verwaltung"),
                            ("Sachbearbeitung", "Sachbearbeitung"),
                            ("Lesend", "Lesend"),
                        ],
                        default="Sachbearbeitung",
                        max_length=20,
                        verbose_name="Rolle",
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(auto_now_add=True, verbose_name="Angelegt am"),
                ),
                (
                    "benutzer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitgliedschaften",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitgliedschaften",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitgliedschaft",
                "verbose_name_plural": "Mitgliedschaften",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("benutzer", "organisation"),
                        name="eine_mitgliedschaft_je_benutzer_und_organisation",
                    )
                ],
            },
        ),
    ]
