# Generated by Django 5.2.9 on 2026-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0039_organisation_pflicht"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="zweifaktor_pflicht",
            field=models.BooleanField(
                default=False,
                verbose_name="Zwei-Faktor für alle Konten dieser Verwaltung verlangen",
            ),
        ),
    ]
