# Generated by Django 5.2.9 on 2026-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_organisation_zweifaktor_pflicht'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='stundensatz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Stundensatz (CHF)'),
        ),
    ]
