# Generated by Django 5.2.9 on 2026-09-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0041_organisation_stundensatz"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="abo_bis",
            field=models.DateField(blank=True, null=True, verbose_name="Testphase bis"),
        ),
        migrations.AddField(
            model_name="organisation",
            name="abo_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Abo/Testphase seit"
            ),
        ),
    ]
