# Generated by Django 5.2.9 on 2026-09-21 05:11
#
# Nimmt 0042 zurück, einen Tag später. Kein Datenverlust: Die beiden Felder
# waren `null=True` und wurden nur vom Onboarding-Dienst gesetzt, den es erst
# seit demselben Tag gibt; gelesen hat sie nichts.
#
# Grund: `docs/PLAN-V7.md` §4.1 gibt Stufe, Status und «Testphase bis» einem
# eigenen Modell `abo.Abonnement` (Arbeitspaket M8, Etappe E3). Zwei
# Datumsfelder an `Organisation` wären dort die zweite Quelle für dieselbe
# Auskunft. Siehe `core/services/onboarding.py`, Abschnitt «UND KEINE
# TESTPHASE».
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0042_organisation_abo_bis_organisation_abo_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="abo_bis",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="abo_start",
        ),
    ]
