# Generated by Django 5.2.9 on 2026-09-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0043_remove_organisation_abo_bis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eigentuemer",
            name="sprache",
            field=models.CharField(
                choices=[
                    ("de", "Deutsch"),
                    ("fr", "Französisch"),
                    ("it", "Italienisch"),
                    ("en", "Englisch"),
                ],
                default="de",
                max_length=2,
                verbose_name="Korrespondenzsprache",
            ),
        ),
    ]
