# Generated by Django 5.2.9 on 2026-09-29 12:15
#
# Abo-Stufen auf die Marktnamen aus core/funktionen.py (D7,
# docs/AUFTRAG-ABOSTUFEN.md). Gespeicherte Werte werden umgeschrieben:
# pro -> team, premium -> professional; start bleibt start.
#
# Rückwärts ist die Abbildung verlustbehaftet: enterprise gab es vorher nicht
# und wird zu premium, der höchsten alten Stufe.

from django.db import migrations, models

VORWAERTS = {'pro': 'team', 'premium': 'professional'}
RUECKWAERTS = {'team': 'pro', 'professional': 'premium', 'enterprise': 'premium'}


def _umschreiben(apps, abbildung):
    Organisation = apps.get_model('crm', 'Organisation')
    for alt, neu in abbildung.items():
        Organisation.objects.filter(abo_plan=alt).update(abo_plan=neu)


def vorwaerts(apps, schema_editor):
    _umschreiben(apps, VORWAERTS)


def rueckwaerts(apps, schema_editor):
    _umschreiben(apps, RUECKWAERTS)


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0044_eigentuemer_sprache"),
    ]

    operations = [
        # Zuerst das Feld: 'professional' hat zwölf Zeichen, die alte Spalte
        # fasste zehn. Rückwärts läuft die Reihenfolge umgekehrt, die Werte
        # sind also wieder kurz, bevor die Spalte schrumpft.
        migrations.AlterField(
            model_name="organisation",
            name="abo_plan",
            field=models.CharField(
                choices=[
                    ("start", "Start"),
                    ("team", "Team"),
                    ("professional", "Professional"),
                    ("enterprise", "Enterprise"),
                ],
                default="team",
                max_length=20,
                verbose_name="Abo-Plan",
            ),
        ),
        migrations.RunPython(vorwaerts, rueckwaerts),
    ]
