# Generated by Django 5.2.9 on 2026-09-30 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0045_abostufen_marktnamen"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenzzinsStand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stichtag",
                    models.DateField(verbose_name="Stichtag (Änderung erkannt am)"),
                ),
                (
                    "satz",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Referenzzinssatz (%)",
                    ),
                ),
                (
                    "vorher",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Vorheriger Satz (%)",
                    ),
                ),
                (
                    "quelle",
                    models.CharField(
                        choices=[("bwo", "Abruf BWO"), ("manuell", "Manuell erfasst")],
                        default="manuell",
                        max_length=10,
                    ),
                ),
                (
                    "betroffene_senkung",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Verträge mit Senkungsanspruch"
                    ),
                ),
                (
                    "betroffene_erhoehung",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Verträge mit Erhöhungsmöglichkeit"
                    ),
                ),
                ("erfasst_am", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referenzzins_staende",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referenzzins-Stand",
                "verbose_name_plural": "Referenzzins-Historie",
                "ordering": ("-stichtag", "-id"),
            },
        ),
    ]
