# Generated by Django 5.2.9 on 2026-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0046_ahv_nummer_verschluesselt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mitgliedschaft",
            name="rolle",
            field=models.CharField(
                choices=[
                    ("Inhaber", "Inhaber"),
                    ("Verwalter", "Verwalter"),
                    ("Sachbearbeiter", "Sachbearbeiter"),
                    ("Lesezugriff", "Lesezugriff"),
                    ("Hauswart", "Hauswart"),
                ],
                default="Sachbearbeiter",
                max_length=20,
                verbose_name="Rolle",
            ),
        ),
    ]
