# Generated by Django 5.2.9 on 2026-10-01 08:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0048_referenzzinsstand"),
    ]

    operations = [
        migrations.CreateModel(
            name="MahnStufe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stufe",
                    models.PositiveSmallIntegerField(
                        help_text="1, 2, 3 … — eine höhere Stufe ist die strengere Mahnung.",
                        verbose_name="Stufe",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(max_length=120, verbose_name="Bezeichnung"),
                ),
                (
                    "ab_tage",
                    models.PositiveIntegerField(
                        help_text="Ab so vielen Tagen Verzug ist diese Stufe erreicht.",
                        verbose_name="Ab Tagen nach Fälligkeit",
                    ),
                ),
                (
                    "gebuehr",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Mahnspesen (CHF)",
                    ),
                ),
                (
                    "art_257d",
                    models.BooleanField(
                        default=False,
                        help_text="Diese Stufe setzt die Zahlungsfrist mit Kündigungsandrohung.",
                        verbose_name="Kündigungsandrohung (Art. 257d OR)",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahnstufe",
                "verbose_name_plural": "Mahnstufen",
                "ordering": ["stufe"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "stufe"),
                        name="uniq_mahnstufe_organisation_stufe",
                    )
                ],
            },
        ),
    ]
