# Generated by Django 5.2.9 on 2026-10-01 11:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0050_mahnstufen_standard"),
    ]

    operations = [
        migrations.AddField(
            model_name="mahnstufe",
            name="brief_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Leer = Standardtext. Platzhalter: {monat} {betrag} {gebuehr} {mieter}.",
                verbose_name="Text des Mahnschreibens",
            ),
        ),
        migrations.AddField(
            model_name="mahnstufe",
            name="brief_titel",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Leer = Standardtitel.",
                max_length=120,
                verbose_name="Titel des Mahnschreibens",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="mahn_mindestabstand_tage",
            field=models.PositiveSmallIntegerField(
                default=7, verbose_name="Mindestabstand zwischen zwei Mahnungen (Tage)"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="mahn_verzug_ab_tag",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 = der Fälligkeitstag zählt als Tag 0 (eine am 1. fällige Miete ist am 1. im Mahnlauf sichtbar); 1 = Verzug erst ab dem Folgetag.",
                verbose_name="Verzug beginnt n Tage nach Fälligkeit",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="verzugszins_prozent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Gesetzlich 5 % (Art. 104 OR); vertraglich abweichend möglich.",
                max_digits=4,
                verbose_name="Verzugszins (% p.a.)",
            ),
        ),
    ]
