# Generated by Django 5.2.9 on 2026-03-31 08:06

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Einheit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(max_length=50, verbose_name="Objektbezeichnung"),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("whg", "Wohnung"),
                            ("gew", "Gewerbe"),
                            ("pp", "Parkplatz"),
                            ("bas", "Bastelraum"),
                        ],
                        default="whg",
                        max_length=10,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "ewid",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="EWID"
                    ),
                ),
                (
                    "etage",
                    models.CharField(blank=True, max_length=50, verbose_name="Etage"),
                ),
                (
                    "wertquote",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=6,
                        verbose_name="Wertquote",
                    ),
                ),
                (
                    "zimmer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Anz. Zimmer",
                    ),
                ),
                (
                    "flaeche_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Fläche (m²)",
                    ),
                ),
                (
                    "nettomiete_aktuell",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="Soll-Miete",
                    ),
                ),
                (
                    "nebenkosten_aktuell",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        verbose_name="Soll-Nebenkosten",
                    ),
                ),
                (
                    "nk_abrechnungsart",
                    models.CharField(
                        choices=[("akonto", "Akonto"), ("pauschal", "Pauschal")],
                        default="pauschal",
                        max_length=20,
                        verbose_name="NK-Art",
                    ),
                ),
                (
                    "ref_zinssatz",
                    models.DecimalField(
                        decimal_places=2,
                        default=core.utils.get_current_ref_zins,
                        max_digits=4,
                        verbose_name="Basis Ref.Zins",
                    ),
                ),
                (
                    "lik_punkte",
                    models.DecimalField(
                        decimal_places=1,
                        default=core.utils.get_current_lik,
                        max_digits=6,
                        verbose_name="Basis LIK",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einheit",
                "verbose_name_plural": "Einheiten",
                "db_table": "core_einheit",
            },
        ),
        migrations.CreateModel(
            name="Geraet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typ", models.CharField(max_length=50)),
                ("marke", models.CharField(max_length=50)),
                ("modell", models.CharField(blank=True, max_length=100)),
                ("installations_datum", models.DateField(blank=True, null=True)),
                ("garantie_bis", models.DateField(blank=True, null=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geraete",
                        to="portfolio.einheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gerät",
                "verbose_name_plural": "Geräte",
                "db_table": "core_geraet",
            },
        ),
        migrations.CreateModel(
            name="Liegenschaft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strasse",
                    models.CharField(max_length=200, verbose_name="Strasse & Nr."),
                ),
                ("plz", models.CharField(max_length=10, verbose_name="PLZ")),
                ("ort", models.CharField(max_length=100, verbose_name="Ort")),
                (
                    "egid",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="EGID"
                    ),
                ),
                (
                    "baujahr",
                    models.IntegerField(blank=True, null=True, verbose_name="Baujahr"),
                ),
                (
                    "kataster_nummer",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Kataster-Nr."
                    ),
                ),
                (
                    "versicherungswert",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Versicherungswert",
                    ),
                ),
                (
                    "kanton",
                    models.CharField(blank=True, max_length=2, verbose_name="Kanton"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bankname"
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
                ),
                (
                    "verteilschluessel_text",
                    models.CharField(
                        default="nach Wohnfläche (m2)",
                        max_length=200,
                        verbose_name="Verteilschlüssel",
                    ),
                ),
                (
                    "mandant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liegenschaften",
                        to="crm.mandant",
                    ),
                ),
                (
                    "verwaltung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liegenschaften",
                        to="crm.verwaltung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liegenschaft",
                "verbose_name_plural": "Liegenschaften",
                "db_table": "core_liegenschaft",
            },
        ),
        migrations.AddField(
            model_name="einheit",
            name="liegenschaft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="einheiten",
                to="portfolio.liegenschaft",
            ),
        ),
        migrations.CreateModel(
            name="Schluessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schluessel_nummer", models.CharField(max_length=50)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schlüssel",
                "db_table": "core_schluessel",
            },
        ),
        migrations.CreateModel(
            name="SchluesselAusgabe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ausgegeben_am", models.DateField(default=django.utils.timezone.now)),
                ("rueckgabe_am", models.DateField(blank=True, null=True)),
                (
                    "handwerker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.handwerker",
                    ),
                ),
                (
                    "mieter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.mieter",
                    ),
                ),
                (
                    "schluessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ausgaben",
                        to="portfolio.schluessel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schlüsselausgabe",
                "db_table": "core_schluesselausgabe",
            },
        ),
        migrations.CreateModel(
            name="Unterhalt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("datum", models.DateField(default=django.utils.timezone.now)),
                (
                    "kosten",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "beleg",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.get_smart_upload_path,
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unterhalt",
                "db_table": "core_unterhalt",
            },
        ),
        migrations.CreateModel(
            name="Zaehler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("strom", "Strom"),
                            ("wasser", "Wasser"),
                            ("heizung", "Heizung"),
                        ],
                        max_length=20,
                    ),
                ),
                ("zaehler_nummer", models.CharField(max_length=50)),
                ("standort", models.CharField(blank=True, max_length=100)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zaehler",
                        to="portfolio.einheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zähler",
                "verbose_name_plural": "Zähler",
                "db_table": "core_zaehler",
            },
        ),
        migrations.CreateModel(
            name="ZaehlerStand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(default=django.utils.timezone.now)),
                ("wert", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "zaehler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staende",
                        to="portfolio.zaehler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zählerstand",
                "db_table": "core_zaehlerstand",
            },
        ),
    ]
