# Generated by Django 5.2.9 on 2026-04-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zaehlerstand",
            options={
                "verbose_name": "Zählerstand",
                "verbose_name_plural": "Zählerstände",
            },
        ),
        migrations.AddField(
            model_name="einheit",
            name="volumen_m3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Volumen (m³)",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="flaeche_m2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Fläche (m²)",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="nk_abrechnungsart",
            field=models.CharField(
                choices=[("akonto", "Akonto"), ("pauschal", "Pauschal")],
                default="akonto",
                max_length=20,
                verbose_name="NK-Art",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="typ",
            field=models.CharField(
                choices=[
                    ("whg", "Wohnung"),
                    ("gew", "Gewerbe"),
                    ("stwe", "STWEG-Einheit"),
                    ("pp", "Parkplatz"),
                    ("gar", "Garage"),
                    ("bas", "Bastelraum"),
                ],
                default="whg",
                max_length=10,
                verbose_name="Typ",
            ),
        ),
        migrations.AlterField(
            model_name="einheit",
            name="wertquote",
            field=models.DecimalField(
                decimal_places=2, default=10.0, max_digits=7, verbose_name="Wertquote"
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaft",
            name="verteilschluessel_text",
            field=models.CharField(
                default="nach Wohnfläche (m2)",
                max_length=200,
                verbose_name="Verteilschlüssel Standard",
            ),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="standort",
            field=models.CharField(blank=True, max_length=100, verbose_name="Standort"),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="typ",
            field=models.CharField(
                choices=[
                    ("strom", "Strom"),
                    ("wasser_kalt", "Kaltwasser"),
                    ("wasser_warm", "Warmwasser"),
                    ("waerme", "Wärmezähler/Heizung"),
                ],
                max_length=20,
                verbose_name="Zählertyp",
            ),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="zaehler_nummer",
            field=models.CharField(max_length=50, verbose_name="Zähler-Nr."),
        ),
        migrations.AlterField(
            model_name="zaehlerstand",
            name="wert",
            field=models.DecimalField(
                decimal_places=3, max_digits=12, verbose_name="Zählerstand"
            ),
        ),
    ]
