# Generated by Django 5.2.9 on 2026-04-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_zaehlerstand_options_einheit_volumen_m3_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geraet",
            name="typ",
        ),
        migrations.AddField(
            model_name="einheit",
            name="heizkosten_verteilschluessel",
            field=models.CharField(
                choices=[
                    ("m2", "Fläche (m2)"),
                    ("m3", "Volumen (m3)"),
                    ("pauschal", "Pauschal"),
                ],
                default="m2",
                max_length=50,
                verbose_name="HK-Schlüssel",
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="notizen",
            field=models.TextField(
                blank=True, default="", verbose_name="Interne Notizen"
            ),
        ),
        migrations.AddField(
            model_name="geraet",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("kuehlschrank", "Kühlschrank"),
                    ("backofen", "Backofen / Herd"),
                    ("geschirrspueler", "Geschirrspüler"),
                    ("waschmaschine", "Waschmaschine"),
                    ("tumbler", "Tumbler / Trockner"),
                    ("heizung", "Heizung / Boiler"),
                    ("sonstiges", "Sonstiges"),
                ],
                default="sonstiges",
                max_length=100,
                verbose_name="Geräte-Art",
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="garantie_bis",
            field=models.DateField(
                blank=True, null=True, verbose_name="Garantie gültig bis"
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="installations_datum",
            field=models.DateField(
                blank=True, null=True, verbose_name="Installiert am"
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="marke",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Marke / Hersteller"
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="modell",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Modell / Seriennummer"
            ),
        ),
    ]
