# Generated by Django 5.2.9 on 2026-04-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_remove_geraet_typ_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geraet",
            name="sonstiges_bezeichnung",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Genaue Bezeichnung (Sonstiges)",
            ),
        ),
    ]
