# Generated by Django 5.2.9 on 2026-04-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_geraet_sonstiges_bezeichnung"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schluesselausgabe",
            options={},
        ),
        migrations.AlterModelOptions(
            name="unterhalt",
            options={},
        ),
        migrations.AddField(
            model_name="einheit",
            name="bodenbelag",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Bodenbelag (Wohnraum)",
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="letzte_renovation",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Letzte Renovation (Jahr)"
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="oto_dose",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="OTO-Dose (Glasfaser)",
            ),
        ),
        migrations.AddField(
            model_name="schluessel",
            name="anzahl",
            field=models.IntegerField(default=1, verbose_name="Anzahl total"),
        ),
        migrations.AddField(
            model_name="schluessel",
            name="einheit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schluessel_liste",
                to="portfolio.einheit",
            ),
        ),
        migrations.AddField(
            model_name="schluessel",
            name="typ",
            field=models.CharField(
                default="Wohnung", max_length=50, verbose_name="Schlüssel-Typ"
            ),
        ),
        migrations.AddField(
            model_name="zaehler",
            name="aktueller_stand",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Aktueller Stand",
            ),
        ),
        migrations.AlterField(
            model_name="schluessel",
            name="schluessel_nummer",
            field=models.CharField(max_length=50, verbose_name="Schlüssel-Nummer"),
        ),
    ]
