# Generated by Django 5.2.9 on 2026-04-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_schluesselausgabe_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schluesselausgabe",
            options={"verbose_name": "Schlüsselausgabe"},
        ),
        migrations.AlterModelOptions(
            name="unterhalt",
            options={
                "verbose_name": "Unterhalt / Renovation",
                "verbose_name_plural": "Unterhalt / Renovationen",
            },
        ),
        migrations.AddField(
            model_name="einheit",
            name="bodenbelag_nassraum",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Bodenbelag (Nassraum)",
            ),
        ),
        migrations.AddField(
            model_name="unterhalt",
            name="beschreibung",
            field=models.TextField(blank=True, default="", verbose_name="Details"),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="einheit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unterhalte",
                to="portfolio.einheit",
            ),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="titel",
            field=models.CharField(max_length=200, verbose_name="Massnahme / Titel"),
        ),
    ]
