# Generated by Django 5.2.9 on 2026-04-28 07:09

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_schluesselausgabe_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geraet",
            options={"verbose_name": "Gerät"},
        ),
        migrations.AlterModelOptions(
            name="unterhalt",
            options={"verbose_name": "Unterhalt"},
        ),
        migrations.AlterModelOptions(
            name="zaehler",
            options={"verbose_name": "Zähler"},
        ),
        migrations.AlterModelOptions(
            name="zaehlerstand",
            options={"verbose_name": "Zählerstand"},
        ),
        migrations.AddField(
            model_name="einheit",
            name="estrich",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Estrich"
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="keller",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Kellerabteil"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="elektriker_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Notfall Elektriker",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="elektriker_telefon",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Elektriker Telefon"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="hauswart_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Hauswart"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="hauswart_telefon",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Hauswart Telefon"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="sanitaer_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Notfall Sanitär"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="sanitaer_telefon",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Sanitär Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="garantie_bis",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="installations_datum",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="kategorie",
            field=models.CharField(
                default="sonstiges", max_length=100, verbose_name="Geräte-Art"
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="marke",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="modell",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="sonstiges_bezeichnung",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Genaue Bezeichnung",
            ),
        ),
        migrations.CreateModel(
            name="Dokument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("kategorie", models.CharField(default="Allgemein", max_length=50)),
                ("datei", models.FileField(upload_to=core.utils.get_smart_upload_path)),
                ("datum", models.DateField(default=django.utils.timezone.now)),
                (
                    "einheit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokumente",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokumente",
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "db_table": "portfolio_dokument",
            },
        ),
    ]
