# Generated by Django 5.2.9 on 2026-04-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_geraet_options_alter_unterhalt_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="gehoert_zu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nebenobjekte",
                to="portfolio.einheit",
                verbose_name="Gehört zu Hauptobjekt",
            ),
        ),
    ]
