# Generated by Django 5.2.9 on 2026-04-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_einheit_gehoert_zu"),
    ]

    operations = [
        migrations.AddField(
            model_name="geraet",
            name="liegenschaft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allgemeine_geraete",
                to="portfolio.liegenschaft",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="gebaeudevolumen_m3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Gebäudevolumen (m³)",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="grundstuecksflaeche_m2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Grundstücksfläche (m²)",
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="einheit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geraete",
                to="portfolio.einheit",
            ),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="kategorie",
            field=models.CharField(default="sonstiges", max_length=100),
        ),
        migrations.AlterField(
            model_name="geraet",
            name="sonstiges_bezeichnung",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="schluessel",
            name="anzahl",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="schluessel",
            name="schluessel_nummer",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="schluessel",
            name="typ",
            field=models.CharField(default="Wohnung", max_length=50),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="beschreibung",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="unterhalt",
            name="titel",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="aktueller_stand",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="typ",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="zaehler_nummer",
            field=models.CharField(max_length=50),
        ),
    ]
