# Generated by Django 5.2.9 on 2026-04-30 09:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0009_geraet_liegenschaft_liegenschaft_gebaeudevolumen_m3_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Verteilschluessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kostenart",
                    models.CharField(
                        choices=[
                            ("heizung", "Heizkosten"),
                            ("wasser", "Wasser / Abwasser"),
                            ("lift", "Liftkosten"),
                            ("allgemeinstrom", "Allgemeinstrom"),
                            ("hauswartung", "Hauswartung / Reinigung"),
                            ("kabel_tv", "Kabel-TV / Antenne"),
                            ("garten", "Gartenpflege"),
                            ("verwaltung", "Verwaltungshonorar"),
                            ("versicherung", "Versicherungen"),
                            ("sonstiges", "Sonstige Nebenkosten"),
                        ],
                        max_length=50,
                        verbose_name="Kostenart",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("m2", "Fläche (m²)"),
                            ("m3", "Volumen (m³)"),
                            ("prozent", "Prozent (%)"),
                            ("anteil", "Anteile (z.B. Wertquote)"),
                            ("pauschal", "Pauschal (CHF)"),
                        ],
                        default="m2",
                        max_length=20,
                        verbose_name="Berechnungstyp",
                    ),
                ),
                (
                    "wert",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="z.B. 85.50 für m2 oder 12.0000 für Prozent",
                        max_digits=12,
                        verbose_name="Wert",
                    ),
                ),
                (
                    "gueltig_ab",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Gültig ab"
                    ),
                ),
                (
                    "gueltig_bis",
                    models.DateField(blank=True, null=True, verbose_name="Gültig bis"),
                ),
                (
                    "notizen",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Bemerkung"
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verteilschluessel",
                        to="portfolio.einheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verteilschlüssel",
                "verbose_name_plural": "Verteilschlüssel",
                "db_table": "portfolio_verteilschluessel",
                "ordering": ["kostenart", "-gueltig_ab"],
            },
        ),
    ]
