# Generated by Django 5.2.9 on 2026-04-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_verteilschluessel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verteilschluessel",
            name="typ",
            field=models.CharField(
                choices=[
                    ("m2", "Fläche (m²)"),
                    ("m3", "Volumen (m³)"),
                    ("prozent", "Prozent (%)"),
                    ("anteil", "Anteile (z.B. Wertquote)"),
                    ("pauschal", "Pauschal (CHF)"),
                    ("zimmer", "Zimmer"),
                    ("einheit", "Pro Einheit"),
                ],
                default="m2",
                max_length=20,
                verbose_name="Berechnungstyp",
            ),
        ),
        migrations.CreateModel(
            name="LiegenschaftVerteilschluessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kostenart",
                    models.CharField(
                        choices=[
                            ("heizung", "Heizkosten"),
                            ("wasser", "Wasser / Abwasser"),
                            ("lift", "Liftkosten"),
                            ("allgemeinstrom", "Allgemeinstrom"),
                            ("hauswartung", "Hauswartung / Reinigung"),
                            ("kabel_tv", "Kabel-TV / Antenne"),
                            ("garten", "Gartenpflege"),
                            ("verwaltung", "Verwaltungshonorar"),
                            ("versicherung", "Versicherungen"),
                            ("sonstiges", "Sonstige Nebenkosten"),
                        ],
                        max_length=50,
                        verbose_name="Kostenart",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("m2", "Fläche (m²)"),
                            ("m3", "Volumen (m³)"),
                            ("wertquote", "Wertquote / Anteile"),
                            ("zimmer", "Anzahl Zimmer"),
                            ("einheit", "Pro Einheit (1 Anteil pro Wohnung)"),
                        ],
                        default="m2",
                        max_length=20,
                        verbose_name="Berechnung nach",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_schluessel",
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liegenschafts-Standard (Verteilschlüssel)",
                "db_table": "portfolio_liegenschaft_verteilschluessel",
                "ordering": ["kostenart"],
            },
        ),
    ]
