# Generated by Django 5.2.9 on 2026-04-30 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_alter_verteilschluessel_typ_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liegenschaftverteilschluessel",
            name="gueltig_ab",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Gültig ab"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaftverteilschluessel",
            name="gueltig_bis",
            field=models.DateField(blank=True, null=True, verbose_name="Gültig bis"),
        ),
        migrations.AddField(
            model_name="liegenschaftverteilschluessel",
            name="notizen",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Bemerkung"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaftverteilschluessel",
            name="wert",
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=12, verbose_name="Wert"
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaftverteilschluessel",
            name="typ",
            field=models.CharField(
                choices=[
                    ("m2", "Fläche (m²)"),
                    ("m3", "Volumen (m³)"),
                    ("prozent", "Prozent (%)"),
                    ("anteil", "Anteile (z.B. Wertquote)"),
                    ("pauschal", "Pauschal (CHF)"),
                ],
                default="m2",
                max_length=20,
                verbose_name="Berechnung nach",
            ),
        ),
        migrations.AlterField(
            model_name="verteilschluessel",
            name="typ",
            field=models.CharField(
                choices=[
                    ("m2", "Fläche (m²)"),
                    ("m3", "Volumen (m³)"),
                    ("prozent", "Prozent (%)"),
                    ("anteil", "Anteile (z.B. Wertquote)"),
                    ("pauschal", "Pauschal (CHF)"),
                ],
                default="m2",
                max_length=20,
                verbose_name="Berechnungstyp",
            ),
        ),
    ]
