# Generated by Django 5.2.9 on 2026-05-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_liegenschaftverteilschluessel_gueltig_ab_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="standard_kautionsmonate",
            field=models.IntegerField(
                default=3, verbose_name="Standard Kaution (Monate)"
            ),
        ),
        migrations.AlterField(
            model_name="liegenschaftverteilschluessel",
            name="typ",
            field=models.CharField(
                choices=[
                    ("m2", "Fläche (m²)"),
                    ("m3", "Volumen (m³)"),
                    ("prozent", "Prozent (%)"),
                    ("anteil", "Anteile (z.B. Wertquote)"),
                    ("pauschal", "Pauschal (CHF)"),
                    ("zimmer", "Zimmer"),
                    ("einheit", "Pro Einheit"),
                ],
                default="m2",
                max_length=20,
                verbose_name="Berechnung nach",
            ),
        ),
        migrations.AlterField(
            model_name="verteilschluessel",
            name="typ",
            field=models.CharField(
                choices=[
                    ("m2", "Fläche (m²)"),
                    ("m3", "Volumen (m³)"),
                    ("prozent", "Prozent (%)"),
                    ("anteil", "Anteile (z.B. Wertquote)"),
                    ("pauschal", "Pauschal (CHF)"),
                    ("zimmer", "Zimmer"),
                    ("einheit", "Pro Einheit"),
                ],
                default="m2",
                max_length=20,
                verbose_name="Berechnungstyp",
            ),
        ),
        migrations.AlterField(
            model_name="verteilschluessel",
            name="wert",
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=12, verbose_name="Wert"
            ),
        ),
    ]
