# Generated by Django 5.2.9 on 2026-07-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_einheit_standard_kautionsmonate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liegenschaft",
            name="hkvo_aktiv",
            field=models.BooleanField(
                default=False, verbose_name="Verbrauchsabhängige Heizkosten (HKVO)"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="hkvo_grundkosten_prozent",
            field=models.IntegerField(
                default=40, verbose_name="Grundkosten-Anteil (%)"
            ),
        ),
    ]
