# Generated by Django 5.2.9 on 2026-07-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_liegenschaft_hkvo_aktiv_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wartungsfrist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("wartung", "Wartung / Service"),
                            ("versicherung", "Versicherung"),
                            ("kontrolle", "Kontrolle / Prüfung"),
                            ("abo", "Abonnement / Vertrag"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        default="wartung",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(max_length=200, verbose_name="Bezeichnung"),
                ),
                (
                    "anbieter",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Anbieter / Dienstleister",
                    ),
                ),
                (
                    "naechste_faelligkeit",
                    models.DateField(verbose_name="Nächste Fälligkeit"),
                ),
                (
                    "intervall_monate",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Intervall (Monate)"
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "notiz",
                    models.TextField(blank=True, default="", verbose_name="Notiz"),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wartungsfristen",
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wartungsfrist",
                "verbose_name_plural": "Wartungsfristen",
                "db_table": "portfolio_wartungsfrist",
                "ordering": ["naechste_faelligkeit"],
            },
        ),
    ]
