# Generated by Django 5.2.9 on 2026-07-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_wartungsfrist"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="ausschreibung_notiz",
            field=models.TextField(
                blank=True, default="", verbose_name="Vermarktungsnotiz"
            ),
        ),
        migrations.AddField(
            model_name="einheit",
            name="verfuegbar_ab",
            field=models.DateField(blank=True, null=True, verbose_name="Verfügbar ab"),
        ),
        migrations.AddField(
            model_name="einheit",
            name="zur_ausschreibung",
            field=models.BooleanField(default=False, verbose_name="Zur Ausschreibung"),
        ),
    ]
