# Generated by Django 5.2.9 on 2026-07-12 16:56

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0016_einheit_ausschreibung_notiz_einheit_verfuegbar_ab_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EinheitFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bild", models.ImageField(upload_to=core.utils.get_smart_upload_path)),
                (
                    "beschreibung",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("reihenfolge", models.PositiveIntegerField(default=0)),
                ("hochgeladen_am", models.DateTimeField(auto_now_add=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="portfolio.einheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objekt-Foto",
                "verbose_name_plural": "Objekt-Fotos",
                "db_table": "core_einheitfoto",
                "ordering": ["reihenfolge", "hochgeladen_am"],
            },
        ),
    ]
