# Generated by Django 5.2.9 on 2026-07-13 06:07

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_einheitfoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lebensdauer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kategorie", models.CharField(max_length=80, unique=True)),
                (
                    "jahre",
                    models.PositiveIntegerField(verbose_name="Lebensdauer (Jahre)"),
                ),
                ("bemerkung", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "verbose_name": "Lebensdauer",
                "verbose_name_plural": "Lebensdauertabelle",
                "db_table": "core_lebensdauer",
                "ordering": ["kategorie"],
            },
        ),
        migrations.CreateModel(
            name="Ausstattung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raum", models.CharField(max_length=60, verbose_name="Raum")),
                (
                    "kategorie",
                    models.CharField(max_length=80, verbose_name="Kategorie"),
                ),
                (
                    "bezeichnung",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Bezeichnung / Detail",
                    ),
                ),
                ("marke", models.CharField(blank=True, default="", max_length=80)),
                ("modell", models.CharField(blank=True, default="", max_length=80)),
                ("material", models.CharField(blank=True, default="", max_length=80)),
                ("menge", models.PositiveIntegerField(default=1, verbose_name="Menge")),
                (
                    "einbau_datum",
                    models.DateField(
                        blank=True, null=True, verbose_name="Einbau / Anschaffung"
                    ),
                ),
                (
                    "neuwert",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Neuwert (CHF)",
                    ),
                ),
                (
                    "lebensdauer_jahre",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Lebensdauer (Jahre, optional)",
                    ),
                ),
                (
                    "zustand",
                    models.CharField(
                        choices=[
                            ("neuwertig", "Neuwertig"),
                            ("gut", "Gut"),
                            ("gebraucht", "Gebraucht"),
                            ("defekt", "Defekt"),
                        ],
                        default="gut",
                        max_length=12,
                    ),
                ),
                ("garantie_bis", models.DateField(blank=True, null=True)),
                ("notiz", models.TextField(blank=True, default="")),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.get_smart_upload_path,
                    ),
                ),
                ("sortierung", models.PositiveIntegerField(default=0)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ausstattung",
                        to="portfolio.einheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ausstattung",
                "verbose_name_plural": "Ausstattung",
                "db_table": "core_ausstattung",
                "ordering": ["raum", "sortierung", "id"],
            },
        ),
    ]
