# Generated by Django 5.2.9 on 2026-07-14 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_seed_lebensdauer"),
    ]

    operations = [
        migrations.AddField(
            model_name="zaehler",
            name="liegenschaft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allgemeine_zaehler",
                to="portfolio.liegenschaft",
            ),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="einheit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zaehler",
                to="portfolio.einheit",
            ),
        ),
        migrations.AlterField(
            model_name="zaehler",
            name="typ",
            field=models.CharField(max_length=40),
        ),
    ]
