# Generated by Django 5.2.9 on 2026-07-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_zaehler_liegenschaft_alter_zaehler_einheit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geraet",
            name="kapazitaet",
            field=models.CharField(
                blank=True,
                default="",
                max_length=60,
                verbose_name="Kapazität / Leistung",
            ),
        ),
        migrations.AddField(
            model_name="geraet",
            name="notiz",
            field=models.TextField(blank=True, default="", verbose_name="Notiz"),
        ),
        migrations.AddField(
            model_name="geraet",
            name="seriennummer",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Seriennummer"
            ),
        ),
        migrations.AddField(
            model_name="geraet",
            name="standort",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Standort"
            ),
        ),
    ]
