# Generated by Django 5.2.9 on 2026-07-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0021_geraet_kapazitaet_geraet_notiz_geraet_seriennummer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="merkmale",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Ausstattungsmerkmale"
            ),
        ),
    ]
