# Generated by Django 5.2.9 on 2026-07-14 17:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0022_einheit_merkmale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sollmietzins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gueltig_ab",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Gültig ab"
                    ),
                ),
                (
                    "netto_mietzins",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="Netto-Mietzins (CHF)",
                    ),
                ),
                (
                    "nebenkosten",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=6,
                        verbose_name="Nebenkosten (CHF)",
                    ),
                ),
                (
                    "notiz",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Bemerkung"
                    ),
                ),
                (
                    "erstellt_am",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Erfasst am"
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sollmietzinse",
                        to="portfolio.einheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sollmietzins",
                "verbose_name_plural": "Sollmietzinse",
                "db_table": "portfolio_sollmietzins",
                "ordering": ["-gueltig_ab", "-id"],
            },
        ),
    ]
