# Generated by Django 5.2.9 on 2026-07-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0024_staffelvorlage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sollmietzins",
            name="basis_lik_punkte",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=6,
                null=True,
                verbose_name="Basis LIK (Punkte)",
            ),
        ),
        migrations.AddField(
            model_name="sollmietzins",
            name="basis_referenzzinssatz",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Basis Referenzzinssatz (%)",
            ),
        ),
    ]
