# Generated by Django 5.2.9 on 2026-07-15 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0025_sollmietzins_basis_lik_punkte_and_more"),
        ("rentals", "0021_collapse_vertragsbeilagen_dubletten"),
    ]

    operations = [
        migrations.AddField(
            model_name="sollmietzins",
            name="quelle_anpassung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sollmietzins_zeilen",
                to="rentals.mietzinsanpassung",
            ),
        ),
    ]
