# Generated by Django 5.2.9 on 2026-07-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0026_sollmietzins_quelle_anpassung"),
    ]

    operations = [
        migrations.AddField(
            model_name="sollmietzins",
            name="rabatt_netto",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Rabatt Netto (CHF)",
            ),
        ),
        migrations.AddField(
            model_name="sollmietzins",
            name="rabatt_nk",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Rabatt NK (CHF)",
            ),
        ),
        migrations.AlterField(
            model_name="sollmietzins",
            name="netto_mietzins",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Netto-Mietzins (Referenz, CHF)",
            ),
        ),
    ]
