# Generated by Django 5.2.9 on 2026-07-16 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0027_sollmietzins_rabatt_netto_sollmietzins_rabatt_nk_and_more"),
        ("rentals", "0025_cleanup_verwaiste_vertragsdokumente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sollmietzins",
            name="quelle_anpassung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sollmietzins_zeilen",
                to="rentals.mietzinsanpassung",
            ),
        ),
    ]
