# Generated by Django 5.2.9 on 2026-07-17 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0028_alter_sollmietzins_quelle_anpassung"),
    ]

    operations = [
        migrations.CreateModel(
            name="Versicherung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("gebaeude", "Gebäudeversicherung"),
                            ("haftpflicht", "Gebäude-Haftpflicht"),
                            ("wasser", "Wasser / Elementar"),
                            ("glas", "Glasbruch"),
                            ("bauherren", "Bauherren / Bau"),
                            ("rechtsschutz", "Rechtsschutz"),
                            ("andere", "Andere"),
                        ],
                        default="gebaeude",
                        max_length=20,
                        verbose_name="Art",
                    ),
                ),
                (
                    "gesellschaft",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Gesellschaft",
                    ),
                ),
                (
                    "policennummer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="Policennummer",
                    ),
                ),
                (
                    "versicherungssumme",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Versicherungssumme (CHF)",
                    ),
                ),
                (
                    "jahrespraemie",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Jahresprämie (CHF)",
                    ),
                ),
                (
                    "ablauf_datum",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Ablauf / nächste Fälligkeit",
                    ),
                ),
                (
                    "notiz",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Bemerkung"
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versicherungen",
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versicherung",
                "verbose_name_plural": "Versicherungen",
                "db_table": "core_versicherung",
                "ordering": ["art", "gesellschaft"],
            },
        ),
    ]
