# Generated by Django 5.2.9 on 2026-07-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0029_versicherung"),
    ]

    operations = [
        migrations.AddField(
            model_name="liegenschaft",
            name="anlagekosten",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Anlage-/Gestehungskosten",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="energiebezugsflaeche_m2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Energiebezugsfläche (m²)",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="energietraeger",
            field=models.CharField(
                blank=True,
                default="",
                max_length=60,
                verbose_name="Energieträger (Zusatz)",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="geak_datum",
            field=models.DateField(
                blank=True, null=True, verbose_name="GEAK ausgestellt am"
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="geak_klasse",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                default="",
                max_length=1,
                verbose_name="GEAK-Klasse (Gebäudehülle)",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="geak_klasse_gesamt",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                default="",
                max_length=1,
                verbose_name="GEAK-Klasse (Gesamtenergie)",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="heizsystem",
            field=models.CharField(
                blank=True,
                choices=[
                    ("waermepumpe", "Wärmepumpe"),
                    ("gas", "Gasheizung"),
                    ("oel", "Ölheizung"),
                    ("fernwaerme", "Fernwärme"),
                    ("holz", "Holz / Pellets"),
                    ("elektro", "Elektro"),
                    ("solar", "Solar / thermisch"),
                    ("andere", "Andere"),
                ],
                default="",
                max_length=20,
                verbose_name="Heizsystem",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="kaufdatum",
            field=models.DateField(blank=True, null=True, verbose_name="Kaufdatum"),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="kaufpreis",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Kaufpreis",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="verkehrswert",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Verkehrswert (Marktwert)",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="warmwasser",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zentral", "Zentral (Heizung)"),
                    ("boiler", "Elektroboiler"),
                    ("waermepumpe", "Wärmepumpenboiler"),
                    ("solar", "Solar"),
                    ("andere", "Andere"),
                ],
                default="",
                max_length=20,
                verbose_name="Warmwasser",
            ),
        ),
    ]
