# Generated by Django 5.2.9 on 2026-08-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0040_organisation_zweifaktor_pflicht"),
        ("portfolio", "0038_organisation_rest_pflicht"),
    ]

    operations = [
        migrations.CreateModel(
            name="Liegenschaftsbudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jahr", models.PositiveSmallIntegerField(verbose_name="Jahr")),
                (
                    "unterhalt",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Geplanter Unterhalt für dieses Jahr, ohne wertvermehrende Investitionen.",
                        max_digits=12,
                        verbose_name="Unterhaltsbudget (CHF)",
                    ),
                ),
                (
                    "bemerkung",
                    models.TextField(blank=True, default="", verbose_name="Bemerkung"),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liegenschaftsbudget",
                "verbose_name_plural": "Liegenschaftsbudgets",
                "ordering": ("-jahr",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("liegenschaft", "jahr"),
                        name="budget_je_liegenschaft_und_jahr",
                    )
                ],
            },
        ),
    ]
