# Generated by Django 5.2.9 on 2026-09-30 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0040_liegenschaft_betreut_von"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="liegenschaft",
            name="hauswarte",
            field=models.ManyToManyField(
                blank=True,
                related_name="hauswart_liegenschaften",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Hauswarte",
            ),
        ),
    ]
