# Generated by Django 5.2.9 on 2026-09-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0041_liegenschaft_hauswarte"),
    ]

    operations = [
        migrations.AddField(
            model_name="versicherung",
            name="selbstbehalt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Selbstbehalt je Schaden (CHF)",
            ),
        ),
    ]
