# Generated by Django 5.2.9 on 2026-10-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0042_versicherung_selbstbehalt"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="stockwerkeigentuemer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stweg_einheiten",
                to="crm.eigentuemer",
                verbose_name="Stockwerkeigentümer",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="status",
            field=models.CharField(
                choices=[
                    ("entwurf", "Entwurf"),
                    ("aktiv", "Aktiv"),
                    ("archiviert", "Archiviert"),
                ],
                default="aktiv",
                max_length=12,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="typ",
            field=models.CharField(
                choices=[
                    ("MIETE", "Mietliegenschaft"),
                    ("STWEG", "Stockwerkeigentum (STWEG)"),
                ],
                default="MIETE",
                max_length=10,
                verbose_name="Art",
            ),
        ),
        migrations.AddField(
            model_name="liegenschaft",
            name="wertquote_total",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Wertquoten-Total (Nenner)"
            ),
        ),
    ]
