# Generated by Django 5.2.9 on 2026-10-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0043_stweg_grundlagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="einheit",
            name="miteigentuemer",
            field=models.ManyToManyField(
                blank=True,
                related_name="stweg_miteigentum",
                to="crm.eigentuemer",
                verbose_name="Miteigentümer",
            ),
        ),
    ]
