# Generated by Django 5.2.9 on 2026-10-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0044_einheit_miteigentuemer"),
    ]

    operations = [
        migrations.AddField(
            model_name="liegenschaft",
            name="verteilschluessel_aktiv",
            field=models.BooleanField(
                default=False, verbose_name="Verteilschlüssel der Liegenschaft anwenden"
            ),
        ),
    ]
