# Generated by Django 5.2.9 on 2026-10-04 07:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0043_stweg_grundlagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="StwegAbrechnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jahr", models.PositiveIntegerField()),
                (
                    "gesamtkosten",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("entwurf", "Entwurf"),
                            ("abgeschlossen", "Abgeschlossen"),
                        ],
                        default="entwurf",
                        max_length=14,
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stweg_abrechnungen",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_abrechnung",
                "ordering": ["-jahr"],
            },
        ),
        migrations.CreateModel(
            name="StwegAbrechnungPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wertquote", models.DecimalField(decimal_places=2, max_digits=7)),
                ("wertquote_total", models.PositiveIntegerField()),
                ("kostenanteil", models.DecimalField(decimal_places=2, max_digits=12)),
                ("akonto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("saldo", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "abrechnung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="stweg.stwegabrechnung",
                    ),
                ),
                (
                    "eigentuemer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.eigentuemer",
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stweg_positionen",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_abrechnung_position",
                "ordering": ["einheit_id"],
            },
        ),
        migrations.CreateModel(
            name="StwegAkonto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Betrag (CHF)"
                    ),
                ),
                ("bemerkung", models.CharField(blank=True, default="", max_length=200)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stweg_akontos",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Akonto-Zahlung",
                "verbose_name_plural": "Akonto-Zahlungen",
                "db_table": "stweg_akonto",
                "ordering": ["datum", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="stwegabrechnung",
            constraint=models.UniqueConstraint(
                fields=("liegenschaft", "jahr"),
                name="stweg_abrechnung_je_liegenschaft_und_jahr",
            ),
        ),
    ]
