# Generated by Django 5.2.9 on 2026-10-04 08:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0043_stweg_grundlagen"),
        ("stweg", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Traktandum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nr", models.PositiveSmallIntegerField()),
                ("titel", models.CharField(max_length=200)),
                ("beschreibung", models.TextField(blank=True, default="")),
                (
                    "antrag",
                    models.TextField(
                        blank=True, default="", verbose_name="Antrag der Verwaltung"
                    ),
                ),
                (
                    "mehrheitsart",
                    models.CharField(
                        choices=[
                            ("einfach_koepfe", "Mehrheit der Stimmenden (nach Köpfen)"),
                            (
                                "einfach_quoten",
                                "Mehrheit der Stimmenden (nach Wertquoten)",
                            ),
                            (
                                "doppelt",
                                "Mehrheit nach Köpfen UND Wertquoten (der Stimmenden)",
                            ),
                            (
                                "doppelt_aller",
                                "Mehrheit aller Eigentümer UND aller Wertquoten",
                            ),
                            ("einstimmig", "Einstimmigkeit aller Eigentümer"),
                            ("kenntnisnahme", "Zur Kenntnisnahme (keine Abstimmung)"),
                        ],
                        default="einfach_koepfe",
                        max_length=20,
                    ),
                ),
                (
                    "rechtsgrundlage",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Von der Verwaltung zu bestätigen; wird nicht automatisch ermittelt.",
                        max_length=200,
                        verbose_name="Rechtsgrundlage / Reglement",
                    ),
                ),
                (
                    "ergebnis",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("angenommen", "Angenommen"),
                            ("abgelehnt", "Abgelehnt"),
                            ("vertagt", "Vertagt"),
                            ("kenntnis", "Zur Kenntnis genommen"),
                        ],
                        default="offen",
                        max_length=10,
                    ),
                ),
                ("beschlusstext", models.TextField(blank=True, default="")),
                ("ja_koepfe", models.PositiveSmallIntegerField(default=0)),
                ("nein_koepfe", models.PositiveSmallIntegerField(default=0)),
                ("enthaltung_koepfe", models.PositiveSmallIntegerField(default=0)),
                (
                    "ja_quoten",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=9
                    ),
                ),
                (
                    "nein_quoten",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=9
                    ),
                ),
                (
                    "enthaltung_quoten",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=9
                    ),
                ),
                ("festgestellt_am", models.DateTimeField(blank=True, null=True)),
                (
                    "vollzug_aufgabe",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Vollzug (Aufgabe)",
                    ),
                ),
                ("vollzug_faellig_am", models.DateField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_traktandum",
                "ordering": ["versammlung_id", "nr"],
            },
        ),
        migrations.CreateModel(
            name="StwegAnfrage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("betreff", models.CharField(max_length=200)),
                ("text", models.TextField(blank=True, default="")),
                (
                    "kanal",
                    models.CharField(
                        choices=[
                            ("portal", "Portal"),
                            ("email", "E-Mail"),
                            ("telefon", "Telefon"),
                            ("brief", "Brief"),
                            ("persoenlich", "Persönlich"),
                        ],
                        default="portal",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("neu", "Neu"),
                            ("in_bearbeitung", "In Bearbeitung"),
                            ("beantwortet", "Beantwortet"),
                            ("erledigt", "Erledigt"),
                        ],
                        default="neu",
                        max_length=14,
                    ),
                ),
                ("antwort", models.TextField(blank=True, default="")),
                ("beantwortet_am", models.DateTimeField(blank=True, null=True)),
                ("faellig_am", models.DateField(blank=True, null=True)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "eigentuemer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stweg_anfragen",
                        to="crm.eigentuemer",
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stweg_anfragen",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stweg_anfragen",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "traktandum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anfragen",
                        to="stweg.traktandum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anfrage",
                "verbose_name_plural": "Anfragen",
                "db_table": "stweg_anfrage",
                "ordering": ["-erstellt_am"],
            },
        ),
        migrations.CreateModel(
            name="Versammlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("ordentlich", "Ordentliche Versammlung"),
                            ("ausserordentlich", "Ausserordentliche Versammlung"),
                        ],
                        default="ordentlich",
                        max_length=20,
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("datum", models.DateTimeField(verbose_name="Beginn")),
                ("ort", models.CharField(blank=True, default="", max_length=200)),
                ("einladungsfrist_tage", models.PositiveSmallIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("entwurf", "Entwurf"),
                            ("eingeladen", "Eingeladen"),
                            ("durchgefuehrt", "Durchgeführt"),
                            ("protokolliert", "Protokoll versendet"),
                        ],
                        default="entwurf",
                        max_length=14,
                    ),
                ),
                (
                    "leitung",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Versammlungsleitung",
                    ),
                ),
                (
                    "protokollfuehrung",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("einladung_versendet_am", models.DateTimeField(blank=True, null=True)),
                ("protokoll_text", models.TextField(blank=True, default="")),
                ("protokoll_versendet_am", models.DateTimeField(blank=True, null=True)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versammlungen",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versammlung",
                "verbose_name_plural": "Versammlungen",
                "db_table": "stweg_versammlung",
                "ordering": ["-datum"],
            },
        ),
        migrations.AddField(
            model_name="traktandum",
            name="versammlung",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traktanden",
                to="stweg.versammlung",
            ),
        ),
        migrations.CreateModel(
            name="StwegVersand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("einladung", "Einladung"),
                            ("protokoll", "Protokoll"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.CharField(blank=True, default="", max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("gesendet", "Per E-Mail gesendet"),
                            ("fehler", "Fehler beim Versand"),
                            (
                                "post_noetig",
                                "Per Post zustellen (keine E-Mail-Adresse)",
                            ),
                        ],
                        max_length=12,
                    ),
                ),
                ("zeitpunkt", models.DateTimeField(auto_now_add=True)),
                ("fehler", models.CharField(blank=True, default="", max_length=300)),
                (
                    "eigentuemer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.eigentuemer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "versammlung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versaende",
                        to="stweg.versammlung",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_versand",
                "ordering": ["-zeitpunkt"],
            },
        ),
        migrations.CreateModel(
            name="Anwesenheit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("anwesend", "Anwesend"),
                            ("vertreten", "Vertreten (Vollmacht)"),
                            ("abwesend", "Abwesend"),
                        ],
                        default="abwesend",
                        max_length=10,
                    ),
                ),
                (
                    "vertreter",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Vertreten durch",
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "versammlung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anwesenheiten",
                        to="stweg.versammlung",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_anwesenheit",
            },
        ),
        migrations.CreateModel(
            name="Stimme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wert",
                    models.CharField(
                        choices=[
                            ("ja", "Ja"),
                            ("nein", "Nein"),
                            ("enthaltung", "Enthaltung"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "traktandum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stimmen",
                        to="stweg.traktandum",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_stimme",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("traktandum", "einheit"), name="stweg_stimme_je_einheit"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="traktandum",
            constraint=models.UniqueConstraint(
                fields=("versammlung", "nr"), name="stweg_traktandum_nr_je_versammlung"
            ),
        ),
        migrations.AddConstraint(
            model_name="anwesenheit",
            constraint=models.UniqueConstraint(
                fields=("versammlung", "einheit"), name="stweg_anwesenheit_je_einheit"
            ),
        ),
    ]
