# Generated by Django 5.2.9 on 2026-10-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("stweg", "0002_versammlung_anfragen"),
    ]

    operations = [
        migrations.CreateModel(
            name="StwegAbrechnungKosten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(blank=True, null=True)),
                ("lieferant", models.CharField(blank=True, default="", max_length=200)),
                ("text", models.CharField(blank=True, default="", max_length=200)),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "abrechnung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kostenzeilen",
                        to="stweg.stwegabrechnung",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_abrechnung_kosten",
                "ordering": ["datum", "id"],
            },
        ),
    ]
