# Generated by Django 5.2.9 on 2026-10-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0043_stweg_grundlagen"),
        ("stweg", "0003_abrechnung_kostenzeilen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vollmacht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bevollmaechtigter",
                    models.CharField(max_length=120, verbose_name="Vertreten durch"),
                ),
                (
                    "kanal",
                    models.CharField(
                        choices=[
                            ("portal", "Portal"),
                            ("verwaltung", "Von der Verwaltung erfasst"),
                        ],
                        default="portal",
                        max_length=12,
                    ),
                ),
                ("erteilt_am", models.DateTimeField(auto_now_add=True)),
                ("widerrufen_am", models.DateTimeField(blank=True, null=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "erteilt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.eigentuemer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "versammlung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vollmachten",
                        to="stweg.versammlung",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_vollmacht",
                "ordering": ["erteilt_am"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("widerrufen_am__isnull", True)),
                        fields=("versammlung", "einheit"),
                        name="stweg_vollmacht_eine_gueltige_je_einheit",
                    )
                ],
            },
        ),
    ]
