# Generated by Django 5.2.9 on 2026-10-04 10:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0043_stweg_grundlagen"),
        ("stweg", "0004_vollmacht"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zirkularbeschluss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("antrag", models.TextField(verbose_name="Antrag")),
                ("begruendung", models.TextField(blank=True, default="")),
                (
                    "mehrheitsart",
                    models.CharField(
                        choices=[
                            ("einfach_koepfe", "Mehrheit der Stimmenden (nach Köpfen)"),
                            (
                                "einfach_quoten",
                                "Mehrheit der Stimmenden (nach Wertquoten)",
                            ),
                            (
                                "doppelt",
                                "Mehrheit nach Köpfen UND Wertquoten (der Stimmenden)",
                            ),
                            (
                                "doppelt_aller",
                                "Mehrheit aller Eigentümer UND aller Wertquoten",
                            ),
                            ("einstimmig", "Einstimmigkeit aller Eigentümer"),
                            ("kenntnisnahme", "Zur Kenntnisnahme (keine Abstimmung)"),
                        ],
                        default="einstimmig",
                        max_length=20,
                    ),
                ),
                (
                    "rechtsgrundlage",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("frist_bis", models.DateField(verbose_name="Abstimmung bis")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("entwurf", "Entwurf"),
                            ("laufend", "Läuft"),
                            ("abgeschlossen", "Abgeschlossen"),
                        ],
                        default="entwurf",
                        max_length=14,
                    ),
                ),
                ("versendet_am", models.DateTimeField(blank=True, null=True)),
                (
                    "ergebnis",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("angenommen", "Angenommen"),
                            ("abgelehnt", "Abgelehnt"),
                            ("vertagt", "Vertagt"),
                            ("kenntnis", "Zur Kenntnis genommen"),
                        ],
                        default="offen",
                        max_length=10,
                    ),
                ),
                ("beschlusstext", models.TextField(blank=True, default="")),
                ("ja_koepfe", models.PositiveSmallIntegerField(default=0)),
                ("nein_koepfe", models.PositiveSmallIntegerField(default=0)),
                ("enthaltung_koepfe", models.PositiveSmallIntegerField(default=0)),
                (
                    "ja_quoten",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=9
                    ),
                ),
                (
                    "nein_quoten",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=9
                    ),
                ),
                (
                    "enthaltung_quoten",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=9
                    ),
                ),
                ("festgestellt_am", models.DateTimeField(blank=True, null=True)),
                ("ergebnis_versendet_am", models.DateTimeField(blank=True, null=True)),
                (
                    "vollzug_aufgabe",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("vollzug_faellig_am", models.DateField(blank=True, null=True)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zirkularbeschluesse",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zirkularbeschluss",
                "verbose_name_plural": "Zirkularbeschlüsse",
                "db_table": "stweg_zirkular",
                "ordering": ["-erstellt_am"],
            },
        ),
        migrations.CreateModel(
            name="ZirkularVersand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[("antrag", "Antrag"), ("ergebnis", "Ergebnis")],
                        max_length=10,
                    ),
                ),
                ("email", models.CharField(blank=True, default="", max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("gesendet", "Per E-Mail gesendet"),
                            ("fehler", "Fehler beim Versand"),
                            (
                                "post_noetig",
                                "Per Post zustellen (keine E-Mail-Adresse)",
                            ),
                        ],
                        max_length=12,
                    ),
                ),
                ("zeitpunkt", models.DateTimeField(auto_now_add=True)),
                ("fehler", models.CharField(blank=True, default="", max_length=300)),
                (
                    "eigentuemer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.eigentuemer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "zirkular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versaende",
                        to="stweg.zirkularbeschluss",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_zirkular_versand",
                "ordering": ["-zeitpunkt"],
            },
        ),
        migrations.CreateModel(
            name="ZirkularStimme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wert",
                    models.CharField(
                        choices=[
                            ("ja", "Ja"),
                            ("nein", "Nein"),
                            ("enthaltung", "Enthaltung"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "kanal",
                    models.CharField(
                        choices=[
                            ("portal", "Portal"),
                            ("verwaltung", "Von der Verwaltung erfasst"),
                        ],
                        default="portal",
                        max_length=12,
                    ),
                ),
                ("abgegeben_am", models.DateTimeField(auto_now=True)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "zirkular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stimmen",
                        to="stweg.zirkularbeschluss",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_zirkular_stimme",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("zirkular", "einheit"),
                        name="stweg_zirkular_stimme_je_einheit",
                    )
                ],
            },
        ),
    ]
