# Generated by Django 5.2.9 on 2026-10-04 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("finance", "0044_stweg_grundlagen"),
        ("portfolio", "0044_einheit_miteigentuemer"),
        ("stweg", "0005_zirkularbeschluss"),
    ]

    operations = [
        migrations.AddField(
            model_name="stwegabrechnungkosten",
            name="schluessel_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="StwegSchluessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("wertquote", "Wertquote (aus der Einheit)"),
                            ("flaeche", "Fläche m² (aus der Einheit)"),
                            ("volumen", "Volumen m³ (aus der Einheit)"),
                            ("manuell", "Eigene Anteile je Einheit (z. B. Lift)"),
                        ],
                        default="wertquote",
                        max_length=10,
                    ),
                ),
                ("ist_standard", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(blank=True, default="", max_length=200)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stweg_schluessel",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verteilschlüssel",
                "verbose_name_plural": "Verteilschlüssel",
                "db_table": "stweg_schluessel",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StwegKostenzuordnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "konto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="finance.buchungskonto",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stweg_kostenzuordnungen",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "schluessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zuordnungen",
                        to="stweg.stwegschluessel",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_kostenzuordnung",
            },
        ),
        migrations.CreateModel(
            name="StwegAbrechnungAnteil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schluessel_name", models.CharField(max_length=100)),
                ("gewicht", models.DecimalField(decimal_places=4, max_digits=14)),
                ("gewicht_total", models.DecimalField(decimal_places=4, max_digits=14)),
                ("kosten_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schluesselanteile",
                        to="stweg.stwegabrechnungposition",
                    ),
                ),
                (
                    "schluessel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stweg.stwegschluessel",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_abrechnung_anteil",
                "ordering": ["schluessel_name", "id"],
            },
        ),
        migrations.AddField(
            model_name="stwegabrechnungkosten",
            name="schluessel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="stweg.stwegschluessel",
            ),
        ),
        migrations.CreateModel(
            name="StwegSchluesselAnteil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anteil", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "schluessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anteile",
                        to="stweg.stwegschluessel",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_schluessel_anteil",
            },
        ),
        migrations.AddConstraint(
            model_name="stwegschluessel",
            constraint=models.UniqueConstraint(
                fields=("liegenschaft", "name"), name="stweg_schluessel_name_je_lg"
            ),
        ),
        migrations.AddConstraint(
            model_name="stwegschluessel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ist_standard", True)),
                fields=("liegenschaft",),
                name="stweg_schluessel_ein_standard_je_lg",
            ),
        ),
        migrations.AddConstraint(
            model_name="stwegkostenzuordnung",
            constraint=models.UniqueConstraint(
                fields=("liegenschaft", "konto"), name="stweg_zuordnung_je_konto"
            ),
        ),
        migrations.AddConstraint(
            model_name="stwegschluesselanteil",
            constraint=models.UniqueConstraint(
                fields=("schluessel", "einheit"), name="stweg_anteil_je_einheit"
            ),
        ),
        migrations.AddConstraint(
            model_name="stwegschluesselanteil",
            constraint=models.CheckConstraint(
                condition=models.Q(("anteil__gte", 0)),
                name="stweg_anteil_nicht_negativ",
            ),
        ),
    ]
