# Generated by Django 5.2.9 on 2026-10-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0044_einheit_miteigentuemer"),
        ("stweg", "0006_verteilschluessel"),
    ]

    operations = [
        migrations.CreateModel(
            name="StwegBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jahr", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("entwurf", "Entwurf"),
                            ("vorgelegt", "Der Versammlung vorgelegt"),
                            ("genehmigt", "Genehmigt"),
                            ("abgelehnt", "Abgelehnt"),
                        ],
                        default="entwurf",
                        max_length=10,
                    ),
                ),
                ("raten", models.PositiveSmallIntegerField(default=4)),
                ("erste_faelligkeit", models.DateField(blank=True, null=True)),
                ("bemerkung", models.TextField(blank=True, default="")),
                ("genehmigt_am", models.DateTimeField(blank=True, null=True)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stweg_budgets",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "db_table": "stweg_budget",
                "ordering": ["-jahr"],
            },
        ),
        migrations.AddField(
            model_name="traktandum",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="traktanden",
                to="stweg.stwegbudget",
            ),
        ),
        migrations.CreateModel(
            name="StwegBudgetPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bezeichnung", models.CharField(max_length=200)),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="stweg.stwegbudget",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "schluessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stweg.stwegschluessel",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_budget_position",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StwegVorschreibung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_nr", models.PositiveSmallIntegerField()),
                ("rate_total", models.PositiveSmallIntegerField()),
                ("faellig_am", models.DateField()),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=12)),
                ("jahresbetrag", models.DecimalField(decimal_places=2, max_digits=12)),
                ("aufteilung", models.JSONField(blank=True, default=list)),
                ("versendet_am", models.DateTimeField(blank=True, null=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vorschreibungen",
                        to="stweg.stwegbudget",
                    ),
                ),
                (
                    "eigentuemer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.eigentuemer",
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stweg_vorschreibungen",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_vorschreibung",
                "ordering": ["faellig_am", "einheit_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="stwegbudget",
            constraint=models.UniqueConstraint(
                fields=("liegenschaft", "jahr"), name="stweg_budget_je_lg_und_jahr"
            ),
        ),
        migrations.AddConstraint(
            model_name="stwegbudget",
            constraint=models.CheckConstraint(
                condition=models.Q(("raten__in", (1, 2, 3, 4, 6, 12))),
                name="stweg_budget_raten_gueltig",
            ),
        ),
        migrations.AddConstraint(
            model_name="stwegvorschreibung",
            constraint=models.UniqueConstraint(
                fields=("budget", "einheit", "rate_nr"),
                name="stweg_vorschreibung_je_rate",
            ),
        ),
    ]
