# Generated by Django 5.2.9 on 2026-10-04 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0044_einheit_miteigentuemer"),
        ("stweg", "0007_budget_vorschreibung"),
    ]

    operations = [
        migrations.AddField(
            model_name="stimme",
            name="abgegeben_am",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stimme",
            name="kanal",
            field=models.CharField(default="verwaltung", max_length=10),
        ),
        migrations.AddField(
            model_name="versammlung",
            name="evoting",
            field=models.BooleanField(default=False, verbose_name="E-Voting im Portal"),
        ),
        migrations.AddField(
            model_name="versammlung",
            name="evoting_bis",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="E-Voting offen bis"
            ),
        ),
        migrations.AlterField(
            model_name="traktandum",
            name="mehrheitsart",
            field=models.CharField(
                choices=[
                    ("einfach_koepfe", "Mehrheit der Stimmenden (nach Köpfen)"),
                    ("einfach_quoten", "Mehrheit der Stimmenden (nach Wertquoten)"),
                    ("doppelt", "Mehrheit nach Köpfen UND Wertquoten (der Stimmenden)"),
                    ("doppelt_aller", "Mehrheit aller Eigentümer UND aller Wertquoten"),
                    (
                        "doppelt_anwesende",
                        "Mehrheit der anwesenden Eigentümer UND mehr als die Hälfte aller Wertquoten",
                    ),
                    ("einstimmig", "Einstimmigkeit aller Eigentümer"),
                    ("kenntnisnahme", "Zur Kenntnisnahme (keine Abstimmung)"),
                ],
                default="einfach_koepfe",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="zirkularbeschluss",
            name="mehrheitsart",
            field=models.CharField(
                choices=[
                    ("einfach_koepfe", "Mehrheit der Stimmenden (nach Köpfen)"),
                    ("einfach_quoten", "Mehrheit der Stimmenden (nach Wertquoten)"),
                    ("doppelt", "Mehrheit nach Köpfen UND Wertquoten (der Stimmenden)"),
                    ("doppelt_aller", "Mehrheit aller Eigentümer UND aller Wertquoten"),
                    (
                        "doppelt_anwesende",
                        "Mehrheit der anwesenden Eigentümer UND mehr als die Hälfte aller Wertquoten",
                    ),
                    ("einstimmig", "Einstimmigkeit aller Eigentümer"),
                    ("kenntnisnahme", "Zur Kenntnisnahme (keine Abstimmung)"),
                ],
                default="einstimmig",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StimmeEreignis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wert", models.CharField(max_length=10)),
                ("vorher", models.CharField(blank=True, default="", max_length=10)),
                ("kanal", models.CharField(max_length=10)),
                ("zeitpunkt", models.DateTimeField(auto_now_add=True)),
                (
                    "eigentuemer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.eigentuemer",
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "traktandum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stimm_ereignisse",
                        to="stweg.traktandum",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_stimme_ereignis",
                "ordering": ["zeitpunkt", "id"],
            },
        ),
    ]
