# Generated by Django 5.2.9 on 2026-10-04 13:35

import core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0044_einheit_miteigentuemer"),
        ("stweg", "0008_evoting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StwegDokument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategorie",
                    models.CharField(
                        choices=[
                            ("begruendungsakt", "Begründungsakt"),
                            ("reglement", "STWEG-Reglement"),
                            ("nutzungsordnung", "Nutzungs- und Verwaltungsordnung"),
                            ("versicherung", "Versicherungspolice"),
                            ("jahresrechnung", "Jahresrechnung"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("datei", models.FileField(upload_to=core.utils.get_smart_upload_path)),
                (
                    "gueltig_ab",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("gueltig_bis", models.DateField(blank=True, null=True)),
                ("sichtbar", models.BooleanField(default=True)),
                ("hochgeladen_am", models.DateTimeField(auto_now_add=True)),
                (
                    "hochgeladen_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stweg_dokumente",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "db_table": "stweg_dokument",
                "ordering": ["kategorie", "-gueltig_ab", "-id"],
            },
        ),
    ]
