# Generated by Django 5.2.9 on 2026-10-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0044_stweg_grundlagen"),
        ("stweg", "0009_dokumente"),
    ]

    operations = [
        migrations.AddField(
            model_name="stwegabrechnungposition",
            name="buchungen",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="finance.buchung"
            ),
        ),
        migrations.AddField(
            model_name="stwegakonto",
            name="buchung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finance.buchung",
            ),
        ),
        migrations.AddField(
            model_name="stwegakonto",
            name="zahlungseingang",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finance.zahlungseingang",
            ),
        ),
        migrations.AddField(
            model_name="stwegakonto",
            name="zweck",
            field=models.CharField(
                choices=[
                    ("akonto", "Akonto-Beitrag"),
                    ("fonds", "Einlage Erneuerungsfonds"),
                ],
                default="akonto",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="stwegvorschreibung",
            name="buchung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finance.buchung",
            ),
        ),
    ]
