# Generated by Django 5.2.9 on 2026-10-04 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stweg", "0010_hauptbuch"),
    ]

    operations = [
        migrations.AddField(
            model_name="zirkularbeschluss",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zirkulare",
                to="stweg.stwegbudget",
            ),
        ),
    ]
