# Generated by Django 5.2.9 on 2026-10-04 16:14

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stweg", "0011_zirkular_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="vollmacht",
            name="dokument",
            field=models.FileField(
                blank=True, null=True, upload_to=core.utils.get_smart_upload_path
            ),
        ),
    ]
