# Generated by Django 5.2.9 on 2026-10-04 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0044_einheit_miteigentuemer"),
        ("stweg", "0012_vollmacht_dokument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="traktandum",
            name="ohne_beschlussfaehigkeit",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="StwegVorgaben",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "einladungsfrist_tage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Vorgabe für neue Versammlungen; leer = 10 Tage (Systemvorgabe, nicht geprüft).",
                        null=True,
                        verbose_name="Einladungsfrist (Tage)",
                    ),
                ),
                (
                    "quorum_koepfe_prozent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Anteil aller Stockwerkeigentümer, der anwesend oder vertreten sein muss. Leer = nicht beurteilt.",
                        max_digits=5,
                        null=True,
                        verbose_name="Beschlussfähig ab Anteil der Köpfe (%)",
                    ),
                ),
                (
                    "quorum_quoten_prozent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Anteil aller Wertquoten, der anwesend oder vertreten sein muss. Leer = nicht beurteilt.",
                        max_digits=5,
                        null=True,
                        verbose_name="Beschlussfähig ab Anteil der Wertquoten (%)",
                    ),
                ),
                (
                    "anfechtungsfrist_tage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Leer = es wird keine Frist geführt.",
                        null=True,
                        verbose_name="Anfechtungsfrist (Tage ab Versand des Protokolls)",
                    ),
                ),
                (
                    "bemerkung",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Quelle (Reglement, Artikel)",
                    ),
                ),
                ("bestaetigt_am", models.DateTimeField(blank=True, null=True)),
                (
                    "bestaetigt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liegenschaft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stweg_vorgaben",
                        to="portfolio.liegenschaft",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vorgaben der Gemeinschaft",
                "db_table": "stweg_vorgaben",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quorum_koepfe_prozent__isnull", True),
                            models.Q(
                                ("quorum_koepfe_prozent__gte", 0),
                                ("quorum_koepfe_prozent__lte", 100),
                            ),
                            _connector="OR",
                        ),
                        name="stweg_vorgaben_quorum_koepfe_0_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quorum_quoten_prozent__isnull", True),
                            models.Q(
                                ("quorum_quoten_prozent__gte", 0),
                                ("quorum_quoten_prozent__lte", 100),
                            ),
                            _connector="OR",
                        ),
                        name="stweg_vorgaben_quorum_quoten_0_100",
                    ),
                ],
            },
        ),
    ]
