# Generated by Django 5.2.9 on 2026-10-05 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0044_einheit_miteigentuemer"),
        ("stweg", "0013_vorgaben"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StwegInkassoFall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("offen", "Offen"), ("erledigt", "Erledigt")],
                        default="offen",
                        max_length=10,
                    ),
                ),
                (
                    "eroeffnet_am",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("erledigt_am", models.DateField(blank=True, null=True)),
                ("retention_erklaert_am", models.DateField(blank=True, null=True)),
                ("retention_gegenstaende", models.TextField(blank=True, default="")),
                (
                    "eigentuemer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.eigentuemer",
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stweg_inkassofaelle",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_inkassofall",
                "ordering": ["-eroeffnet_am", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StwegMahnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stufe", models.PositiveSmallIntegerField()),
                ("datum", models.DateField(default=django.utils.timezone.localdate)),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=12)),
                ("frist_bis", models.DateField()),
                ("versendet_am", models.DateTimeField(blank=True, null=True)),
                ("kanal", models.CharField(blank=True, default="", max_length=10)),
                (
                    "fall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mahnungen",
                        to="stweg.stweginkassofall",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_mahnung",
                "ordering": ["stufe"],
            },
        ),
        migrations.CreateModel(
            name="StwegPfandrecht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stichtag", models.DateField()),
                ("betrag_gesamt", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "betrag_pfandberechtigt",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "betrag_ausgeschlossen",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("zeilen", models.JSONField(blank=True, default=list)),
                ("angemeldet_am", models.DateTimeField(auto_now_add=True)),
                ("eingetragen_am", models.DateField(blank=True, null=True)),
                (
                    "angemeldet_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pfandrechte",
                        to="stweg.stweginkassofall",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_pfandrecht",
                "ordering": ["-angemeldet_am"],
            },
        ),
        migrations.AddConstraint(
            model_name="stweginkassofall",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "offen")),
                fields=("einheit",),
                name="stweg_inkasso_ein_offener_fall_je_einheit",
            ),
        ),
        migrations.AddConstraint(
            model_name="stwegmahnung",
            constraint=models.UniqueConstraint(
                fields=("fall", "stufe"), name="stweg_mahnung_eine_je_stufe"
            ),
        ),
        migrations.AddConstraint(
            model_name="stwegmahnung",
            constraint=models.CheckConstraint(
                condition=models.Q(("stufe__gte", 1), ("stufe__lte", 3)),
                name="stweg_mahnung_stufe_1_bis_3",
            ),
        ),
    ]
