# Generated by Django 5.2.9 on 2026-10-05 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0044_einheit_miteigentuemer"),
        ("stweg", "0015_akonto_vorschreibung"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stwegvorgaben",
            name="verzugszins_prozent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Aus Reglement oder Gesetz. Leer = es werden keine Verzugszinsen berechnet.",
                max_digits=5,
                null=True,
                verbose_name="Verzugszins auf Beiträge (% pro Jahr)",
            ),
        ),
        migrations.CreateModel(
            name="StwegEigentuemerwechsel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        verbose_name="Eigentumsübergang (Tag des Grundbucheintrags oder Antritt)"
                    ),
                ),
                ("bemerkung", models.CharField(blank=True, default="", max_length=200)),
                (
                    "bisheriger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="crm.eigentuemer",
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stweg_wechsel",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "erfasst_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "neu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="crm.eigentuemer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_eigentuemerwechsel",
                "ordering": ["datum", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("einheit", "datum"),
                        name="stweg_wechsel_ein_wechsel_je_tag",
                    )
                ],
            },
        ),
    ]
