# Generated by Django 5.2.9 on 2026-10-05 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0044_stweg_grundlagen"),
        ("stweg", "0016_verzugszins_eigentuemerwechsel"),
    ]

    operations = [
        migrations.AddField(
            model_name="stwegakonto",
            name="an_kosten",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="stwegakonto",
            name="an_zins",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="stwegakonto",
            name="zins_buchung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finance.buchung",
            ),
        ),
    ]
