# Generated by Django 5.2.9 on 2026-10-05 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("finance", "0044_stweg_grundlagen"),
        ("portfolio", "0044_einheit_miteigentuemer"),
        ("stweg", "0017_akonto_anrechnung"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stweginkassofall",
            name="betreibung_eingeleitet_am",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stweginkassofall",
            name="betreibungsamt",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="stwegvorgaben",
            name="mahngebuehr_ab_stufe",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Leer = ab der 2. Mahnung. Gilt nur, wenn eine Mahngebühr eingetragen ist.",
                null=True,
                verbose_name="Mahngebühr ab Mahnstufe",
            ),
        ),
        migrations.AddField(
            model_name="stwegvorgaben",
            name="mahngebuehr_chf",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Aus Reglement oder Beschluss. Leer = keine Mahngebühren.",
                max_digits=8,
                null=True,
                verbose_name="Mahngebühr je Mahnung (CHF)",
            ),
        ),
        migrations.CreateModel(
            name="StwegInkassoPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("mahnspesen", "Mahngebühr"),
                            ("betreibungskosten", "Betreibungskostenvorschuss"),
                        ],
                        max_length=20,
                    ),
                ),
                ("datum", models.DateField(default=django.utils.timezone.localdate)),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=10)),
                ("text", models.CharField(max_length=200)),
                (
                    "amt",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Betreibungsamt",
                    ),
                ),
                ("storniert_am", models.DateField(blank=True, null=True)),
                (
                    "buchung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="finance.buchung",
                    ),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stweg_inkassopositionen",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "erfasst_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fall",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positionen",
                        to="stweg.stweginkassofall",
                    ),
                ),
                (
                    "mahnung",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="position",
                        to="stweg.stwegmahnung",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_inkassoposition",
                "ordering": ["datum", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("betrag__gt", 0)),
                        name="stweg_inkassoposition_betrag_pos",
                    )
                ],
            },
        ),
    ]
