# Generated by Django 5.2.9 on 2026-10-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stweg", "0018_inkassoposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="traktandum",
            name="geschaeftsart",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Art des Geschäfts"
            ),
        ),
    ]
