# Generated by Django 5.2.9 on 2026-10-05 13:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_mahnwesen_einstellungen"),
        ("portfolio", "0044_einheit_miteigentuemer"),
        ("stweg", "0019_traktandum_geschaeftsart"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StwegBefreiung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "begruendung",
                    models.CharField(
                        max_length=200,
                        verbose_name="Begründung (Reglement, Beschluss, Artikel)",
                    ),
                ),
                (
                    "erfasst_am",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "einheit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "erfasst_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "schluessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="befreiungen",
                        to="stweg.stwegschluessel",
                    ),
                ),
            ],
            options={
                "db_table": "stweg_befreiung",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schluessel", "einheit"),
                        name="stweg_befreiung_je_einheit",
                    )
                ],
            },
        ),
    ]
