# Generated by Django 5.2.9 on 2026-10-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stweg", "0020_befreiung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stwegdokument",
            name="kategorie",
            field=models.CharField(
                choices=[
                    ("begruendungsakt", "Begründungsakt"),
                    ("reglement", "STWEG-Reglement"),
                    ("nutzungsordnung", "Nutzungs- und Verwaltungsordnung"),
                    ("gebaeudeversicherung", "Gebäudeversicherungsnachweis"),
                    ("versicherung", "Weitere Versicherungspolice (z. B. Haftpflicht)"),
                    ("jahresrechnung", "Jahresrechnung"),
                    ("sonstiges", "Sonstiges"),
                ],
                max_length=20,
            ),
        ),
    ]
