# Generated by Django 5.2.9 on 2026-04-07 08:27

import core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchadenMeldung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "titel",
                    models.CharField(max_length=200, verbose_name="Titel / Schaden"),
                ),
                ("beschreibung", models.TextField(verbose_name="Beschreibung")),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.utils.get_smart_upload_path,
                    ),
                ),
                (
                    "email_melder",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="E-Mail Melder",
                    ),
                ),
                (
                    "tel_melder",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Telefon Melder",
                    ),
                ),
                (
                    "zutritt",
                    models.CharField(
                        choices=[
                            ("telefon", "Termin via Telefon"),
                            ("passpartout", "Passpartout (Schlüssel vorhanden)"),
                        ],
                        default="telefon",
                        max_length=20,
                        verbose_name="Zutritt / Termin",
                    ),
                ),
                (
                    "mieter_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Mieter E-Mail (Legacy)",
                    ),
                ),
                (
                    "mieter_telefon",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Mieter Telefon (Legacy)",
                    ),
                ),
                (
                    "prioritaet",
                    models.CharField(
                        default="mittel", max_length=20, verbose_name="Priorität"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("neu", "Neu"),
                            ("in_bearbeitung", "In Bearbeitung"),
                            ("warte_auf_mieter", "Warte auf Mieter"),
                            ("erledigt", "Erledigt"),
                        ],
                        default="neu",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("gelesen", models.BooleanField(default=False)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("aktualisiert_am", models.DateTimeField(auto_now=True)),
                (
                    "betroffene_einheit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schaeden",
                        to="portfolio.einheit",
                    ),
                ),
                (
                    "gemeldet_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gemeldete_schaeden",
                        to="crm.mieter",
                    ),
                ),
                (
                    "liegenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schaeden",
                        to="portfolio.liegenschaft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket / Schaden",
                "verbose_name_plural": "Tickets / Schäden",
                "db_table": "core_schadenmeldung",
                "ordering": ["-erstellt_am"],
            },
        ),
        migrations.CreateModel(
            name="HandwerkerAuftrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="offen", max_length=20)),
                ("beauftragt_am", models.DateTimeField(auto_now_add=True)),
                ("bemerkung", models.TextField(blank=True)),
                (
                    "handwerker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auftraege",
                        to="crm.handwerker",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handwerker_auftraege",
                        to="tickets.schadenmeldung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Handwerker-Auftrag",
                "db_table": "core_handwerkerauftrag",
            },
        ),
        migrations.CreateModel(
            name="TicketNachricht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("absender_name", models.CharField(max_length=100)),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("system", "System"),
                            ("mail_antwort", "Mail Antwort"),
                            ("antwort_senden", "Antwort Senden"),
                            ("handwerker_mail", "Handwerker Mail"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                ("nachricht", models.TextField()),
                (
                    "datei",
                    models.FileField(blank=True, null=True, upload_to="ticket_anhang/"),
                ),
                (
                    "cc_email",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="CC (Optional)"
                    ),
                ),
                ("gelesen", models.BooleanField(default=False)),
                ("is_intern", models.BooleanField(default=False)),
                ("is_von_verwaltung", models.BooleanField(default=False)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "empfaenger_handwerker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.handwerker",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nachrichten",
                        to="tickets.schadenmeldung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historie / Nachricht",
                "db_table": "core_ticketnachricht",
                "ordering": ["-erstellt_am"],
            },
        ),
    ]
