# Generated by Django 5.2.9 on 2026-05-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schadenmeldung",
            name="kategorie",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Kategorie"
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="objekt",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Objekt"
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="raum",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Raum"
            ),
        ),
    ]
