# Generated by Django 5.2.9 on 2026-05-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_schadenmeldung_kategorie_schadenmeldung_objekt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schadenmeldung",
            name="melder_nachname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nachname Melder"
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="melder_vorname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Vorname Melder"
            ),
        ),
        migrations.AlterField(
            model_name="schadenmeldung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu"),
                    ("in_bearbeitung", "In Bearbeitung"),
                    ("warte_auf_mieter", "Warte auf Mieter"),
                    ("warte_auf_handwerker", "Warte auf Handwerker"),
                    ("erledigt", "Erledigt"),
                ],
                default="neu",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="ticketnachricht",
            name="typ",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("system", "System"),
                    ("mail_antwort", "Mail Antwort"),
                    ("antwort_senden", "Antwort Senden"),
                    ("handwerker_mail", "Handwerker Mail"),
                    ("email", "Ausgehende E-Mail"),
                ],
                default="chat",
                max_length=20,
            ),
        ),
    ]
