# Generated by Django 5.2.9 on 2026-07-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_debitorenrechnung_qr_referenz"),
        ("tickets", "0003_schadenmeldung_melder_nachname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="handwerkerauftrag",
            name="kosten_effektiv",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Effektive Kosten (CHF)",
            ),
        ),
        migrations.AddField(
            model_name="handwerkerauftrag",
            name="kosten_geschaetzt",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Kostenschätzung (CHF)",
            ),
        ),
        migrations.AddField(
            model_name="handwerkerauftrag",
            name="kreditoren_rechnung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handwerker_auftraege",
                to="finance.kreditorenrechnung",
            ),
        ),
    ]
