# Generated by Django 5.2.9 on 2026-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_handwerkerauftrag_kosten_effektiv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="handwerkerauftrag",
            name="freigabe_datum",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Freigabe am"
            ),
        ),
        migrations.AddField(
            model_name="handwerkerauftrag",
            name="freigabe_kommentar",
            field=models.TextField(
                blank=True, default="", verbose_name="Kommentar Eigentümer"
            ),
        ),
        migrations.AddField(
            model_name="handwerkerauftrag",
            name="freigabe_status",
            field=models.CharField(
                choices=[
                    ("nicht_noetig", "Keine Freigabe nötig"),
                    ("ausstehend", "Freigabe ausstehend"),
                    ("freigegeben", "Freigegeben"),
                    ("abgelehnt", "Abgelehnt"),
                ],
                default="nicht_noetig",
                max_length=20,
                verbose_name="Freigabe-Status",
            ),
        ),
    ]
