# Generated by Django 5.2.9 on 2026-07-12 15:41

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_handwerkerauftrag_freigabe_datum_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchadenFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bild", models.ImageField(upload_to=core.utils.get_smart_upload_path)),
                (
                    "beschreibung",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("hochgeladen_am", models.DateTimeField(auto_now_add=True)),
                (
                    "hochgeladen_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schaden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="tickets.schadenmeldung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schaden-Foto",
                "verbose_name_plural": "Schaden-Fotos",
                "db_table": "core_schadenfoto",
                "ordering": ["hochgeladen_am"],
            },
        ),
    ]
