# Generated by Django 5.2.9 on 2026-07-13 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_seed_lebensdauer"),
        ("tickets", "0006_schadenfoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="schadenmeldung",
            name="ausstattung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schaeden",
                to="portfolio.ausstattung",
            ),
        ),
    ]
