# Generated by Django 5.2.9 on 2026-09-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0048_referenzzinsstand"),
        ("finance", "0042_kreditor_weiterverrechnung_eigentuemer"),
        ("portfolio", "0041_versicherung_selbstbehalt"),
        ("tickets", "0010_organisation_pflicht"),
    ]

    operations = [
        migrations.CreateModel(
            name="Versicherungsfall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schadennummer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="Schadennummer",
                    ),
                ),
                ("gemeldet_am", models.DateField(verbose_name="Gemeldet am")),
                (
                    "schadensumme",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Schadensumme (CHF)",
                    ),
                ),
                (
                    "selbstbehalt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Selbstbehalt (CHF)",
                    ),
                ),
                (
                    "selbstbehalt_traeger",
                    models.CharField(
                        choices=[
                            ("eigentuemer", "Eigentümer"),
                            ("mieter", "Mieter (Überwälzung)"),
                        ],
                        default="eigentuemer",
                        max_length=12,
                        verbose_name="Selbstbehalt trägt",
                    ),
                ),
                (
                    "entschaedigung_erhalten",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Entschädigung erhalten (CHF)",
                    ),
                ),
                (
                    "entschaedigung_am",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Entschädigung eingegangen am",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("gemeldet", "Gemeldet"),
                            ("abklaerung", "In Abklärung"),
                            ("entschaedigt", "Entschädigt"),
                            ("abgelehnt", "Abgelehnt"),
                        ],
                        default="gemeldet",
                        max_length=12,
                    ),
                ),
                ("bemerkung", models.CharField(blank=True, default="", max_length=255)),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="crm.organisation",
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "police",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faelle",
                        to="portfolio.versicherung",
                    ),
                ),
                (
                    "selbstbehalt_rechnung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="finance.debitorenrechnung",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versicherungsfaelle",
                        to="tickets.schadenmeldung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versicherungsfall",
                "verbose_name_plural": "Versicherungsfälle",
                "ordering": ["-gemeldet_am", "-id"],
            },
        ),
    ]
