# Generated by Django 5.2.9 on 2026-10-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0011_versicherungsfall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schadenmeldung",
            name="status",
            field=models.CharField(
                choices=[
                    ("neu", "Neu"),
                    ("in_bearbeitung", "In Bearbeitung"),
                    ("warte_auf_mieter", "Warte auf Mieter"),
                    ("warte_auf_handwerker", "Warte auf Handwerker"),
                    ("wartet_auf_rechnung", "Wartet auf Rechnung"),
                    ("erledigt", "Erledigt"),
                ],
                default="neu",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
