# Generated by Django 5.2.9 on 2026-10-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0012_status_wartet_auf_rechnung"),
    ]

    operations = [
        migrations.AddField(
            model_name="handwerkerauftrag",
            name="termin_am",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Termin"),
        ),
        migrations.AddField(
            model_name="handwerkerauftrag",
            name="termin_status",
            field=models.CharField(
                choices=[
                    ("offen", "Kein Termin"),
                    ("vereinbart", "Termin vereinbart"),
                    ("abgesagt", "Termin abgesagt"),
                ],
                default="offen",
                max_length=12,
                verbose_name="Terminstatus",
            ),
        ),
    ]
