# Generated by Django 5.2.9 on 2026-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0013_handwerkerauftrag_termin"),
    ]

    operations = [
        migrations.AddField(
            model_name="schadenmeldung",
            name="bauteil",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="Betroffenes Bauteil",
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="kostentraeger",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="Kostenträger (STWEG)",
            ),
        ),
    ]
