# Generated by Django 5.2.9 on 2026-10-05 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0014_stweg_bauteil_kostentraeger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="schadenmeldung",
            name="faellig_bis",
            field=models.DateField(
                blank=True, null=True, verbose_name="Erledigen bis (SLA)"
            ),
        ),
        migrations.AddField(
            model_name="schadenmeldung",
            name="zugewiesen_an",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zugewiesene_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Zuständig (intern)",
            ),
        ),
    ]
